import type { LiteLlmProviderEntry } from './litellm.types';

/**
 * Static fallback snapshot of LiteLLM's provider_create_fields.json, mapped to
 * LiteLlmProviderEntry and deduped by provider id (`name`).
 *
 * Served by LiteLlmAdminService.fetchProviders() when the live GitHub fetch
 * fails and no cache is warm, so the provider picker never renders empty on a
 * transient network blip / rate-limit. Refresh by re-running the live fetch.
 * Snapshot taken 2026-06-17 from BerriAI/litellm main.
 */
export const FALLBACK_PROVIDERS: LiteLlmProviderEntry[] = [
  { name: 'aiml', label: 'AI/ML API', modelHint: 'aiml/flux-pro/v1.1' },
  { name: 'ai21', label: 'Ai21', modelHint: 'gpt-3.5-turbo' },
  { name: 'ai21_chat', label: 'Ai21 Chat', modelHint: 'gpt-3.5-turbo' },
  {
    name: 'aiohttp_openai',
    label: 'Aiohttp Openai',
    modelHint: 'gpt-3.5-turbo',
  },
  { name: 'bedrock', label: 'Amazon Bedrock', modelHint: 'claude-3-opus' },
  { name: 'anthropic', label: 'Anthropic', modelHint: 'claude-3-opus' },
  {
    name: 'anthropic_text',
    label: 'Anthropic Text',
    modelHint: 'gpt-3.5-turbo',
  },
  { name: 'assemblyai', label: 'AssemblyAI', modelHint: 'gpt-3.5-turbo' },
  { name: 'auto_router', label: 'Auto Router', modelHint: 'gpt-3.5-turbo' },
  {
    name: 'sagemaker_chat',
    label: 'AWS SageMaker',
    modelHint: 'sagemaker/jumpstart-dft-meta-textgeneration-llama-2-7b',
  },
  { name: 'azure', label: 'Azure', modelHint: 'azure/my-deployment' },
  {
    name: 'azure_ai',
    label: 'Azure AI Foundry (Studio)',
    modelHint: 'azure_ai/command-r-plus',
  },
  { name: 'azure_text', label: 'Azure Text', modelHint: 'gpt-3.5-turbo' },
  { name: 'baseten', label: 'Baseten', modelHint: 'gpt-3.5-turbo' },
  { name: 'bytez', label: 'Bytez', modelHint: 'gpt-3.5-turbo' },
  { name: 'cerebras', label: 'Cerebras', modelHint: 'gpt-3.5-turbo' },
  { name: 'clarifai', label: 'Clarifai', modelHint: 'gpt-3.5-turbo' },
  { name: 'cloudflare', label: 'Cloudflare', modelHint: 'gpt-3.5-turbo' },
  { name: 'codestral', label: 'Codestral', modelHint: 'gpt-3.5-turbo' },
  { name: 'cohere', label: 'Cohere', modelHint: 'gpt-3.5-turbo' },
  { name: 'cohere_chat', label: 'Cohere Chat', modelHint: 'gpt-3.5-turbo' },
  { name: 'cometapi', label: 'Cometapi', modelHint: 'gpt-3.5-turbo' },
  { name: 'compactifai', label: 'Compactifai', modelHint: 'gpt-3.5-turbo' },
  { name: 'custom', label: 'Custom', modelHint: 'gpt-3.5-turbo' },
  { name: 'custom_openai', label: 'Custom Openai', modelHint: 'gpt-3.5-turbo' },
  { name: 'dashscope', label: 'Dashscope', modelHint: 'gpt-3.5-turbo' },
  { name: 'databricks', label: 'Databricks', modelHint: 'gpt-3.5-turbo' },
  { name: 'datarobot', label: 'Datarobot', modelHint: 'gpt-3.5-turbo' },
  { name: 'deepgram', label: 'Deepgram', modelHint: 'gpt-3.5-turbo' },
  {
    name: 'deepinfra',
    label: 'DeepInfra',
    modelHint: 'deepinfra/<any-model-on-deepinfra>',
  },
  { name: 'deepseek', label: 'Deepseek', modelHint: 'gpt-3.5-turbo' },
  {
    name: 'docker_model_runner',
    label: 'Docker Model Runner',
    modelHint: 'gpt-3.5-turbo',
  },
  { name: 'dotprompt', label: 'Dotprompt', modelHint: 'gpt-3.5-turbo' },
  { name: 'elevenlabs', label: 'ElevenLabs', modelHint: 'gpt-3.5-turbo' },
  { name: 'empower', label: 'Empower', modelHint: 'gpt-3.5-turbo' },
  {
    name: 'fal_ai',
    label: 'Fal AI',
    modelHint: 'fal_ai/fal-ai/flux-pro/v1.1-ultra',
  },
  {
    name: 'featherless_ai',
    label: 'Featherless Ai',
    modelHint: 'gpt-3.5-turbo',
  },
  { name: 'fireworks_ai', label: 'Fireworks AI', modelHint: 'gpt-3.5-turbo' },
  { name: 'friendliai', label: 'Friendliai', modelHint: 'gpt-3.5-turbo' },
  { name: 'galadriel', label: 'Galadriel', modelHint: 'gpt-3.5-turbo' },
  { name: 'github', label: 'Github', modelHint: 'gpt-3.5-turbo' },
  {
    name: 'github_copilot',
    label: 'Github Copilot',
    modelHint: 'gpt-3.5-turbo',
  },
  { name: 'gemini', label: 'Google AI Studio', modelHint: 'gemini-pro' },
  { name: 'gradient_ai', label: 'GradientAI', modelHint: 'gpt-3.5-turbo' },
  { name: 'groq', label: 'Groq', modelHint: 'gpt-3.5-turbo' },
  { name: 'heroku', label: 'Heroku', modelHint: 'gpt-3.5-turbo' },
  { name: 'huggingface', label: 'Huggingface', modelHint: 'gpt-3.5-turbo' },
  { name: 'humanloop', label: 'Humanloop', modelHint: 'gpt-3.5-turbo' },
  { name: 'hyperbolic', label: 'Hyperbolic', modelHint: 'gpt-3.5-turbo' },
  { name: 'infinity', label: 'Infinity', modelHint: 'gpt-3.5-turbo' },
  { name: 'jina_ai', label: 'Jina AI', modelHint: 'jina_ai/' },
  { name: 'lambda_ai', label: 'Lambda Ai', modelHint: 'gpt-3.5-turbo' },
  { name: 'langfuse', label: 'Langfuse', modelHint: 'gpt-3.5-turbo' },
  { name: 'lemonade', label: 'Lemonade', modelHint: 'gpt-3.5-turbo' },
  { name: 'litellm_proxy', label: 'Litellm Proxy', modelHint: 'gpt-3.5-turbo' },
  { name: 'llamafile', label: 'Llamafile', modelHint: 'gpt-3.5-turbo' },
  { name: 'lm_studio', label: 'Lm Studio', modelHint: 'gpt-3.5-turbo' },
  { name: 'maritalk', label: 'Maritalk', modelHint: 'gpt-3.5-turbo' },
  { name: 'meta_llama', label: 'Meta Llama', modelHint: 'gpt-3.5-turbo' },
  { name: 'milvus', label: 'Milvus', modelHint: 'gpt-3.5-turbo' },
  { name: 'mistral', label: 'Mistral AI', modelHint: 'gpt-3.5-turbo' },
  { name: 'minimax', label: 'MiniMax', modelHint: 'minimax/MiniMax-M2' },
  { name: 'moonshot', label: 'Moonshot', modelHint: 'gpt-3.5-turbo' },
  { name: 'morph', label: 'Morph', modelHint: 'gpt-3.5-turbo' },
  { name: 'nebius', label: 'Nebius', modelHint: 'gpt-3.5-turbo' },
  { name: 'nlp_cloud', label: 'Nlp Cloud', modelHint: 'gpt-3.5-turbo' },
  { name: 'novita', label: 'Novita', modelHint: 'gpt-3.5-turbo' },
  { name: 'nscale', label: 'Nscale', modelHint: 'gpt-3.5-turbo' },
  { name: 'nvidia_nim', label: 'Nvidia Nim', modelHint: 'gpt-3.5-turbo' },
  { name: 'ollama', label: 'Ollama', modelHint: 'gpt-3.5-turbo' },
  { name: 'ollama_chat', label: 'Ollama Chat', modelHint: 'gpt-3.5-turbo' },
  { name: 'oobabooga', label: 'Oobabooga', modelHint: 'gpt-3.5-turbo' },
  { name: 'openai', label: 'OpenAI', modelHint: 'gpt-3.5-turbo' },
  { name: 'openai_like', label: 'Openai Like', modelHint: 'gpt-3.5-turbo' },
  {
    name: 'text-completion-openai',
    label: 'OpenAI Text Completion',
    modelHint: 'gpt-3.5-turbo',
  },
  { name: 'openrouter', label: 'Openrouter', modelHint: 'gpt-3.5-turbo' },
  {
    name: 'oci',
    label: 'Oracle Cloud Infrastructure (OCI)',
    modelHint: 'oci/xai.grok-3',
  },
  { name: 'ovhcloud', label: 'Ovhcloud', modelHint: 'gpt-3.5-turbo' },
  { name: 'perplexity', label: 'Perplexity', modelHint: 'gpt-3.5-turbo' },
  { name: 'petals', label: 'Petals', modelHint: 'gpt-3.5-turbo' },
  { name: 'pg_vector', label: 'Pg Vector', modelHint: 'gpt-3.5-turbo' },
  { name: 'predibase', label: 'Predibase', modelHint: 'gpt-3.5-turbo' },
  { name: 'recraft', label: 'Recraft', modelHint: 'gpt-3.5-turbo' },
  { name: 'replicate', label: 'Replicate', modelHint: 'gpt-3.5-turbo' },
  { name: 'runwayml', label: 'Runwayml', modelHint: 'gpt-3.5-turbo' },
  { name: 'sagemaker', label: 'Sagemaker', modelHint: 'gpt-3.5-turbo' },
  { name: 'sambanova', label: 'Sambanova', modelHint: 'gpt-3.5-turbo' },
  { name: 'sap', label: 'SAP Generative AI Hub', modelHint: 'sap/gpt-4' },
  { name: 'snowflake', label: 'Snowflake', modelHint: 'snowflake/mistral-7b' },
  { name: 'soniox', label: 'Soniox', modelHint: 'soniox/stt-async-v4' },
  {
    name: 'text-completion-codestral',
    label: 'Text-Completion-Codestral',
    modelHint: 'gpt-3.5-turbo',
  },
  { name: 'together_ai', label: 'TogetherAI', modelHint: 'gpt-3.5-turbo' },
  { name: 'topaz', label: 'Topaz', modelHint: 'gpt-3.5-turbo' },
  { name: 'triton', label: 'Triton', modelHint: 'gpt-3.5-turbo' },
  { name: 'v0', label: 'V0', modelHint: 'gpt-3.5-turbo' },
  {
    name: 'vercel_ai_gateway',
    label: 'Vercel Ai Gateway',
    modelHint: 'gpt-3.5-turbo',
  },
  {
    name: 'vertex_ai',
    label: 'Vertex AI (Anthropic, Gemini, etc.)',
    modelHint: 'gemini-pro',
  },
  {
    name: 'vertex_ai_beta',
    label: 'Vertex Ai Beta',
    modelHint: 'gpt-3.5-turbo',
  },
  { name: 'hosted_vllm', label: 'vllm', modelHint: 'gpt-3.5-turbo' },
  { name: 'vllm', label: 'Vllm', modelHint: 'gpt-3.5-turbo' },
  {
    name: 'volcengine',
    label: 'VolcEngine',
    modelHint: 'volcengine/<any-model-on-volcengine>',
  },
  { name: 'voyage', label: 'Voyage AI', modelHint: 'voyage/' },
  { name: 'wandb', label: 'Wandb', modelHint: 'gpt-3.5-turbo' },
  {
    name: 'watsonx',
    label: 'Watsonx',
    modelHint: 'watsonx/ibm/granite-3-3-8b-instruct',
  },
  { name: 'watsonx_text', label: 'Watsonx Text', modelHint: 'gpt-3.5-turbo' },
  { name: 'xai', label: 'xAI', modelHint: 'gpt-3.5-turbo' },
  { name: 'xinference', label: 'Xinference', modelHint: 'gpt-3.5-turbo' },
  { name: 'cursor', label: 'Cursor', modelHint: 'cursor/claude-4-sonnet' },
];
