/**
 * StorybookChatsHarness — mounts the real useChatsWebSocket + useChatsUsageStats
 * hooks over isolated state so WS-event replay from WSEventPlayer exercises the
 * production reducer path. DO NOT add feature behavior here — production changes
 * belong in the real ChatsPage.
 *
 * Critical: threadTokenUsageByNode state is owned by useChatsUsageStats (not by
 * this harness). The harness passes usageStats.setThreadTokenUsageByNode into
 * useChatsWebSocket so both hooks read/write the same map.
 */
import React, { useCallback, useEffect, useRef, useState } from 'react';

import type { GraphPreviewDto, ThreadDto } from '../../../autogenerated';
import { GraphPreviewDtoStatusEnum } from '../../../autogenerated';
import { useThreadMessageStore } from '../../../hooks/useThreadMessageStore';
import type { ToastMessageApi } from '../../../utils/toastAdapter';
import { ThreadTokenUsageLine } from '../../chats/components/ThreadTokenUsageLine';
import { useChatsUsageStats } from '../../chats/hooks/useChatsUsageStats';
import { useChatsWebSocket } from '../../chats/hooks/useChatsWebSocket';
import type {
  DraftThread,
  GraphCacheEntry,
  MessageMeta,
} from '../../chats/types';
import ThreadMessagesView from '../../graphs/components/ThreadMessagesView';
import type { LoadedFixture } from './ws-replay.types';

// ---------------------------------------------------------------------------
// Harness-local no-op toast — avoids wiring the full sonner provider.
// The return value satisfies ToastMessageApi's MessageType (callable + thenable).
// ---------------------------------------------------------------------------

type MessageType = (() => void) & PromiseLike<boolean>;

const makeNoop = (): MessageType => {
  const fn = () => {};
  (fn as unknown as { then: PromiseLike<boolean>['then'] }).then = (
    onFulfilled,
  ) => Promise.resolve(true).then(onFulfilled);
  return fn as MessageType;
};

const noopToast: ToastMessageApi = {
  error: () => makeNoop(),
  success: () => makeNoop(),
  info: () => makeNoop(),
  warning: () => makeNoop(),
  loading: () => makeNoop(),
  open: () => makeNoop(),
  destroy: () => {},
};

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

interface StorybookChatsHarnessProps {
  fixture: LoadedFixture;
  resetToken: number; // consumed externally via <StorybookChatsHarness key={resetToken} />
  onAggregateUsageChange?: (totalPrice: number | undefined) => void;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export const StorybookChatsHarness: React.FC<StorybookChatsHarnessProps> = ({
  fixture,
  onAggregateUsageChange,
}) => {
  // ── Harness-local state ────────────────────────────────────────────────────

  const [threads, setThreads] = useState<ThreadDto[]>([
    {
      id: fixture.threadId,
      graphId: fixture.graphId,
      status: 'running',
      externalThreadId: '',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      name: null,
    },
  ]);

  const [selectedThreadId, setSelectedThreadId] = useState<string | undefined>(
    fixture.threadId,
  );

  const [selectedThreadShadow, setSelectedThreadShadow] =
    useState<ThreadDto | null>(null);

  const [draftThread, setDraftThread] = useState<DraftThread | null>(null);

  const [messageMeta, setMessageMeta] = useState<Record<string, MessageMeta>>(
    {},
  );

  const [graphCache, setGraphCache] = useState<Record<string, GraphCacheEntry>>(
    () => {
      const previewGraph: GraphPreviewDto = {
        id: fixture.graphId,
        name: 'Harness Graph',
        version: '1',
        targetVersion: '1',
        status: GraphPreviewDtoStatusEnum.Running,
        triggerNodes: [],
        nodeDisplayNames: {},
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        agents: [
          { nodeId: 'supervisor', name: 'Supervisor', description: undefined },
          {
            nodeId: 'researcher-1',
            name: 'Researcher 1',
            description: undefined,
          },
          {
            nodeId: 'researcher-2',
            name: 'Researcher 2',
            description: undefined,
          },
        ],
      };

      return {
        [fixture.graphId]: {
          graph: previewGraph,
          nodeDisplayNames: {},
          triggerNodes: [],
        },
      };
    },
  );

  // ── Refs ───────────────────────────────────────────────────────────────────

  const threadsRef = useRef<ThreadDto[]>(threads);
  useEffect(() => {
    threadsRef.current = threads;
  }, [threads]);

  const pendingThreadSelectionRef = useRef<string | null>(null);

  // ── Message store ──────────────────────────────────────────────────────────

  const messageStore = useThreadMessageStore();

  // ── Stub callbacks ─────────────────────────────────────────────────────────

  const sortThreadsByTimestampDesc = useCallback(
    (list: ThreadDto[]) =>
      [...list].sort(
        (a, b) =>
          new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime(),
      ),
    [],
  );

  const getThreadTimestamp = useCallback(
    (t: ThreadDto) => new Date(t.updatedAt).getTime(),
    [],
  );

  const ensureGraphsLoaded = useCallback(async () => {}, []);

  // ── useChatsUsageStats — MUST be called before useChatsWebSocket ───────────

  const selectedThread = threads.find((t) => t.id === selectedThreadId);

  const usageStats = useChatsUsageStats({
    toastMessage: noopToast,
    selectedThread,
    selectedThreadId,
    selectedThreadIsDraft: false,
    selectedAgentNodeId: null,
    graphCache,
    getFullGraph: () => undefined,
  });

  // ── useChatsWebSocket — wires every dep from UseChatsWebSocketDeps ─────────

  useChatsWebSocket({
    graphFilterId: fixture.graphId,
    selectedThreadId,
    draftThread,

    threadsRef,
    pendingThreadSelectionRef,

    setThreads,
    setSelectedThreadId,
    setSelectedThreadShadow,
    setDraftThread,
    setExternalThreadIds: messageStore.setExternalThreadIds,
    setMessageMeta,
    // B1 guard: setThreadTokenUsageByNode comes from usageStats, NOT from a
    // local useState — so both hooks share the same state.
    setThreadTokenUsageByNode: usageStats.setThreadTokenUsageByNode,

    messages: messageStore.messages,
    pendingMessages: messageStore.pendingMessages,
    updateMessages: messageStore.updateMessages,
    updatePendingMessages: messageStore.updatePendingMessages,
    externalThreadIds: messageStore.externalThreadIds,

    sortThreadsByTimestampDesc,
    getThreadTimestamp,
    ensureGraphsLoaded,

    graphCache,
    setGraphCache,
    // real fn so running→done transition invalidates the REST snapshot cache
    invalidateThreadUsageStats: usageStats.invalidateThreadUsageStats,
  });

  // ── Forward aggregate usage to parent ─────────────────────────────────────

  useEffect(() => {
    onAggregateUsageChange?.(usageStats.selectedThreadHeaderUsage?.totalPrice);
  }, [
    onAggregateUsageChange,
    usageStats.selectedThreadHeaderUsage?.totalPrice,
  ]);

  // ── Silence unused-var lint for selectedThreadShadow and messageMeta.
  // They are required by the hook contract and updated via setters passed in,
  // but the harness render does not consume them directly.
  void selectedThreadShadow;
  void messageMeta;

  // ── Render ─────────────────────────────────────────────────────────────────

  const messagesForSelectedThread =
    messageStore.messages[selectedThreadId ?? '']?.all ?? [];
  const pendingMessagesForSelectedThread =
    messageStore.pendingMessages[selectedThreadId ?? '']?.all ?? [];
  const selectedStatus = threads.find((t) => t.id === selectedThreadId)?.status;

  return (
    <div className="flex flex-col gap-3">
      <ThreadTokenUsageLine
        usage={usageStats.selectedThreadHeaderUsage}
        inFlightSum={usageStats.selectedThreadHeaderInFlightSum}
        contextPercent={usageStats.selectedThreadHeaderContextPercent}
        contextMaxTokens={usageStats.selectedThreadHeaderContextMaxTokens}
      />
      <ThreadMessagesView
        messages={messagesForSelectedThread}
        messagesLoading={false}
        selectedThreadId={selectedThreadId}
        isAgentNode={true}
        pendingMessages={pendingMessagesForSelectedThread}
        currentThreadLastRunId={null}
        isNodeRunning={selectedStatus === 'running'}
        isThreadStopped={
          selectedStatus === 'done' || selectedStatus === 'stopped'
        }
      />
    </div>
  );
};
