// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest';

import { cleanup, render, screen, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, beforeAll, describe, expect, it, vi } from 'vitest';

import type { TemplateDto } from '../../../autogenerated';
import { TemplateDtoKindEnum } from '../../../autogenerated';
import { TemplateSidebar } from './TemplateSidebar';

// Radix ScrollArea touches ResizeObserver, absent in jsdom.
beforeAll(() => {
  if (!('ResizeObserver' in globalThis)) {
    globalThis.ResizeObserver = class {
      observe() {}
      unobserve() {}
      disconnect() {}
    } as unknown as typeof ResizeObserver;
  }
});

afterEach(() => {
  cleanup();
});

const makeTemplate = (over: Partial<TemplateDto>): TemplateDto => ({
  id: 'id',
  name: 'Name',
  description: 'desc',
  kind: TemplateDtoKindEnum.Tool,
  schema: {},
  ...over,
});

const renderSidebar = (templates: TemplateDto[]) => {
  return render(
    <TemplateSidebar
      templates={templates}
      onTemplateClick={vi.fn()}
      onClose={vi.fn()}
    />,
  );
};

describe('TemplateSidebar category grouping', () => {
  const simpleAgent = makeTemplate({
    id: 'simple-agent',
    name: 'Simple agent',
    kind: TemplateDtoKindEnum.SimpleAgent,
  });
  const claudeAgent = makeTemplate({
    id: 'claude-agent',
    name: 'Claude agent',
    kind: TemplateDtoKindEnum.ClaudeAgent,
  });
  const webSearch = makeTemplate({
    id: 'web-search',
    name: 'Web search',
    kind: TemplateDtoKindEnum.Tool,
  });

  it('groups Simple and Claude agents under a single "Agents" category', () => {
    renderSidebar([simpleAgent, claudeAgent, webSearch]);

    const agentsHeader = screen.getByRole('button', { name: /Agents/ });
    expect(within(agentsHeader).getByText('2')).toBeInTheDocument();

    // The raw per-kind sections must not leak as their own categories.
    expect(
      screen.queryByRole('button', { name: /claudeAgent/ }),
    ).not.toBeInTheDocument();
    expect(
      screen.queryByRole('button', { name: /^Agent 1$/ }),
    ).not.toBeInTheDocument();
  });

  it('keeps non-agent kinds in their own category', () => {
    renderSidebar([simpleAgent, claudeAgent, webSearch]);

    const toolsHeader = screen.getByRole('button', { name: /Tools/ });
    expect(within(toolsHeader).getByText('1')).toBeInTheDocument();
  });

  it('reveals both agent templates when the Agents category is expanded', async () => {
    const user = userEvent.setup();
    renderSidebar([simpleAgent, claudeAgent, webSearch]);

    await user.click(screen.getByRole('button', { name: /Agents/ }));

    expect(screen.getByText('Simple agent')).toBeInTheDocument();
    expect(screen.getByText('Claude agent')).toBeInTheDocument();
  });
});
