import Form from '@rjsf/core';
import type {
  BaseInputTemplateProps,
  FieldProps,
  FieldTemplateProps,
  ObjectFieldTemplateProps,
  RegistryFieldsType,
  RegistryWidgetsType,
  RJSFSchema,
  TemplatesType,
  UiSchema,
  WidgetProps,
} from '@rjsf/utils';
import validator from '@rjsf/validator-ajv8';
import {
  AlertTriangle,
  Check,
  ChevronsUpDown,
  Copy,
  Maximize2,
  X,
} from 'lucide-react';
import React, { useCallback, useEffect, useMemo, useState } from 'react';

import { gitRepositoriesApi, secretsApi } from '../../../api';
import type {
  GitRepositoryDto,
  LiteLlmModelDto,
  SecretResponseDto,
} from '../../../autogenerated';
import {
  Alert,
  AlertDescription,
  AlertTitle,
} from '../../../components/ui/alert';
import { Badge } from '../../../components/ui/badge';
import { Button } from '../../../components/ui/button';
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from '../../../components/ui/command';
import { Input } from '../../../components/ui/input';
import {
  KeyValueInput,
  type KeyValuePair,
} from '../../../components/ui/key-value-input';
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '../../../components/ui/popover';
import { Switch } from '../../../components/ui/switch';
import { Textarea } from '../../../components/ui/textarea';
import { API_URL } from '../../../config';
import type { SchemaProperty } from '../types';
import { getSchemaTypeName } from '../utils/schemaUtils';
import { ArrayTagInput } from './ArrayTagInput';

type FormData = Record<string, unknown>;
type UiSchemaShape = UiSchema<FormData, RJSFSchema, FormContext>;

type FormContext = {
  liteLlmModels: LiteLlmModelDto[];
  litellmModelsLoading: boolean;
  openExpandedTextarea: (fieldKey: string, value: string) => void;
  openAiSuggestion: (
    fieldKey: string,
    fieldLabel: string,
    value?: unknown,
  ) => void;
  aiSuggestionEnabled: boolean;
  githubAppEnabled: boolean;
  formData: FormData;
};

const handleNumberWheel: React.WheelEventHandler<HTMLElement> = (event) => {
  if (event.target instanceof HTMLInputElement) {
    event.target.blur();
  }
};

const getFormContext = (props: {
  formContext?: unknown;
  registry?: { formContext?: unknown };
}): FormContext => {
  const ctx = props.formContext ?? props.registry?.formContext ?? {};

  // Provide safe defaults for all required context properties
  const defaultContext: FormContext = {
    liteLlmModels: [],
    litellmModelsLoading: false,
    openExpandedTextarea: () => {},
    openAiSuggestion: () => {},
    aiSuggestionEnabled: false,
    githubAppEnabled: false,
    formData: {},
  };

  if (ctx && typeof ctx === 'object') {
    return { ...defaultContext, ...(ctx as Partial<FormContext>) };
  }

  return defaultContext;
};

const buildUiSchema = (schema: RJSFSchema): UiSchemaShape => {
  const props = (schema as { properties?: unknown })?.properties;
  if (!props || typeof props !== 'object') {
    return {};
  }

  const ui: UiSchemaShape = {};

  const getAdditionalProperties = (prop: SchemaProperty): unknown => {
    const direct = (prop as { additionalProperties?: unknown })
      .additionalProperties;
    if (direct !== undefined) {
      return direct;
    }

    if (Array.isArray(prop.allOf) && prop.allOf.length === 1) {
      return (prop.allOf[0] as { additionalProperties?: unknown } | undefined)
        ?.additionalProperties;
    }

    return undefined;
  };

  for (const [key, propUnknown] of Object.entries(
    props as Record<string, unknown>,
  )) {
    const prop = propUnknown as SchemaProperty;

    const fieldUi: UiSchemaShape = {};

    const uiLabel =
      typeof prop['x-ui:label'] === 'string'
        ? String(prop['x-ui:label'])
        : undefined;
    if (uiLabel) {
      fieldUi['ui:title'] = uiLabel;
    }

    if (prop['x-ui:textarea'] === true) {
      fieldUi['ui:widget'] = 'textareaWithExpand';
    }

    if (prop['x-ui:litellm-models-list-select'] === true) {
      fieldUi['ui:widget'] = 'litellmModelsSelect';
    }

    if (
      prop['x-ui:ai-suggestions'] === true &&
      prop['x-ui:textarea'] !== true &&
      prop['x-ui:litellm-models-list-select'] !== true
    ) {
      fieldUi['ui:widget'] = 'textWithAi';
    }

    const typeName = getSchemaTypeName(prop);

    if (typeName === 'array' && prop['x-ui:secret-multi-select'] !== true) {
      fieldUi['ui:field'] = 'arrayAsTextarea';
    }

    const isObjectWithAdditionalProps =
      typeName === 'object' && Boolean(getAdditionalProperties(prop));
    if (isObjectWithAdditionalProps) {
      fieldUi['ui:field'] = 'keyValueObject';
    }

    if (prop['x-ui:github-repos-select'] === true) {
      fieldUi['ui:field'] = 'githubRepoSelect';
    }

    if (prop['x-ui:secret-select'] === true) {
      fieldUi['ui:field'] = 'secretSelect';
    }

    if (prop['x-ui:secret-multi-select'] === true) {
      fieldUi['ui:field'] = 'secretMultiSelect';
    }

    if (prop['x-ui:readonly'] === true) {
      fieldUi['ui:readonly'] = true;
    }

    ui[key] = fieldUi;
  }

  return ui;
};

// --- Hoisted RJSF templates ---

const RjsfObjectFieldTemplate = (
  props: ObjectFieldTemplateProps<FormData, RJSFSchema, FormContext>,
) => {
  // RJSF AntD default wraps objects in a panel/card which doesn't match our sidebar.
  return (
    <div>
      {props.properties.map((p) => (
        <div key={p.name}>{p.content}</div>
      ))}
    </div>
  );
};

const RjsfFieldTemplate = (
  props: FieldTemplateProps<FormData, RJSFSchema, FormContext>,
) => {
  const schemaType = (props.schema as { type?: unknown } | undefined)?.type;
  const isBooleanField = schemaType === 'boolean';
  // RJSF often sets displayLabel=false for boolean widgets (checkbox),
  // but we render a Switch and still want the label visible.
  const showLabel =
    Boolean(props.label) && (props.displayLabel !== false || isBooleanField);
  const descriptionText =
    typeof props.rawDescription === 'string' ? props.rawDescription : '';

  return (
    <div style={{ marginBottom: 15 }}>
      {showLabel && (
        <div style={{ display: 'flex', alignItems: 'center', gap: 5 }}>
          <span style={{ fontSize: 15 }}>{props.label}</span>
          {props.required && (
            <span
              style={{
                color: 'gray',
                fontSize: 11,
                position: 'relative',
                top: '1px',
              }}>
              (required)
            </span>
          )}
        </div>
      )}

      <div style={{ marginTop: showLabel ? 4 : 0 }}>{props.children}</div>

      {descriptionText && (
        <span
          className="text-muted-foreground"
          style={{
            display: 'block',
            marginTop: 6,
            fontSize: 14,
            lineHeight: 1.25,
          }}>
          {descriptionText}
        </span>
      )}

      {props.errors}
    </div>
  );
};

const RjsfBaseInputTemplate = (
  props: BaseInputTemplateProps<FormData, RJSFSchema, FormContext>,
) => {
  const inputType = typeof props.type === 'string' ? props.type : 'text';
  const inputValue =
    typeof props.value === 'string' || typeof props.value === 'number'
      ? props.value
      : '';
  return (
    <Input
      type={inputType}
      value={inputValue}
      onChange={(e) => props.onChange(e.target.value)}
      onBlur={() => props.onBlur(props.id, props.value)}
      onFocus={() => props.onFocus(props.id, props.value)}
      disabled={props.disabled || props.readonly}
      placeholder={props.placeholder}
      className="w-full"
    />
  );
};

// --- Searchable Combobox Select (shared by RjsfSelectWidget and RjsfLitellmModelsSelectWidget) ---

const SearchableSelect = ({
  value,
  onChange,
  options,
  placeholder,
  disabled,
  allowClear,
  emptyMessage,
}: {
  value: string | undefined;
  onChange: (value: string | undefined) => void;
  options: { label: string; value: string }[];
  placeholder?: string;
  disabled?: boolean;
  allowClear?: boolean;
  emptyMessage?: string;
}) => {
  const [open, setOpen] = useState(false);
  const selectedOption = options.find((opt) => opt.value === value);

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <div className="relative w-full">
        <PopoverTrigger asChild>
          <Button
            variant="outline"
            role="combobox"
            aria-expanded={open}
            disabled={disabled}
            className="w-full justify-between font-normal"
            style={{ minHeight: 36 }}>
            <span
              className={selectedOption ? '' : 'text-muted-foreground'}
              style={{
                overflow: 'hidden',
                textOverflow: 'ellipsis',
                whiteSpace: 'nowrap',
              }}>
              {selectedOption?.label ?? placeholder ?? 'Select...'}
            </span>
            <ChevronsUpDown className="ml-2 size-4 shrink-0 opacity-50" />
          </Button>
        </PopoverTrigger>
        {allowClear && value && !disabled && (
          <button
            type="button"
            onClick={(e) => {
              e.stopPropagation();
              onChange(undefined);
            }}
            className="absolute right-8 top-1/2 -translate-y-1/2 rounded-sm p-0.5 opacity-50 hover:opacity-100"
            aria-label="Clear selection">
            <X className="size-3" />
          </button>
        )}
      </div>
      <PopoverContent
        className="p-0"
        style={{ width: 'var(--radix-popover-trigger-width)' }}>
        <Command>
          <CommandInput placeholder="Search..." />
          <CommandList>
            <CommandEmpty>{emptyMessage ?? 'No results found.'}</CommandEmpty>
            <CommandGroup>
              {options.map((opt) => (
                <CommandItem
                  key={opt.value}
                  value={opt.label}
                  onSelect={() => {
                    onChange(opt.value === value ? undefined : opt.value);
                    setOpen(false);
                  }}>
                  <Check
                    className={`mr-2 size-4 ${opt.value === value ? 'opacity-100' : 'opacity-0'}`}
                  />
                  {opt.label}
                </CommandItem>
              ))}
            </CommandGroup>
          </CommandList>
        </Command>
      </PopoverContent>
    </Popover>
  );
};

// --- Hoisted RJSF widgets ---

const RjsfSelectWidget = (
  props: WidgetProps<string, RJSFSchema, FormContext>,
) => {
  const enumOptions = (
    (
      props.options as {
        enumOptions?: { label: string; value: unknown }[];
      }
    ).enumOptions ?? []
  ).map((opt) => ({
    label: opt.label,
    value: opt.value as string,
  }));

  const placeholder =
    props.placeholder ??
    (props.label ? `Select ${String(props.label).toLowerCase()}` : 'Select');

  return (
    <SearchableSelect
      value={typeof props.value === 'string' ? props.value : undefined}
      onChange={(v) => props.onChange(v)}
      options={enumOptions}
      disabled={props.disabled || props.readonly}
      placeholder={placeholder}
      allowClear={!props.required}
    />
  );
};

const RjsfNumberWidget = (
  props: WidgetProps<number, RJSFSchema, FormContext>,
) => {
  const schema = props.schema as {
    minimum?: number;
    maximum?: number;
    multipleOf?: number;
  };
  const rawValue: unknown = props.value;
  const value =
    typeof rawValue === 'number' && Number.isFinite(rawValue)
      ? rawValue
      : undefined;

  return (
    <div onWheelCapture={handleNumberWheel}>
      <Input
        type="number"
        value={value ?? ''}
        onChange={(e) => {
          const next =
            e.target.value === '' ? undefined : Number(e.target.value);
          props.onChange(
            typeof next === 'number' && Number.isFinite(next)
              ? next
              : undefined,
          );
        }}
        min={schema.minimum}
        max={schema.maximum}
        step={schema.multipleOf}
        disabled={props.disabled || props.readonly}
        placeholder={props.placeholder}
        className="w-full"
      />
    </div>
  );
};

const RjsfUpDownWidget = (
  props: WidgetProps<number, RJSFSchema, FormContext>,
) => (
  <div onWheelCapture={handleNumberWheel}>
    <Input
      type="number"
      value={
        typeof props.value === 'number' && Number.isFinite(props.value)
          ? props.value
          : ''
      }
      onChange={(e) => {
        const next = e.target.value === '' ? undefined : Number(e.target.value);
        props.onChange(
          typeof next === 'number' && Number.isFinite(next) ? next : undefined,
        );
      }}
      min={(props.schema as { minimum?: number }).minimum}
      max={(props.schema as { maximum?: number }).maximum}
      step={(props.schema as { multipleOf?: number }).multipleOf}
      disabled={props.disabled || props.readonly}
      placeholder={props.placeholder}
      className="w-full"
    />
  </div>
);

const RjsfCheckboxWidget = (
  props: WidgetProps<boolean, RJSFSchema, FormContext>,
) => (
  <Switch
    checked={Boolean(props.value)}
    onCheckedChange={(checked) => props.onChange(checked)}
    disabled={props.disabled || props.readonly}
  />
);

const RjsfTextWithAiWidget = (
  props: WidgetProps<string, RJSFSchema, FormContext>,
) => {
  const ctx = getFormContext(props);
  const schemaForField = props.schema as unknown as SchemaProperty;
  const hasAiSuggestions = schemaForField?.['x-ui:ai-suggestions'] === true;

  return (
    <div style={{ display: 'flex', flexDirection: 'column' }}>
      <Input
        value={typeof props.value === 'string' ? props.value : ''}
        onChange={(e) => props.onChange(e.target.value)}
        disabled={props.disabled || props.readonly}
        placeholder={props.placeholder}
      />
      {hasAiSuggestions && ctx.aiSuggestionEnabled === true && (
        <Button
          variant="link"
          size="sm"
          className="h-auto p-0 text-xs"
          onClick={() =>
            ctx.openAiSuggestion?.(
              props.name,
              props.label ?? props.name,
              props.value,
            )
          }>
          Improve with AI
        </Button>
      )}
    </div>
  );
};

const RjsfTextareaWithExpandWidget = (
  props: WidgetProps<string, RJSFSchema, FormContext>,
) => {
  const ctx = getFormContext(props);
  const schemaForField = props.schema as unknown as SchemaProperty;
  const hasAiSuggestions = schemaForField?.['x-ui:ai-suggestions'] === true;

  return (
    <div style={{ position: 'relative' }}>
      <Textarea
        value={typeof props.value === 'string' ? props.value : ''}
        onChange={(e) => props.onChange(e.target.value)}
        rows={5}
        style={{
          paddingRight: '32px',
          resize: 'none',
          maxHeight: 200,
          overflowY: 'auto',
        }}
        disabled={props.disabled || props.readonly}
        placeholder={props.placeholder}
      />
      <Button
        variant="ghost"
        size="icon"
        className="absolute right-1 top-1 size-7"
        onClick={() =>
          ctx.openExpandedTextarea?.(
            props.name,
            typeof props.value === 'string' ? props.value : '',
          )
        }
        disabled={props.disabled}>
        <Maximize2 className="size-3.5" />
      </Button>
      {hasAiSuggestions && ctx.aiSuggestionEnabled === true && (
        <Button
          variant="link"
          size="sm"
          className="h-auto p-0 text-xs"
          onClick={() =>
            ctx.openAiSuggestion?.(
              props.name,
              props.label ?? props.name,
              props.value,
            )
          }>
          Improve with AI
        </Button>
      )}
    </div>
  );
};

const RjsfLitellmModelsSelectWidget = (
  props: WidgetProps<string, RJSFSchema, FormContext>,
) => {
  const ctx = getFormContext(props);
  const options = (ctx.liteLlmModels ?? []).map((model: LiteLlmModelDto) => ({
    label: model.ownedBy ? `${model.id} (${model.ownedBy})` : model.id,
    value: model.id,
  }));
  return (
    <SearchableSelect
      value={typeof props.value === 'string' ? props.value : undefined}
      onChange={(v) => props.onChange(v)}
      options={options}
      disabled={props.disabled || props.readonly}
      placeholder={props.placeholder}
      allowClear={!props.required}
      emptyMessage={
        ctx.litellmModelsLoading === true
          ? 'Loading models...'
          : 'No models available'
      }
    />
  );
};

const RjsfTextWidget = (
  props: WidgetProps<string, RJSFSchema, FormContext>,
) => (
  <Input
    value={
      typeof props.value === 'string'
        ? props.value
        : typeof props.value === 'number'
          ? String(props.value)
          : ''
    }
    onChange={(e) => props.onChange(e.target.value)}
    disabled={props.disabled || props.readonly}
    placeholder={props.placeholder}
    className="w-full"
  />
);

// --- Hoisted RJSF fields ---

const RjsfArrayAsTextareaField = (
  props: FieldProps<FormData, RJSFSchema, FormContext>,
) => {
  const current = Array.isArray(props.formData)
    ? (props.formData as unknown as string[])
    : [];
  return (
    <div>
      <span className="text-sm font-semibold">
        {props.schema.title ?? props.name}
      </span>
      {props.schema.description && (
        <span
          className="text-muted-foreground"
          style={{ display: 'block', fontSize: 12, marginBottom: 8 }}>
          {props.schema.description}
        </span>
      )}
      <ArrayTagInput
        value={current}
        onChange={(lines) => {
          props.onChange(lines as unknown as FormData, props.fieldPathId.path);
        }}
        disabled={props.disabled || props.readonly}
        placeholder="Enter item and press Enter"
      />
    </div>
  );
};

const RjsfKeyValueObjectField = (
  props: FieldProps<FormData, RJSFSchema, FormContext>,
) => {
  const record = useMemo(
    () =>
      props.formData &&
      typeof props.formData === 'object' &&
      !Array.isArray(props.formData)
        ? (props.formData as Record<string, unknown>)
        : {},
    [props.formData],
  );

  // Local state keeps pairs with empty keys visible while the user is typing.
  // We seed from formData on mount and re-sync when formData changes externally.
  const [localPairs, setLocalPairs] = useState<KeyValuePair[]>(() =>
    Object.entries(record).map(([k, v]) => ({
      key: k,
      value: v === undefined || v === null ? '' : String(v),
    })),
  );

  // Sync from formData when it changes externally (e.g. undo, reset).
  // Only overwrite if the serialised record actually differs from what
  // localPairs would produce, so we don't clobber in-progress edits.
  const prevRecordRef = React.useRef(record);
  React.useEffect(() => {
    if (prevRecordRef.current === record) {
      return;
    }
    prevRecordRef.current = record;

    const fromLocal: Record<string, string> = {};
    for (const p of localPairs) {
      const k = p.key.trim();
      if (k) {
        fromLocal[k] = p.value;
      }
    }
    if (JSON.stringify(fromLocal) !== JSON.stringify(record)) {
      // eslint-disable-next-line react-hooks/set-state-in-effect -- reconcile local pairs with external record
      setLocalPairs(
        Object.entries(record).map(([k, v]) => ({
          key: k,
          value: v === undefined || v === null ? '' : String(v),
        })),
      );
    }
  }, [record, localPairs]);

  const handleChange = (nextPairs: KeyValuePair[]) => {
    setLocalPairs(nextPairs);
    const next: Record<string, string> = {};
    for (const pair of nextPairs) {
      const k = pair.key.trim();
      if (!k) {
        continue;
      }
      next[k] = pair.value;
    }
    props.onChange(next as unknown as FormData, props.fieldPathId.path);
  };

  return (
    <div>
      <span className="text-sm font-semibold">
        {props.schema.title ?? props.name}
      </span>
      {props.schema.description && (
        <span
          className="text-muted-foreground"
          style={{ display: 'block', fontSize: 12 }}>
          {props.schema.description}
        </span>
      )}
      <KeyValueInput value={localPairs} onChange={handleChange} />
    </div>
  );
};

const RjsfGitHubRepoSelectField = (
  props: FieldProps<FormData, RJSFSchema, FormContext>,
) => {
  const [repos, setRepos] = useState<GitRepositoryDto[]>([]);
  const [loading, setLoading] = useState(true);
  const [open, setOpen] = useState(false);

  useEffect(() => {
    let cancelled = false;
    const fetchRepos = async () => {
      try {
        const response = await gitRepositoriesApi.getRepositories();
        if (!cancelled) {
          setRepos(response.data);
        }
      } catch (error) {
        console.warn('Failed to fetch git repositories:', error);
      } finally {
        if (!cancelled) {
          setLoading(false);
        }
      }
    };
    fetchRepos();
    return () => {
      cancelled = true;
    };
  }, []);

  const selected = useMemo(
    () =>
      Array.isArray(props.formData)
        ? (props.formData as unknown as string[])
        : [],
    [props.formData],
  );

  const options = useMemo(
    () =>
      repos.map((repo) => ({
        label: `${repo.owner}/${repo.repo}`,
        value: repo.id,
      })),
    [repos],
  );

  const handleToggle = useCallback(
    (repoId: string) => {
      const next = selected.includes(repoId)
        ? selected.filter((id) => id !== repoId)
        : [...selected, repoId];
      props.onChange(next as unknown as FormData, props.fieldPathId.path);
    },
    [selected, props],
  );

  const selectedLabels = useMemo(
    () =>
      selected
        .map((id) => options.find((opt) => opt.value === id)?.label)
        .filter(Boolean),
    [selected, options],
  );

  return (
    <div>
      <span className="text-sm font-semibold">
        {props.schema.title ?? props.name}
      </span>
      {props.schema.description && (
        <span
          className="text-muted-foreground"
          style={{ display: 'block', fontSize: 12, marginBottom: 8 }}>
          {props.schema.description}
        </span>
      )}
      <Popover open={open} onOpenChange={setOpen}>
        <PopoverTrigger asChild>
          <Button
            variant="outline"
            role="combobox"
            aria-expanded={open}
            disabled={props.disabled || props.readonly}
            className="w-full justify-between font-normal"
            style={{ minHeight: 36 }}>
            <span
              className={
                selectedLabels.length > 0 ? '' : 'text-muted-foreground'
              }
              style={{
                overflow: 'hidden',
                textOverflow: 'ellipsis',
                whiteSpace: 'nowrap',
              }}>
              {selectedLabels.length > 0
                ? `${String(selectedLabels.length)} repo${selectedLabels.length > 1 ? 's' : ''} selected`
                : 'Select repositories...'}
            </span>
            <ChevronsUpDown className="ml-2 size-4 shrink-0 opacity-50" />
          </Button>
        </PopoverTrigger>
        <PopoverContent
          className="p-0"
          style={{ width: 'var(--radix-popover-trigger-width)' }}>
          <Command>
            <CommandInput placeholder="Search repositories..." />
            <CommandList>
              <CommandEmpty>
                {loading ? 'Loading repositories...' : 'No repositories found.'}
              </CommandEmpty>
              <CommandGroup>
                {options.map((opt) => (
                  <CommandItem
                    key={opt.value}
                    value={opt.label}
                    onSelect={() => handleToggle(opt.value)}>
                    <Check
                      className={`mr-2 size-4 ${selected.includes(opt.value) ? 'opacity-100' : 'opacity-0'}`}
                    />
                    {opt.label}
                  </CommandItem>
                ))}
              </CommandGroup>
            </CommandList>
          </Command>
        </PopoverContent>
      </Popover>
      {selectedLabels.length > 0 && (
        <div className="mt-1.5 flex flex-wrap gap-1">
          {selectedLabels.map((label) => (
            <Badge key={label} variant="secondary">
              {label}
            </Badge>
          ))}
        </div>
      )}
    </div>
  );
};

const RjsfSecretSelectField = (
  props: FieldProps<FormData, RJSFSchema, FormContext>,
) => {
  const [secrets, setSecrets] = useState<SecretResponseDto[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;
    const fetchSecrets = async () => {
      try {
        const response = await secretsApi.list();
        if (!cancelled) {
          setSecrets(response.data);
        }
      } catch (error) {
        console.warn('Failed to fetch secrets:', error);
      } finally {
        if (!cancelled) {
          setLoading(false);
        }
      }
    };
    fetchSecrets();
    return () => {
      cancelled = true;
    };
  }, []);

  const options = useMemo(
    () => secrets.map((secret) => ({ label: secret.name, value: secret.name })),
    [secrets],
  );

  const currentValue =
    typeof props.formData === 'string' ? props.formData : undefined;

  return (
    <div>
      <span className="text-sm font-semibold">
        {props.schema.title ?? props.name}
      </span>
      {props.schema.description && (
        <span
          className="text-muted-foreground"
          style={{ display: 'block', fontSize: 12, marginBottom: 8 }}>
          {props.schema.description}
        </span>
      )}
      <SearchableSelect
        value={currentValue}
        onChange={(v) =>
          props.onChange(v as unknown as FormData, props.fieldPathId.path)
        }
        options={options}
        disabled={props.disabled || props.readonly}
        placeholder="Select secret..."
        allowClear={!props.required}
        emptyMessage={loading ? 'Loading secrets...' : 'No secrets configured'}
      />
      <a
        href="/settings/secrets"
        className="mt-1 inline-block text-xs text-muted-foreground underline-offset-2 hover:underline"
        target="_blank"
        rel="noopener noreferrer">
        Manage secrets
      </a>
    </div>
  );
};

const RjsfSecretMultiSelectField = (
  props: FieldProps<FormData, RJSFSchema, FormContext>,
) => {
  const [secrets, setSecrets] = useState<SecretResponseDto[]>([]);
  const [loading, setLoading] = useState(true);
  const [open, setOpen] = useState(false);

  useEffect(() => {
    let cancelled = false;
    const fetchSecrets = async () => {
      try {
        const response = await secretsApi.list();
        if (!cancelled) {
          setSecrets(response.data);
        }
      } catch (error) {
        console.warn('Failed to fetch secrets:', error);
      } finally {
        if (!cancelled) {
          setLoading(false);
        }
      }
    };
    fetchSecrets();
    return () => {
      cancelled = true;
    };
  }, []);

  const selected = useMemo(
    () =>
      Array.isArray(props.formData)
        ? (props.formData as unknown as string[])
        : [],
    [props.formData],
  );

  const options = useMemo(
    () => secrets.map((secret) => ({ label: secret.name, value: secret.name })),
    [secrets],
  );

  const handleToggle = useCallback(
    (secretName: string) => {
      const next = selected.includes(secretName)
        ? selected.filter((name) => name !== secretName)
        : [...selected, secretName];
      props.onChange(next as unknown as FormData, props.fieldPathId.path);
    },
    [selected, props],
  );

  return (
    <div>
      <span className="text-sm font-semibold">
        {props.schema.title ?? props.name}
      </span>
      {props.schema.description && (
        <span
          className="text-muted-foreground"
          style={{ display: 'block', fontSize: 12, marginBottom: 8 }}>
          {props.schema.description}
        </span>
      )}
      <Popover open={open} onOpenChange={setOpen}>
        <PopoverTrigger asChild>
          <Button
            variant="outline"
            role="combobox"
            aria-expanded={open}
            disabled={props.disabled || props.readonly}
            className="w-full justify-between font-normal"
            style={{ minHeight: 36 }}>
            <span
              className={selected.length > 0 ? '' : 'text-muted-foreground'}
              style={{
                overflow: 'hidden',
                textOverflow: 'ellipsis',
                whiteSpace: 'nowrap',
              }}>
              {selected.length > 0
                ? `${String(selected.length)} secret${selected.length > 1 ? 's' : ''} selected`
                : 'Select secrets...'}
            </span>
            <ChevronsUpDown className="ml-2 size-4 shrink-0 opacity-50" />
          </Button>
        </PopoverTrigger>
        <PopoverContent
          className="p-0"
          style={{ width: 'var(--radix-popover-trigger-width)' }}>
          <Command>
            <CommandInput placeholder="Search secrets..." />
            <CommandList>
              <CommandEmpty>
                {loading ? 'Loading secrets...' : 'No secrets configured'}
              </CommandEmpty>
              <CommandGroup>
                {options.map((opt) => (
                  <CommandItem
                    key={opt.value}
                    value={opt.label}
                    onSelect={() => handleToggle(opt.value)}>
                    <Check
                      className={`mr-2 size-4 ${selected.includes(opt.value) ? 'opacity-100' : 'opacity-0'}`}
                    />
                    {opt.label}
                  </CommandItem>
                ))}
              </CommandGroup>
            </CommandList>
          </Command>
        </PopoverContent>
      </Popover>
      {selected.length > 0 && (
        <div className="mt-1.5 flex flex-wrap gap-1">
          {selected.map((name) => (
            <Badge key={name} variant="secondary">
              {name}
            </Badge>
          ))}
        </div>
      )}
      <a
        href="/settings/secrets"
        className="mt-1 inline-block text-xs text-muted-foreground underline-offset-2 hover:underline"
        target="_blank"
        rel="noopener noreferrer">
        Manage secrets
      </a>
    </div>
  );
};

// --- Stable RJSF config objects (module-level, never re-created) ---

// RJSF @rjsf/core Form requires all config objects to match its inferred T
// generic (FormData). Our widgets use narrower value types (string, number,
// boolean) which are correct at runtime but conflict with the strict generic
// constraint. We cast through unknown to satisfy TypeScript while preserving
// full type safety inside each widget/field implementation.
type RjsfTemplates = Partial<TemplatesType<FormData, RJSFSchema, FormContext>>;
type RjsfWidgets = RegistryWidgetsType<FormData, RJSFSchema, FormContext>;
type RjsfFields = RegistryFieldsType<FormData, RJSFSchema, FormContext>;

const RJSF_TEMPLATES: RjsfTemplates = {
  BaseInputTemplate: RjsfBaseInputTemplate,
  ObjectFieldTemplate: RjsfObjectFieldTemplate,
  FieldTemplate: RjsfFieldTemplate,
} as unknown as RjsfTemplates;

const RJSF_WIDGETS: RjsfWidgets = {
  TextWidget: RjsfTextWidget,
  SelectWidget: RjsfSelectWidget,
  NumberWidget: RjsfNumberWidget,
  UpDownWidget: RjsfUpDownWidget,
  CheckboxWidget: RjsfCheckboxWidget,
  textWithAi: RjsfTextWithAiWidget,
  textareaWithExpand: RjsfTextareaWithExpandWidget,
  litellmModelsSelect: RjsfLitellmModelsSelectWidget,
} as unknown as RjsfWidgets;

const RJSF_FIELDS: RjsfFields = {
  arrayAsTextarea: RjsfArrayAsTextareaField,
  keyValueObject: RjsfKeyValueObjectField,
  githubRepoSelect: RjsfGitHubRepoSelectField,
  secretSelect: RjsfSecretSelectField,
  secretMultiSelect: RjsfSecretMultiSelectField,
} as unknown as RjsfFields;

// --- Component ---

export interface TemplateConfigFormProps {
  schema: RJSFSchema;
  formData: FormData;
  onChange: (next: FormData) => void;
  liteLlmModels: LiteLlmModelDto[];
  litellmModelsLoading: boolean;
  onOpenExpandedTextarea: (fieldKey: string, value: string) => void;
  onOpenAiSuggestion: (
    fieldKey: string,
    fieldLabel: string,
    value?: unknown,
  ) => void;
  aiSuggestionEnabled: boolean;
  githubAppEnabled?: boolean;
  templateId?: string;
}

export const TemplateConfigForm: React.FC<TemplateConfigFormProps> = ({
  schema,
  formData,
  onChange,
  liteLlmModels,
  litellmModelsLoading,
  onOpenExpandedTextarea,
  onOpenAiSuggestion,
  aiSuggestionEnabled,
  githubAppEnabled = false,
  templateId,
}) => {
  const [copied, setCopied] = useState(false);
  const uiSchema = useMemo(() => buildUiSchema(schema), [schema]);

  const isGitHubIssuesTrigger = templateId === 'github-issues-trigger';
  const webhookUrl = `${API_URL}/api/webhooks/github`;

  const handleCopyWebhookUrl = useCallback(() => {
    navigator.clipboard.writeText(webhookUrl).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }, [webhookUrl]);

  const formContext: FormContext = useMemo(
    () => ({
      liteLlmModels,
      litellmModelsLoading,
      openExpandedTextarea: onOpenExpandedTextarea,
      openAiSuggestion: onOpenAiSuggestion,
      aiSuggestionEnabled,
      githubAppEnabled,
      formData,
    }),
    [
      aiSuggestionEnabled,
      formData,
      githubAppEnabled,
      liteLlmModels,
      litellmModelsLoading,
      onOpenAiSuggestion,
      onOpenExpandedTextarea,
    ],
  );

  const isGitHubNode =
    templateId === 'github-resource' || templateId === 'gh-tool';
  const showGitHubAppWarning = isGitHubNode && !githubAppEnabled;

  return (
    <>
      {isGitHubIssuesTrigger && (
        <div className="mb-4">
          <span className="mb-1 block text-sm font-semibold">Webhook URL</span>
          <div className="flex items-center gap-2">
            <Input value={webhookUrl} readOnly className="flex-1 text-xs" />
            <Button size="sm" variant="outline" onClick={handleCopyWebhookUrl}>
              {copied ? (
                <Check className="size-3.5" />
              ) : (
                <Copy className="size-3.5" />
              )}
            </Button>
          </div>
          <span className="text-muted-foreground mt-1 block text-xs">
            Add this URL to your GitHub App webhook settings. Set the secret to
            match your <code>GITHUB_WEBHOOK_SECRET</code> environment variable
            and subscribe to Issues events.
          </span>
        </div>
      )}
      {showGitHubAppWarning && (
        <Alert variant="destructive" className="mb-3">
          <AlertTriangle className="size-4" />
          <AlertTitle>GitHub App not connected</AlertTitle>
          <AlertDescription>
            GitHub authentication requires a GitHub App. Go to Settings &gt;
            Integrations to install and link the GitHub App.
          </AlertDescription>
        </Alert>
      )}
      <Form
        schema={schema}
        uiSchema={uiSchema}
        formData={formData}
        formContext={formContext}
        validator={validator}
        showErrorList={false}
        noHtml5Validate
        liveValidate={false}
        templates={RJSF_TEMPLATES}
        widgets={RJSF_WIDGETS}
        fields={RJSF_FIELDS}
        onChange={(e) => {
          const next = (e.formData ?? {}) as FormData;
          onChange(next);
        }}>
        {/* No submit button in this UI (changes are propagated live) */}
        <></>
      </Form>
    </>
  );
};
