import { describe, expect, it } from 'vitest';

import type { TemplateDto } from '../autogenerated';
import type { GraphNode } from '../pages/graphs/types';
import { GraphValidationService } from './GraphValidationService';

/**
 * Client-side pre-flight for secret references. The host-only BYO key marker
 * (`x-ui:secret-select-host`) is rendered with the same secret picker as
 * `x-ui:secret-select`, so a reference to a missing/renamed secret must raise
 * the same "not found" warning here — even though the backend resolves that key
 * host-side (never through the generic sandbox secretEnv path).
 */
describe('GraphValidationService.checkSecretReferences', () => {
  const makeNode = (config: Record<string, unknown>): GraphNode =>
    ({
      id: 'node-1',
      data: { label: 'n', template: 'claude-agent', config },
    }) as unknown as GraphNode;

  const makeTemplate = (properties: Record<string, unknown>): TemplateDto =>
    ({
      id: 'claude-agent',
      schema: { properties },
    }) as unknown as TemplateDto;

  it('flags a host-only BYO secret reference (x-ui:secret-select-host) that is not in the available set', () => {
    const errors = GraphValidationService.checkSecretReferences(
      makeNode({ apiKeySecretRef: 'MISSING_KEY' }),
      [makeTemplate({ apiKeySecretRef: { 'x-ui:secret-select-host': true } })],
      ['SOME_OTHER_SECRET'],
    );

    expect(errors).toHaveLength(1);
    expect(errors[0]).toMatchObject({ nodeId: 'node-1', type: 'config' });
    expect(errors[0].message).toContain('MISSING_KEY');
  });

  it('does not flag a host-only BYO secret reference that exists in the available set', () => {
    const errors = GraphValidationService.checkSecretReferences(
      makeNode({ apiKeySecretRef: 'MY_KEY' }),
      [makeTemplate({ apiKeySecretRef: { 'x-ui:secret-select-host': true } })],
      ['MY_KEY'],
    );

    expect(errors).toHaveLength(0);
  });

  it('preserves parity: still flags a generic x-ui:secret-select reference that is missing', () => {
    const errors = GraphValidationService.checkSecretReferences(
      makeNode({ apiKey: 'MISSING' }),
      [makeTemplate({ apiKey: { 'x-ui:secret-select': true } })],
      ['PRESENT'],
    );

    expect(errors).toHaveLength(1);
    expect(errors[0].message).toContain('MISSING');
  });
});
