// @vitest-environment jsdom
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import type { ThreadMessageDtoMessageOneOf1 } from '../autogenerated';
import { webSocketService } from './WebSocketService';
import type { AgentMessageNotification } from './WebSocketTypes';
import { NotificationScope } from './WebSocketTypes';

// Minimal AI message conforming to ThreadMessageDtoMessageOneOf1 (role: 'ai').
// This is the simplest concrete member of the ThreadMessageDtoMessage union.
const makeTestData = (): AgentMessageNotification => {
  const message: ThreadMessageDtoMessageOneOf1 = {
    role: 'ai',
    content: 'hello from test',
  };

  return {
    type: 'agent.message',
    graphId: 'graph-1',
    ownerId: 'owner-1',
    nodeId: 'node-1',
    threadId: 'thread-1',
    internalThreadId: 'internal-thread-1',
    scope: [NotificationScope.Graph],
    data: {
      id: 'msg-1',
      threadId: 'thread-1',
      nodeId: 'node-1',
      externalThreadId: 'ext-thread-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      message,
    },
  };
};

describe('WebSocketService._unsafeInjectEventForHarness', () => {
  beforeEach(() => {
    vi.useFakeTimers();
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  it('delivers events to typed handlers', () => {
    const spy = vi.fn();
    webSocketService.on('agent.message', spy);

    const testData = makeTestData();
    webSocketService._unsafeInjectEventForHarness('agent.message', testData);
    vi.advanceTimersByTime(1);

    expect(spy).toHaveBeenCalledTimes(1);
    expect(spy).toHaveBeenCalledWith(testData);

    webSocketService.off('agent.message', spy);
  });

  it('delivers events to wildcard handlers', () => {
    const spy = vi.fn();
    webSocketService.on('*', spy);

    const testData = makeTestData();
    webSocketService._unsafeInjectEventForHarness('agent.message', testData);
    vi.advanceTimersByTime(1);

    expect(spy).toHaveBeenCalledTimes(1);
    expect(spy).toHaveBeenCalledWith(testData);

    webSocketService.off('*', spy);
  });

  it('works without a socket connection (no-socket path)', () => {
    // webSocketService.connect() is intentionally NOT called here.
    // This proves the Storybook replay harness can inject events without a
    // real socket.io connection.
    const spy = vi.fn();
    webSocketService.on('agent.message', spy);

    const testData = makeTestData();
    webSocketService._unsafeInjectEventForHarness('agent.message', testData);
    vi.advanceTimersByTime(1);

    expect(spy).toHaveBeenCalledTimes(1);
    expect(spy).toHaveBeenCalledWith(testData);

    webSocketService.off('agent.message', spy);
  });
});
