import { describe, expect, it } from 'vitest';

import type { ThreadMessageDto } from '../../../../autogenerated';
import { STREAMING_REASONING_FLAG } from '../../../../utils/threadMessages';
import {
  _accumulatePreparedStatistics,
  prepareReadyMessages,
} from './prepareMessages';
import type { PreparedMessage } from './threadMessagesTypes';

// ── Factory helpers ───────────────────────────────────────────────────────────

/**
 * Minimal valid `ThreadMessageDto`.  Only the fields required by the
 * prepareReadyMessages processing paths are populated; everything else uses
 * safe default values.
 */
const makeMsg = (
  id: string,
  role: string,
  content: string,
  additionalKwargs: Record<string, unknown> = {},
  extra: Partial<
    Pick<
      ThreadMessageDto,
      'createdAt' | 'updatedAt' | 'nodeId' | 'externalThreadId'
    >
  > = {},
): ThreadMessageDto => ({
  id,
  threadId: 'thread-1',
  nodeId: 'node-1',
  externalThreadId: '',
  createdAt: '2024-01-01T00:00:00.000Z',
  updatedAt: '2024-01-01T00:00:00.000Z',
  ...extra,
  message: {
    id,
    role: role as string,
    content,
    additionalKwargs,
  } as ThreadMessageDto['message'],
});

/** AI message that owns a subagents_run_task tool call. */
const makeSubagentCallMsg = (
  id: string,
  toolCallId: string,
): ThreadMessageDto => ({
  id,
  threadId: 'thread-1',
  nodeId: 'node-1',
  externalThreadId: '',
  createdAt: '2024-01-01T00:00:00.000Z',
  updatedAt: '2024-01-01T00:00:00.000Z',
  message: {
    id,
    role: 'ai' as string,
    content: '',
    toolCalls: [{ id: toolCallId, name: 'subagents_run_task' }],
  } as ThreadMessageDto['message'],
});

/** Tool message that is the result of a subagents_run_task call. */
const makeSubagentResultMsg = (
  id: string,
  toolCallId: string,
): ThreadMessageDto => ({
  id,
  threadId: 'thread-1',
  nodeId: 'node-1',
  externalThreadId: '',
  createdAt: '2024-01-01T00:01:00.000Z',
  updatedAt: '2024-01-01T00:01:00.000Z',
  message: {
    id,
    role: 'tool' as string,
    content: '',
    name: 'subagents_run_task',
    toolCallId,
  } as ThreadMessageDto['message'],
});

/** Streaming reasoning message carrying the `__streamingReasoning` flag. */
const makeStreamingReasoning = (
  id: string,
  overrides: {
    toolCallId?: string;
    subagentCommunication?: boolean;
    interAgentCommunication?: boolean;
  } = {},
): ThreadMessageDto => {
  const kwargs: Record<string, unknown> = {
    __reasoningId: id,
    [STREAMING_REASONING_FLAG]: true,
  };
  if (overrides.toolCallId) {
    kwargs.__toolCallId = overrides.toolCallId;
  }
  if (overrides.subagentCommunication) {
    kwargs.__subagentCommunication = true;
  }
  if (overrides.interAgentCommunication) {
    kwargs.__interAgentCommunication = true;
  }
  return makeMsg(id, 'reasoning', 'streaming...', kwargs);
};

/** Chat message from inside a subagent run (carries __subagentCommunication). */
const makeSubagentInnerChat = (
  id: string,
  toolCallId: string,
): ThreadMessageDto =>
  makeMsg(id, 'ai', `inner content ${id}`, {
    __toolCallId: toolCallId,
    __subagentCommunication: true,
  });

/** Default minimal options for prepareReadyMessages. */
const defaultOptions = {
  isNodeRunning: false,
  isThreadStopped: false,
};

/** Walk a PreparedMessage tree and collect all items matching a predicate. */
const collectItems = (
  items: PreparedMessage[],
  predicate: (item: PreparedMessage) => boolean,
): PreparedMessage[] => {
  const result: PreparedMessage[] = [];
  const walk = (list: PreparedMessage[]): void => {
    for (const item of list) {
      if (predicate(item)) {
        result.push(item);
      }
      if (
        (item.type === 'subagent' || item.type === 'communication') &&
        item.innerMessages.length > 0
      ) {
        walk(item.innerMessages);
      }
    }
  };
  walk(items);
  return result;
};

/** Convenience: return the first subagent block in the tree. */
const findSubagentBlock = (
  items: PreparedMessage[],
  toolCallId: string,
): (PreparedMessage & { type: 'subagent' }) | undefined => {
  const matches = collectItems(
    items,
    (item) =>
      item.type === 'subagent' &&
      'toolCallId' in item &&
      item.toolCallId === toolCallId,
  );
  return matches[0] as (PreparedMessage & { type: 'subagent' }) | undefined;
};

/** Return all streaming reasoning items found anywhere in the tree. */
const findStreamingReasoning = (
  items: PreparedMessage[],
  reasoningId: string,
): PreparedMessage[] =>
  collectItems(
    items,
    (item) =>
      item.type === 'reasoning' &&
      'message' in item &&
      item.id === `reasoning-${reasoningId}`,
  );

// ── Communication-block delegation grouping (Claude-path id-space fix) ─────────

/** AI message that owns a single communication_exec tool call. */
const makeCommCallMsg = (
  id: string,
  toolCallId: string,
  agent: string,
  session: string,
  createdAt: string,
): ThreadMessageDto => ({
  id,
  threadId: 'thread-1',
  nodeId: 'manager',
  externalThreadId: '',
  createdAt,
  updatedAt: createdAt,
  message: {
    id,
    role: 'ai' as string,
    content: '',
    toolCalls: [
      {
        id: toolCallId,
        name: 'communication_exec',
        args: { agent, session, message: 'go', purpose: 'delegate' },
      },
    ],
  } as ThreadMessageDto['message'],
});

/** A delegated agent's inner reply, stamped with the parent call id (or, for
 *  the legacy case, a bridge correlation id that does NOT match any call). */
const makeCommInnerMsg = (
  id: string,
  toolCallId: string | undefined,
  content: string,
  createdAt: string,
  externalThreadId = '',
): ThreadMessageDto => {
  const kwargs: Record<string, unknown> = { __interAgentCommunication: true };
  if (toolCallId) {
    kwargs.__toolCallId = toolCallId;
  }
  return makeMsg(id, 'ai', content, kwargs, {
    nodeId: 'engineer',
    externalThreadId,
    createdAt,
    updatedAt: createdAt,
  });
};

/** Tool result that closes a communication_exec call. */
const makeCommResultMsg = (
  id: string,
  toolCallId: string,
  createdAt: string,
): ThreadMessageDto => ({
  id,
  threadId: 'thread-1',
  nodeId: 'manager',
  externalThreadId: '',
  createdAt,
  updatedAt: createdAt,
  message: {
    id,
    role: 'tool' as string,
    content: 'peer answered',
    name: 'communication_exec',
    toolCallId,
  } as ThreadMessageDto['message'],
});

const findCommBlocks = (
  items: PreparedMessage[],
): (PreparedMessage & { type: 'communication' })[] =>
  collectItems(
    items,
    (item) => item.type === 'communication',
  ) as (PreparedMessage & {
    type: 'communication';
  })[];

describe('Communication-block delegation grouping (Claude-path id-space fix)', () => {
  it('renders two distinct same-agent delegations as two separate blocks keyed by the parent tool_use_id', () => {
    // After the backend fix each delegation's inner messages carry the SDK
    // tool_use_id of their parent communication_exec call, so the primary
    // grouping key hits and the two delegations no longer fold into one block.
    const msgs = [
      makeCommCallMsg(
        'p-a',
        'toolu_A',
        'Engineer',
        'probe',
        '2024-01-01T00:00:00.000Z',
      ),
      makeCommInnerMsg(
        'inner-a',
        'toolu_A',
        'probe result',
        '2024-01-01T00:00:05.000Z',
      ),
      makeCommResultMsg('r-a', 'toolu_A', '2024-01-01T00:00:06.000Z'),
      makeCommCallMsg(
        'p-b',
        'toolu_B',
        'Engineer',
        'plan',
        '2024-01-01T00:01:00.000Z',
      ),
      makeCommInnerMsg(
        'inner-b',
        'toolu_B',
        'plan result',
        '2024-01-01T00:01:05.000Z',
      ),
      makeCommResultMsg('r-b', 'toolu_B', '2024-01-01T00:01:06.000Z'),
    ];

    const prepared = prepareReadyMessages(msgs, defaultOptions);
    const blocks = findCommBlocks(prepared);

    expect(blocks).toHaveLength(2);
    const byId = new Map(blocks.map((b) => [b.toolCallId, b]));
    expect(byId.has('toolu_A')).toBe(true);
    expect(byId.has('toolu_B')).toBe(true);

    // The session label (badge) is preserved per delegation.
    expect(byId.get('toolu_A')!.sessionLabel).toBe('probe');
    expect(byId.get('toolu_B')!.sessionLabel).toBe('plan');

    // Each block contains ONLY its own delegation's inner content — the second
    // delegation must NOT be folded into the first, already-completed block.
    const blockA = JSON.stringify(byId.get('toolu_A')!.innerMessages);
    const blockB = JSON.stringify(byId.get('toolu_B')!.innerMessages);
    expect(blockA).toContain('probe result');
    expect(blockA).not.toContain('plan result');
    expect(blockB).toContain('plan result');
    expect(blockB).not.toContain('probe result');
  });

  it('still groups a legacy inner message via the single-call fallback when no __toolCallId or agent-name matches', () => {
    // Pre-fix / SimpleAgent rows: the inner message carries a bridge correlation
    // id that is NOT a known communication_exec call id, AND no externalThreadId
    // agent-name match — so only the `communicationToolCallIds.size === 1`
    // fallback can route it. This pins that the fallback is not removed.
    const msgs = [
      makeCommCallMsg(
        'p-x',
        'toolu_X',
        'Engineer',
        'solo',
        '2024-01-01T00:00:00.000Z',
      ),
      makeCommInnerMsg(
        'inner-x',
        'bridge-tool-1', // not in communicationToolCallIds
        'legacy result',
        '2024-01-01T00:00:05.000Z',
        '', // no externalThreadId agent-name match either
      ),
      makeCommResultMsg('r-x', 'toolu_X', '2024-01-01T00:00:06.000Z'),
    ];

    const prepared = prepareReadyMessages(msgs, defaultOptions);
    const blocks = findCommBlocks(prepared);

    expect(blocks).toHaveLength(1);
    expect(blocks[0]!.toolCallId).toBe('toolu_X');
    expect(JSON.stringify(blocks[0]!.innerMessages)).toContain('legacy result');
  });
});

// ── Streaming-order fold reproduction (Claude-bridge parent-at-end timing) ─────
//
// The Claude bridge persists each communication_exec parent message at the END
// of its delegation (usage stamped at turn end, insert-only), so a delegation's
// inner messages carry a createdAt BEFORE their own parent call. With bridge
// correlation ids (pre-fix) the inner messages miss the primary grouping key and
// fall to resolveCommByTimestamp, which assigns them to the latest call created
// at-or-before the message — i.e. the PREVIOUS delegation's call — folding
// delegation 2 into delegation 1's block. (This is the user-reported bug; the
// earlier grouping tests above used createdAt='' and an empty externalThreadId,
// so they did NOT reproduce the fold.) The SDK tool_use_id fix routes the inner
// messages via the primary path, keeping each delegation separate.
describe('Communication-block streaming-order fold (Claude-bridge parent-at-end)', () => {
  const build = (d1Id: string, d2Id: string): ThreadMessageDto[] => [
    makeCommInnerMsg(
      'i1',
      d1Id,
      'probe result',
      '2024-01-01T00:00:05.000Z',
      'b__Engineer__probe',
    ),
    makeCommCallMsg(
      'p1',
      'toolu_A',
      'Engineer',
      'probe',
      '2024-01-01T00:00:10.000Z',
    ),
    makeCommResultMsg('r1', 'toolu_A', '2024-01-01T00:00:11.000Z'),
    makeCommInnerMsg(
      'i2',
      d2Id,
      'plan result',
      '2024-01-01T00:00:15.000Z',
      'b__Engineer__plan',
    ),
    makeCommCallMsg(
      'p2',
      'toolu_B',
      'Engineer',
      'plan',
      '2024-01-01T00:00:20.000Z',
    ),
    makeCommResultMsg('r2', 'toolu_B', '2024-01-01T00:00:21.000Z'),
  ];

  const planLocation = (msgs: ThreadMessageDto[]) => {
    const blocks = findCommBlocks(prepareReadyMessages(msgs, defaultOptions));
    const byId = new Map(
      blocks.map((b) => [b.toolCallId, JSON.stringify(b.innerMessages)]),
    );
    return {
      inProbeBlock: Boolean(byId.get('toolu_A')?.includes('plan result')),
      inPlanBlock: Boolean(byId.get('toolu_B')?.includes('plan result')),
    };
  };

  it('reproduces the bug: bridge correlation ids fold the second delegation into the first block', () => {
    expect(planLocation(build('bridge-tool-1', 'bridge-tool-2'))).toEqual({
      inProbeBlock: true,
      inPlanBlock: false,
    });
  });

  it('the SDK tool_use_id fix keeps each delegation in its own block', () => {
    expect(planLocation(build('toolu_A', 'toolu_B'))).toEqual({
      inProbeBlock: false,
      inPlanBlock: true,
    });
  });
});

// ── Scenario (a): orphan with __toolCallId routes into executed block ─────────

describe('adoptOrphanStreamingReasoning — keyed by __toolCallId', () => {
  it('(a) streaming reasoning with __toolCallId routes into the matching subagent block when its status is executed', () => {
    // Subagent inner messages arrive WITHOUT the parent AI message (AI message
    // absent — e.g. pagination).  prepareReadyMessages creates a synthetic
    // subagent block (status: 'executed') from the orphaned inner messages.
    // The streaming reasoning carries the same toolCallId but no __subagentCommunication
    // flag, so it is NOT consumed as inner.  adoptOrphanStreamingReasoning must
    // route it into the synthetic block via findBlockByToolCallId, which accepts
    // any status (fixing "reasoning disappears after block completes").
    const msgs: ThreadMessageDto[] = [
      // Orphan inner chat — parent AI msg for 'tc-exec' is absent
      makeSubagentInnerChat('inner-chat-1', 'tc-exec'),
      // Streaming reasoning carrying the same toolCallId but no comm flags
      makeStreamingReasoning('reasoning:r1', { toolCallId: 'tc-exec' }),
    ];

    const prepared = prepareReadyMessages(msgs, defaultOptions);

    // The synthetic subagent block must exist.
    const block = findSubagentBlock(prepared, 'tc-exec');
    expect(block).toBeDefined();
    expect(block!.status).toBe('executed');

    // The streaming reasoning must be INSIDE the block, not at the root.
    const rootReasoning = prepared.filter(
      (item) =>
        item.type === 'reasoning' && item.id === 'reasoning-reasoning:r1',
    );
    expect(rootReasoning).toHaveLength(0);

    const innerReasoning = block!.innerMessages.filter(
      (item) => item.type === 'reasoning',
    );
    expect(innerReasoning).toHaveLength(1);
  });

  it('(b) two concurrent subagent blocks each receive only their own streaming reasoning', () => {
    const msgs: ThreadMessageDto[] = [
      // Orphan inner messages for subagent A and B (no parent AI msg for either)
      makeSubagentInnerChat('inner-a', 'tc-A'),
      makeSubagentInnerChat('inner-b', 'tc-B'),
      // Streaming reasoning for A — must end up only inside block A
      makeStreamingReasoning('reasoning:a', { toolCallId: 'tc-A' }),
      // Streaming reasoning for B — must end up only inside block B
      makeStreamingReasoning('reasoning:b', { toolCallId: 'tc-B' }),
    ];

    const prepared = prepareReadyMessages(msgs, defaultOptions);

    const blockA = findSubagentBlock(prepared, 'tc-A');
    const blockB = findSubagentBlock(prepared, 'tc-B');

    expect(blockA).toBeDefined();
    expect(blockB).toBeDefined();

    // Block A gets reasoning:a, not reasoning:b
    const reasoningInA = blockA!.innerMessages.filter(
      (item) => item.type === 'reasoning',
    );
    expect(reasoningInA).toHaveLength(1);
    expect(reasoningInA[0].id).toBe('reasoning-reasoning:a');

    // Block B gets reasoning:b, not reasoning:a
    const reasoningInB = blockB!.innerMessages.filter(
      (item) => item.type === 'reasoning',
    );
    expect(reasoningInB).toHaveLength(1);
    expect(reasoningInB[0].id).toBe('reasoning-reasoning:b');

    // Neither reasoning appears at the root level
    const rootReasoning = prepared.filter((item) => item.type === 'reasoning');
    expect(rootReasoning).toHaveLength(0);
  });
});

// ── Scenario (c): orphan without __toolCallId falls back to deepest active ────

describe('adoptOrphanStreamingReasoning — unkeyed falls back to findDeepestActiveBlock', () => {
  it('(c) orphan without __toolCallId is adopted by the deepest active (calling) block', () => {
    // A subagents_run_task call is in progress (no result yet, isNodeRunning=true).
    // The streaming reasoning has no __toolCallId — it should be routed via the
    // existing findDeepestActiveBlock heuristic (existing behavior preserved).
    const msgs: ThreadMessageDto[] = [
      makeSubagentCallMsg('ai-calling', 'tc-calling'),
      // No tool result → block status = 'calling'
      // Streaming reasoning with no toolCallId
      makeStreamingReasoning('reasoning:unkeyed'),
    ];

    const prepared = prepareReadyMessages(msgs, {
      ...defaultOptions,
      isNodeRunning: true,
    });

    const block = findSubagentBlock(prepared, 'tc-calling');
    expect(block).toBeDefined();
    expect(block!.status).toBe('calling');

    // Reasoning must be inside the calling block, not at the root.
    const rootReasoning = prepared.filter((item) => item.type === 'reasoning');
    expect(rootReasoning).toHaveLength(0);

    const innerReasoning = block!.innerMessages.filter(
      (item) => item.type === 'reasoning',
    );
    expect(innerReasoning).toHaveLength(1);
  });
});

// ── Scenario (d): top-level reasoning with no active block stays at root ──────

describe('adoptOrphanStreamingReasoning — no block present (G5)', () => {
  it('(d) streaming reasoning with no matching block stays at the root level', () => {
    // When there are no subagent/communication blocks in the prepared list,
    // a streaming reasoning orphan must remain at the root.  This preserves
    // the top-level reasoning use case (G5: ordinary agent reasoning is visible).
    const msgs: ThreadMessageDto[] = [
      // Just a streaming reasoning — no blocks at all
      makeStreamingReasoning('reasoning:toplevel'),
    ];

    const prepared = prepareReadyMessages(msgs, defaultOptions);

    const rootReasoning = prepared.filter((item) => item.type === 'reasoning');
    expect(rootReasoning).toHaveLength(1);
    expect(rootReasoning[0].id).toBe('reasoning-reasoning:toplevel');
  });

  it('(d) streaming reasoning with a non-matching __toolCallId stays at root when no block matches', () => {
    // When __toolCallId is set but no block in the prepared list has that
    // toolCallId, the orphan falls back to findDeepestActiveBlock.  With no
    // active blocks, it remains at root.
    const msgs: ThreadMessageDto[] = [
      makeStreamingReasoning('reasoning:nomatch', {
        toolCallId: 'tc-nonexistent',
      }),
    ];

    const prepared = prepareReadyMessages(msgs, defaultOptions);

    const rootReasoning = prepared.filter((item) => item.type === 'reasoning');
    expect(rootReasoning).toHaveLength(1);
  });
});

// ── Scenario: persisted vs streaming subagent-inner reasoning (pre-scan wins) ──

describe('subagent-inner reasoning pre-scan grouping', () => {
  it('routes persisted subagent reasoning (no streaming flag) into the SubagentBlock via pre-scan', () => {
    // Persisted reasoning after reload: carries __toolCallId + __subagentCommunication,
    // but NOT STREAMING_REASONING_FLAG.  The pre-scan at prepareMessages.ts:391-428
    // groups it into subagentInnerByToolCallId so it renders inside the SubagentBlock
    // rather than leaking to the parent timeline.
    const msgs: ThreadMessageDto[] = [
      makeSubagentCallMsg('ai-call-1', 'tc1'),
      makeMsg('reasoning-1', 'reasoning', 'thinking...', {
        __toolCallId: 'tc1',
        __subagentCommunication: true,
        __reasoningId: 'reasoning:chunk-a',
      }),
      makeSubagentResultMsg('tool-result-1', 'tc1'),
    ];

    const prepared = prepareReadyMessages(msgs, defaultOptions);

    // Exactly one top-level item, of type 'subagent'.
    expect(prepared).toHaveLength(1);
    expect(prepared[0].type).toBe('subagent');

    // Reasoning is inside the subagent block.
    const block = findSubagentBlock(prepared, 'tc1');
    expect(block).toBeDefined();
    const innerReasoning = block!.innerMessages.filter(
      (m) => m.type === 'reasoning',
    );
    expect(innerReasoning).toHaveLength(1);

    // And NOT at the top level.
    const rootReasoning = prepared.filter((m) => m.type === 'reasoning');
    expect(rootReasoning).toHaveLength(0);
  });

  it('subagent-tagged streaming reasoning with matching __toolCallId is routed by pre-scan (not orphan adoption)', () => {
    // Mid-run streaming: no tool result yet, reasoning carries both STREAMING_REASONING_FLAG
    // (from makeStreamingReasoning) AND __toolCallId matching a loaded subagents_run_task
    // call.  Because the pre-scan runs BEFORE adoptOrphanStreamingReasoning, the
    // reasoning ends up inside the 'calling' subagent block via pre-scan — not via
    // orphan adoption.  The end result looks the same, but this test locks in
    // the execution order so future refactors don't silently route through orphan
    // adoption.
    const msgs: ThreadMessageDto[] = [
      makeSubagentCallMsg('ai-call-1', 'tc1'),
      makeStreamingReasoning('reasoning:chunk-a', {
        toolCallId: 'tc1',
        subagentCommunication: true,
      }),
    ];

    const prepared = prepareReadyMessages(msgs, {
      ...defaultOptions,
      isNodeRunning: true,
    });

    // The subagent block ('calling' status — no tool result yet) contains the reasoning.
    const block = findSubagentBlock(prepared, 'tc1');
    expect(block).toBeDefined();
    const innerReasoning = block!.innerMessages.filter(
      (m) => m.type === 'reasoning',
    );
    expect(innerReasoning).toHaveLength(1);

    // No top-level reasoning — neither pre-scan nor orphan adoption must duplicate.
    expect(prepared.filter((m) => m.type === 'reasoning')).toHaveLength(0);
  });
});

describe('Claude Agent SDK native subagent (tool name "Agent")', () => {
  // The SDK surfaces its native sub-agent spawn as a top-level tool call named
  // `Agent` (NOT subagents_run_task) and tags each inner message with
  // __subagentCommunication + __toolCallId = the spawn call's id. Before the
  // fix these rendered as flat `Agent`/`Write` chips in a generic "Working..."
  // card; they must instead group into a SubagentBlock like run-task does.
  const PARENT = 'toolu_sdk_agent_1';

  const sdkAgentScenario = (): ThreadMessageDto[] => [
    // Parent AI message owning the SDK `Agent` tool call (description + prompt args).
    {
      id: 'ai-agent-call',
      threadId: 'thread-1',
      nodeId: 'node-1',
      externalThreadId: '',
      createdAt: '2024-01-01T00:00:00.000Z',
      updatedAt: '2024-01-01T00:00:00.000Z',
      message: {
        id: 'ai-agent-call',
        role: 'ai',
        content: '',
        toolCalls: [
          {
            id: PARENT,
            name: 'Agent',
            type: 'tool_call',
            args: {
              prompt: 'Create a file hello.js that prints Hello World',
              description: 'Create JS Hello World file',
              subagent_type: 'general-purpose',
            },
          },
        ],
      } as unknown as ThreadMessageDto['message'],
    },
    // Inner AI message that calls Write — surrogate node + subagent-comm flags.
    {
      id: 'sub-ai-write',
      threadId: 'thread-1',
      nodeId: `node-1::sub::${PARENT}`,
      externalThreadId: '',
      createdAt: '2024-01-01T00:00:30.000Z',
      updatedAt: '2024-01-01T00:00:30.000Z',
      message: {
        id: 'sub-ai-write',
        role: 'ai',
        content: '',
        toolCalls: [
          {
            id: 'toolu_write_1',
            name: 'Write',
            type: 'tool_call',
            args: {
              file_path: '/runtime-workspace/hello.js',
              content: 'console.log("Hello World");\n',
            },
          },
        ],
        additionalKwargs: {
          __toolCallId: PARENT,
          __subagentCommunication: true,
          __model: 'claude-opus-4-8',
        },
      } as unknown as ThreadMessageDto['message'],
    },
    // Inner Write tool result.
    {
      id: 'sub-tool-write',
      threadId: 'thread-1',
      nodeId: `node-1::sub::${PARENT}`,
      externalThreadId: '',
      createdAt: '2024-01-01T00:00:40.000Z',
      updatedAt: '2024-01-01T00:00:40.000Z',
      message: {
        id: 'sub-tool-write',
        role: 'tool',
        name: 'Write',
        toolCallId: 'toolu_write_1',
        content: 'File created',
        additionalKwargs: {
          __toolCallId: PARENT,
          __subagentCommunication: true,
        },
      } as unknown as ThreadMessageDto['message'],
    },
    // The `Agent` tool result on the parent node — content is `{ message }`.
    {
      id: 'tool-agent-result',
      threadId: 'thread-1',
      nodeId: 'node-1',
      externalThreadId: '',
      createdAt: '2024-01-01T00:01:00.000Z',
      updatedAt: '2024-01-01T00:01:00.000Z',
      message: {
        id: 'tool-agent-result',
        role: 'tool',
        name: 'Agent',
        toolCallId: PARENT,
        // Mirrors the real SDK shape: human answer followed by the machine
        // footer (continuation handle + <usage> block) that must be stripped.
        content: {
          message:
            'Done. Created /runtime-workspace/hello.js\n' +
            "agentId: ab4bd012 (use SendMessage with to: 'ab4bd012' to continue this agent)\n" +
            '<usage>subagent_tokens: 16236\ntool_uses: 1\nduration_ms: 6548</usage>',
        },
      } as unknown as ThreadMessageDto['message'],
    },
  ];

  it('groups the SDK `Agent` spawn into a SubagentBlock with SDK arg/result keys', () => {
    const prepared = prepareReadyMessages(sdkAgentScenario(), defaultOptions);

    // Exactly one top-level item — the subagent block. No leaked `Agent`/`Write`
    // chips at the parent timeline (the pre-fix symptom).
    expect(prepared).toHaveLength(1);
    expect(prepared[0].type).toBe('subagent');

    const block = findSubagentBlock(prepared, PARENT);
    expect(block).toBeDefined();
    // Header purpose ← SDK `description` arg; task ← `prompt` arg.
    expect(block!.purpose).toBe('Create JS Hello World file');
    expect(block!.taskDescription).toBe(
      'Create a file hello.js that prints Hello World',
    );
    // Result text ← the `{ message }` tool-result key (not `result`), with the
    // SDK footer (agentId / <usage>) stripped.
    expect(block!.resultText).toBe('Done. Created /runtime-workspace/hello.js');
    // Model is read off the inner messages.
    expect(block!.model).toBe('claude-opus-4-8');
  });

  it('nests the inner Write tool inside the block, not at the top level', () => {
    const prepared = prepareReadyMessages(sdkAgentScenario(), defaultOptions);

    // No tool items leak to the parent timeline.
    expect(prepared.filter((m) => m.type === 'tool')).toHaveLength(0);

    const block = findSubagentBlock(prepared, PARENT);
    expect(block).toBeDefined();
    const innerTools = block!.innerMessages.filter((m) => m.type === 'tool');
    expect(innerTools.length).toBeGreaterThanOrEqual(1);

    // The inner SDK `Write` tool gets a human-readable title from its args
    // instead of the bare tool name.
    const writeTool = innerTools.find(
      (m) => m.type === 'tool' && m.name === 'Write',
    );
    expect(writeTool).toBeDefined();
    expect((writeTool as { title?: string }).title).toBe(
      'Write /runtime-workspace/hello.js',
    );
  });
});

// ── accumulatePreparedStatistics — Change 1 regression guard ─────────────────
//
// These scenarios verify that tool items do NOT double-count price/tokens that
// are already contributed by their sibling chat item (which carries the same
// requestTokenUsage reference from the parent AI message DTO).

describe('accumulatePreparedStatistics', () => {
  // Minimal required fields for a ThreadMessageDto used as a chat item's message.
  const makeMinimalDto = (
    id: string,
    requestTokenUsage?: ThreadMessageDto['requestTokenUsage'],
  ): ThreadMessageDto => ({
    id,
    threadId: 'thread-1',
    nodeId: 'node-1',
    externalThreadId: '',
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
    requestTokenUsage,
    message: {
      id,
      role: 'ai',
      content: 'hello',
    } as ThreadMessageDto['message'],
  });

  it('1.1 — chat + 2 tool siblings sharing requestTokenUsage: totalPrice and totalTokens counted once', () => {
    // Regression guard for the (N+1)x double-count: a single AI turn produces
    // one chat PreparedMessage and N tool PreparedMessages, all carrying the
    // same requestTokenUsage. Only the chat item must contribute to
    // totalPrice/totalTokens; tool items contribute only durationMs + count.
    const sharedUsage: ThreadMessageDto['requestTokenUsage'] = {
      inputTokens: 600,
      outputTokens: 400,
      totalTokens: 1000,
      totalPrice: 0.05,
    };

    const chatItem: PreparedMessage = {
      type: 'chat',
      id: 'chat-1',
      message: makeMinimalDto('chat-1', sharedUsage),
    };

    const toolItem1: PreparedMessage = {
      type: 'tool',
      id: 'tool-1',
      name: 'search',
      status: 'executed',
      requestTokenUsage: sharedUsage,
    };

    const toolItem2: PreparedMessage = {
      type: 'tool',
      id: 'tool-2',
      name: 'fetch',
      status: 'executed',
      requestTokenUsage: sharedUsage,
    };

    const stats = _accumulatePreparedStatistics([
      chatItem,
      toolItem1,
      toolItem2,
    ]);

    expect(stats).toBeDefined();
    // totalPrice and totalTokens must come from the chat item only — NOT tripled.
    expect(stats!.usage!.totalPrice).toBe(0.05);
    expect(stats!.usage!.totalTokens).toBe(1000);
  });

  it('1.2 — 3 tool items with no requestTokenUsage and no sibling chat: accumulator returns undefined', () => {
    // Per-block durationMs aggregates were removed in favour of the live
    // thread-runtime timer (which counts wall-clock once instead of summing
    // per-leaf, fixing the parallel-subagent double-count bug). Tools that
    // carry only a per-leaf durationMs and no requestTokenUsage therefore
    // contribute nothing to the block-level accumulator; with no usage on
    // any item the accumulator reports undefined (count = 0).
    const toolA: PreparedMessage = {
      type: 'tool',
      id: 'tool-a',
      name: 'shell',
      status: 'executed',
      durationMs: 100,
    };

    const toolB: PreparedMessage = {
      type: 'tool',
      id: 'tool-b',
      name: 'shell',
      status: 'executed',
      durationMs: 200,
    };

    const toolC: PreparedMessage = {
      type: 'tool',
      id: 'tool-c',
      name: 'shell',
      status: 'executed',
      durationMs: 300,
    };

    const stats = _accumulatePreparedStatistics([toolA, toolB, toolC]);

    expect(stats).toBeUndefined();
  });

  it('1.3 — communication child block + 2 outer chat items: totalPrice accumulates from both sources', () => {
    // A communication/subagent block contributes its pre-computed statistics as
    // a single item to the parent accumulator; outer chat items contribute their
    // own requestTokenUsage. Together they must sum correctly.
    const chatItem1: PreparedMessage = {
      type: 'chat',
      id: 'outer-chat-1',
      message: makeMinimalDto('outer-chat-1', {
        inputTokens: 100,
        outputTokens: 100,
        totalTokens: 200,
        totalPrice: 0.02,
      }),
    };

    const chatItem2: PreparedMessage = {
      type: 'chat',
      id: 'outer-chat-2',
      message: makeMinimalDto('outer-chat-2', {
        inputTokens: 100,
        outputTokens: 100,
        totalTokens: 200,
        totalPrice: 0.02,
      }),
    };

    const communicationBlock: PreparedMessage = {
      type: 'communication',
      id: 'comm-1',
      toolCallId: 'tc-comm-1',
      innerMessages: [],
      status: 'executed',
      statistics: {
        usage: {
          totalPrice: 0.1,
          totalTokens: 500,
        },
      },
    };

    const stats = _accumulatePreparedStatistics([
      chatItem1,
      communicationBlock,
      chatItem2,
    ]);

    expect(stats).toBeDefined();
    // outer chat 1 ($0.02) + communication block ($0.10) + outer chat 2 ($0.02) = $0.14
    expect(stats!.usage!.totalPrice).toBeCloseTo(0.14, 10);
    expect(stats!.usage!.totalTokens).toBe(900); // 200 + 500 + 200
  });

  it('1.4 — unpriced subagent (totalTokens > 0, totalPrice sums to exactly 0): preserves 0 so formatUsd renders "$0.000"', () => {
    // Primary H2 scenario: subagent ran against an unpriced model, so each
    // request's totalPrice is 0 but totalTokens are populated. The accumulator
    // must preserve `totalPrice === 0` (not coerce to undefined), because the
    // downstream `formatUsd` distinguishes `0 → "$0.000"` from `undefined → "$—"`.
    const chatItem1: PreparedMessage = {
      type: 'chat',
      id: 'chat-unpriced-1',
      message: makeMinimalDto('chat-unpriced-1', {
        inputTokens: 100,
        outputTokens: 50,
        totalTokens: 150,
        totalPrice: 0,
      }),
    };

    const chatItem2: PreparedMessage = {
      type: 'chat',
      id: 'chat-unpriced-2',
      message: makeMinimalDto('chat-unpriced-2', {
        inputTokens: 200,
        outputTokens: 100,
        totalTokens: 300,
        totalPrice: 0,
      }),
    };

    const stats = _accumulatePreparedStatistics([chatItem1, chatItem2]);

    expect(stats).toBeDefined();
    // Tokens are summed normally.
    expect(stats!.usage!.totalTokens).toBe(450);
    // Price is genuine 0 — must NOT be coerced to undefined.
    expect(stats!.usage!.totalPrice).toBe(0);
    // Safety: confirm it's a number, not undefined. `formatUsd(0) === "$0.000"`,
    // `formatUsd(undefined) === "$—"` — we want the "$0.000" path.
    expect(typeof stats!.usage!.totalPrice).toBe('number');
  });

  it('1.5 — in-flight subagent: inner AI msg with tool_calls only credits requestTokenUsage to live SubagentBlock statistics', () => {
    // Regression guard for "live cost shows $0.000" bug: an inner subagent AI
    // message that emits ONLY tool_calls (blank text content) used to lose its
    // requestTokenUsage entirely.  prepareReadyMessages does not push a 'chat'
    // prepared item for blank-content AI messages, and the old one-pass
    // accumulator skipped price/tokens on tool items "because the sibling chat
    // carries it" — but with no sibling, the cost was dropped.  The two-pass
    // walk now credits via the tool branch when no chat/reasoning sibling has
    // already credited the same requestTokenUsage object.
    const parentToolCallId = 'tc-running-sub-15';
    const innerToolCallId = 'inner-tc-shell-15';

    const parentAiCall = makeSubagentCallMsg('parent-ai-15', parentToolCallId);

    // Inner AI message: blank content + tool_calls, with usage info.
    // Using cast to ThreadMessageDto['message'] to satisfy the auto-generated type.
    const innerAi = (() => {
      const msg = makeMsg('inner-ai-15', 'ai', '', {
        __toolCallId: parentToolCallId,
        __subagentCommunication: true,
      });
      msg.requestTokenUsage = {
        inputTokens: 200,
        outputTokens: 50,
        totalTokens: 250,
        totalPrice: 0.01,
      };
      // Manually add toolCalls to the message object.
      (msg.message as unknown as Record<string, unknown>).toolCalls = [
        { id: innerToolCallId, name: 'shell' },
      ];
      return msg;
    })();

    // Inner tool result message.
    const innerToolResult = (() => {
      const msg = makeMsg('inner-tool-15', 'tool', 'ok', {
        __toolCallId: parentToolCallId,
        __subagentCommunication: true,
      });
      (msg.message as unknown as Record<string, unknown>).name = 'shell';
      (msg.message as unknown as Record<string, unknown>).toolCallId =
        innerToolCallId;
      return msg;
    })();

    const prepared = prepareReadyMessages(
      [parentAiCall, innerAi, innerToolResult],
      { ...defaultOptions, isNodeRunning: true },
    );

    const block = findSubagentBlock(prepared, parentToolCallId);
    expect(block).toBeDefined();
    expect(block!.type).toBe('subagent');
    expect(block!.status).toBe('calling');
    expect(block!.statistics?.usage?.totalTokens).toBe(250);
    expect(block!.statistics?.usage?.totalPrice).toBeCloseTo(0.01, 10);
  });

  it('1.6 — tool-only AI msg with multiple sibling tool_calls credits requestTokenUsage exactly once via reference dedup', () => {
    // Companion to 1.5: when an AI message has 2+ tool calls (still no chat
    // content), all sibling tool prepared items share the SAME
    // requestTokenUsage object by reference.  The WeakSet dedup must credit
    // only once — not N times.  The total price/tokens reported equal the
    // original AI message's usage, never multiplied by the tool count.
    const sharedUsage: ThreadMessageDto['requestTokenUsage'] = {
      inputTokens: 400,
      outputTokens: 100,
      totalTokens: 500,
      totalPrice: 0.02,
    };

    const toolItem1: PreparedMessage = {
      type: 'tool',
      id: 'tool-only-a',
      name: 'shell',
      status: 'executed',
      requestTokenUsage: sharedUsage,
      durationMs: 100,
    };

    const toolItem2: PreparedMessage = {
      type: 'tool',
      id: 'tool-only-b',
      name: 'files_read',
      status: 'executed',
      requestTokenUsage: sharedUsage,
      durationMs: 200,
    };

    const toolItem3: PreparedMessage = {
      type: 'tool',
      id: 'tool-only-c',
      name: 'shell',
      status: 'executed',
      requestTokenUsage: sharedUsage,
      durationMs: 300,
    };

    const stats = _accumulatePreparedStatistics([
      toolItem1,
      toolItem2,
      toolItem3,
    ]);

    expect(stats).toBeDefined();
    // Credited exactly once via reference dedup — not 3×.
    expect(stats!.usage!.totalPrice).toBeCloseTo(0.02, 10);
    expect(stats!.usage!.totalTokens).toBe(500);
  });
});

// ── Stopped subagent surfaces a synthetic errorText ──────────────────────────

describe('SubagentBlock — stopped status surfaces synthetic errorText', () => {
  it('a subagents_run_task tool_call without a matching tool result becomes status=stopped with a non-empty errorText', () => {
    const aiCall = makeSubagentCallMsg('ai-1', 'tc-stopped');

    const prepared = prepareReadyMessages([aiCall], defaultOptions);

    const block = findSubagentBlock(prepared, 'tc-stopped');
    expect(block).toBeDefined();
    expect(block!.status).toBe('stopped');
    expect(typeof block!.errorText).toBe('string');
    expect(block!.errorText!.length).toBeGreaterThan(0);
  });

  it('a subagent that has an explicit error in its tool result keeps that text', () => {
    const aiCall = makeSubagentCallMsg('ai-2', 'tc-with-error');
    const toolResult = makeSubagentResultMsg('tool-2', 'tc-with-error');
    (toolResult.message as { content: unknown }).content = {
      result: 'Subagent execution failed: provider-error 503',
      error: 'provider-error 503',
      statistics: { usage: null, totalIterations: 0, toolCallsMade: 0 },
    };

    const prepared = prepareReadyMessages([aiCall, toolResult], defaultOptions);

    const block = findSubagentBlock(prepared, 'tc-with-error');
    expect(block).toBeDefined();
    expect(block!.status).toBe('executed');
    expect(block!.errorText).toBe('provider-error 503');
  });

  it('an executed subagent without an error keeps errorText undefined', () => {
    const aiCall = makeSubagentCallMsg('ai-3', 'tc-success');
    const toolResult = makeSubagentResultMsg('tool-3', 'tc-success');
    (toolResult.message as { content: unknown }).content = {
      result: 'Task completed.',
      statistics: { usage: null, totalIterations: 1, toolCallsMade: 0 },
    };

    const prepared = prepareReadyMessages([aiCall, toolResult], defaultOptions);

    const block = findSubagentBlock(prepared, 'tc-success');
    expect(block).toBeDefined();
    expect(block!.status).toBe('executed');
    expect(block!.errorText).toBeUndefined();
  });

  it('a stopped subagent gets NO synthetic errorText when the thread itself was user-stopped', () => {
    // When the user manually stops a thread, in-flight tool calls naturally
    // end up status=stopped without a tool result. Showing a "no result"
    // error there would be misleading — the user knows they stopped it.
    const aiCall = makeSubagentCallMsg('ai-stop', 'tc-userstop');

    const prepared = prepareReadyMessages([aiCall], {
      ...defaultOptions,
      isThreadStopped: true,
    });

    const block = findSubagentBlock(prepared, 'tc-userstop');
    expect(block).toBeDefined();
    expect(block!.status).toBe('stopped');
    expect(block!.errorText).toBeUndefined();
  });
});

// ── Bridge-split turn: preamble text folds into the working block ─────────────

describe('split-turn preamble folds into the working block', () => {
  // The Claude bridge persists ONE assistant turn (leading text + tool_use) as
  // TWO rows that share a single SDK message id. The text-only row must be
  // marked isToolCallContent so the view folds it INTO the following working
  // block (the turn's cost lives on the tool row) instead of rendering it as a
  // standalone, cost-less bubble above its own turn's block.
  const splitPreamble = (rowId: string, sdkId: string): ThreadMessageDto => ({
    id: rowId,
    threadId: 'thread-1',
    nodeId: 'node-1',
    externalThreadId: '',
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
    message: {
      id: sdkId,
      role: 'ai',
      content: "I'll pull up that Linear issue for you.",
    } as ThreadMessageDto['message'],
  });

  const splitToolCall = (
    rowId: string,
    sdkId: string,
    toolCallId: string,
  ): ThreadMessageDto => ({
    id: rowId,
    threadId: 'thread-1',
    nodeId: 'node-1',
    externalThreadId: '',
    createdAt: '2024-01-01T00:00:01.000Z',
    updatedAt: '2024-01-01T00:00:01.000Z',
    message: {
      id: sdkId,
      role: 'ai',
      content: '',
      toolCalls: [{ id: toolCallId, name: 'mcp__linear__get_issue' }],
    } as ThreadMessageDto['message'],
  });

  const findChat = (
    items: PreparedMessage[],
    rowId: string,
  ): (PreparedMessage & { type: 'chat' }) | undefined =>
    collectItems(
      items,
      (item) => item.type === 'chat' && item.id === `chat-${rowId}`,
    )[0] as (PreparedMessage & { type: 'chat' }) | undefined;

  it('marks the preamble text row isToolCallContent when it shares an SDK id with a sibling tool-call row', () => {
    const prepared = prepareReadyMessages(
      [
        splitPreamble('row-text', 'msg_split'),
        splitToolCall('row-tool', 'msg_split', 'tc1'),
      ],
      defaultOptions,
    );

    const preamble = findChat(prepared, 'row-text');
    expect(preamble).toBeDefined();
    expect(preamble!.isToolCallContent).toBe(true);
  });

  it('leaves a pure-text turn (no sibling tool row) as a standalone chat bubble', () => {
    const prepared = prepareReadyMessages(
      [makeMsg('row-final', 'ai', "Here's what that Linear issue is about.")],
      defaultOptions,
    );

    const finalAnswer = findChat(prepared, 'row-final');
    expect(finalAnswer).toBeDefined();
    expect(finalAnswer!.isToolCallContent).toBeFalsy();
  });
});

// ── Communication block: session label + new-thread indicator ────────────────

describe('communication block — session label and new-thread indicator', () => {
  const commCallMsg = (
    aiRowId: string,
    toolCallId: string,
    session?: string,
  ): ThreadMessageDto => ({
    id: aiRowId,
    threadId: 'thread-1',
    nodeId: 'node-1',
    externalThreadId: '',
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
    message: {
      id: aiRowId,
      role: 'ai',
      content: 'Delegating to the engineer.',
      toolCalls: [
        {
          id: toolCallId,
          name: 'communication_exec',
          args: {
            agent: 'Engineer',
            message: 'Plan the task',
            purpose: 'Planning',
            ...(session ? { session } : {}),
          },
        },
      ],
    } as unknown as ThreadMessageDto['message'],
  });

  const commResultMsg = (
    toolRowId: string,
    toolCallId: string,
    startedNewThread?: boolean,
  ): ThreadMessageDto => ({
    id: toolRowId,
    threadId: 'thread-1',
    nodeId: 'node-1',
    externalThreadId: '',
    createdAt: '2024-01-01T00:01:00.000Z',
    updatedAt: '2024-01-01T00:01:00.000Z',
    message: {
      id: toolRowId,
      role: 'tool',
      name: 'communication_exec',
      toolCallId,
      content: JSON.stringify({
        message: 'Plan written to .geniro/planning/spec.md',
        needsMoreInfo: false,
        threadId: 'parent__tool__Engineer__plan',
        ...(startedNewThread !== undefined ? { startedNewThread } : {}),
      }),
    } as unknown as ThreadMessageDto['message'],
  });

  const findCommunication = (
    items: PreparedMessage[],
    toolCallId: string,
  ): (PreparedMessage & { type: 'communication' }) | undefined =>
    collectItems(
      items,
      (it) => it.type === 'communication' && it.toolCallId === toolCallId,
    )[0] as (PreparedMessage & { type: 'communication' }) | undefined;

  it('carries the session label and new-thread flag onto the communication block', () => {
    const prepared = prepareReadyMessages(
      [
        commCallMsg('ai-c1', 'tc-c1', 'plan'),
        commResultMsg('tool-c1', 'tc-c1', true),
      ],
      defaultOptions,
    );

    const block = findCommunication(prepared, 'tc-c1');
    expect(block).toBeDefined();
    expect(block!.sessionLabel).toBe('plan');
    expect(block!.isNewThread).toBe(true);
  });

  it('marks a resumed delegation as continued (isNewThread false) keeping the label', () => {
    const prepared = prepareReadyMessages(
      [
        commCallMsg('ai-c2', 'tc-c2', 'plan'),
        commResultMsg('tool-c2', 'tc-c2', false),
      ],
      defaultOptions,
    );

    const block = findCommunication(prepared, 'tc-c2');
    expect(block).toBeDefined();
    expect(block!.sessionLabel).toBe('plan');
    expect(block!.isNewThread).toBe(false);
  });

  it('leaves both undefined for a label-less call that reports no new-thread flag', () => {
    const prepared = prepareReadyMessages(
      [commCallMsg('ai-c3', 'tc-c3'), commResultMsg('tool-c3', 'tc-c3')],
      defaultOptions,
    );

    const block = findCommunication(prepared, 'tc-c3');
    expect(block).toBeDefined();
    expect(block!.sessionLabel).toBeUndefined();
    expect(block!.isNewThread).toBeUndefined();
  });
});
