// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest';

import {
  act,
  cleanup,
  fireEvent,
  render,
  waitFor,
} from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

const { getAllProjects } = vi.hoisted(() => ({ getAllProjects: vi.fn() }));
vi.mock('../api', () => ({ projectsApi: { getAllProjects } }));

import React from 'react';

import type { ProjectDto } from '../autogenerated';
import { ProjectProvider, useProjectContext } from './ProjectContext';

const STORAGE_KEY = 'geniro:last-project-id';
const VALID_UUID_A = '11111111-1111-4111-8111-111111111111';
const VALID_UUID_B = '22222222-2222-4222-8222-222222222222';

const makeProject = (overrides: Partial<ProjectDto> = {}): ProjectDto => ({
  id: VALID_UUID_A,
  name: 'Test Project',
  description: null,
  icon: null,
  color: '#3B82F6',
  settings: {},
  costLimitUsd: null,
  createdBy: 'user-1',
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
  graphCount: 0,
  threadCount: 0,
  ...overrides,
});

const Probe = () => {
  const ctx = useProjectContext();
  return (
    <div
      data-testid="probe"
      data-loading={String(ctx.loading)}
      data-current={ctx.currentProjectId ?? ''}
      data-count={ctx.projects.length}>
      <button
        data-testid="set-null"
        onClick={() => ctx.setCurrentProjectId(null)}
      />
      <button
        data-testid="set-b"
        onClick={() => ctx.setCurrentProjectId(VALID_UUID_B)}
      />
      <button data-testid="reload" onClick={() => void ctx.loadProjects()} />
    </div>
  );
};

const renderProvider = () =>
  render(
    <ProjectProvider>
      <Probe />
    </ProjectProvider>,
  );

describe('ProjectContext', () => {
  beforeEach(() => {
    localStorage.clear();
    getAllProjects.mockReset();
  });

  afterEach(() => {
    cleanup();
  });

  it('starts with loading=true and empty projects when no localStorage entry exists', () => {
    // Never resolves in this test — we assert the initial synchronous state before fetch settles
    getAllProjects.mockReturnValue(new Promise(() => {}));

    const { getByTestId } = renderProvider();
    const probe = getByTestId('probe');

    expect(probe.dataset.loading).toBe('true');
    expect(probe.dataset.count).toBe('0');
    expect(probe.dataset.current).toBe('');
  });

  it('after fetch resolves: loading=false, projects populated, auto-selects first project when none stored', async () => {
    getAllProjects.mockResolvedValueOnce({
      data: [makeProject(), makeProject({ id: VALID_UUID_B, name: 'Second' })],
    });

    const { getByTestId } = renderProvider();
    const probe = getByTestId('probe');

    // Wait for both loading to finish AND the auto-select effect to fire (two separate useEffects)
    await waitFor(() => {
      expect(probe.dataset.loading).toBe('false');
      expect(probe.dataset.current).toBe(VALID_UUID_A);
    });

    expect(probe.dataset.count).toBe('2');
    expect(localStorage.getItem(STORAGE_KEY)).toBe(VALID_UUID_A);
  });

  it('honors a valid stored UUID that matches a returned project', async () => {
    localStorage.setItem(STORAGE_KEY, VALID_UUID_B);
    getAllProjects.mockResolvedValueOnce({
      data: [makeProject(), makeProject({ id: VALID_UUID_B, name: 'Second' })],
    });

    const { getByTestId } = renderProvider();
    const probe = getByTestId('probe');

    await waitFor(() => expect(probe.dataset.loading).toBe('false'));

    expect(probe.dataset.current).toBe(VALID_UUID_B);
  });

  it('replaces a valid stored UUID that is not in the returned set with the first project ID', async () => {
    localStorage.setItem(STORAGE_KEY, VALID_UUID_B);
    getAllProjects.mockResolvedValueOnce({ data: [makeProject()] });

    const { getByTestId } = renderProvider();
    const probe = getByTestId('probe');

    // Wait for both loading to finish AND the replace-stale-id effect to fire (two separate useEffects)
    await waitFor(() => {
      expect(probe.dataset.loading).toBe('false');
      expect(probe.dataset.current).toBe(VALID_UUID_A);
    });

    expect(localStorage.getItem(STORAGE_KEY)).toBe(VALID_UUID_A);
  });

  it('treats an invalid (non-UUID) stored value as null and auto-selects the first project', async () => {
    localStorage.setItem(STORAGE_KEY, 'not-a-uuid');
    getAllProjects.mockResolvedValueOnce({ data: [makeProject()] });

    const { getByTestId } = renderProvider();
    const probe = getByTestId('probe');

    // Wait for both loading to finish AND the auto-select effect to fire (two separate useEffects)
    await waitFor(() => {
      expect(probe.dataset.loading).toBe('false');
      expect(probe.dataset.current).toBe(VALID_UUID_A);
    });
  });

  it('setCurrentProjectId(id) writes to localStorage', async () => {
    // Both projects returned so VALID_UUID_B passes the auto-select validation effect
    getAllProjects.mockResolvedValueOnce({
      data: [makeProject(), makeProject({ id: VALID_UUID_B, name: 'Second' })],
    });

    const { getByTestId } = renderProvider();
    const probe = getByTestId('probe');
    await waitFor(() => expect(probe.dataset.loading).toBe('false'));

    await act(async () => {
      fireEvent.click(getByTestId('set-b'));
    });

    expect(localStorage.getItem(STORAGE_KEY)).toBe(VALID_UUID_B);
    expect(probe.dataset.current).toBe(VALID_UUID_B);
  });

  it('setCurrentProjectId(null) removes the localStorage key', async () => {
    // Empty projects causes the auto-select effect to bail early (projects.length === 0),
    // so the null set is not immediately overridden by re-selection
    getAllProjects.mockResolvedValueOnce({ data: [] });

    const { getByTestId } = renderProvider();
    const probe = getByTestId('probe');
    await waitFor(() => expect(probe.dataset.loading).toBe('false'));

    localStorage.setItem(STORAGE_KEY, VALID_UUID_A);

    await act(async () => {
      fireEvent.click(getByTestId('set-null'));
    });

    expect(localStorage.getItem(STORAGE_KEY)).toBeNull();
    expect(probe.dataset.current).toBe('');
  });

  it('logs and recovers when getAllProjects rejects', async () => {
    const consoleSpy = vi.spyOn(console, 'error').mockImplementation(() => {});
    getAllProjects.mockRejectedValueOnce(new Error('boom'));

    const { getByTestId } = renderProvider();
    const probe = getByTestId('probe');

    await waitFor(() => expect(probe.dataset.loading).toBe('false'));

    expect(probe.dataset.count).toBe('0');
    expect(consoleSpy).toHaveBeenCalledTimes(1);
    consoleSpy.mockRestore();
  });

  it('loadProjects() from a consumer re-fetches and re-populates state', async () => {
    getAllProjects
      .mockResolvedValueOnce({ data: [makeProject()] })
      .mockResolvedValueOnce({
        data: [
          makeProject(),
          makeProject({ id: VALID_UUID_B, name: 'Second' }),
        ],
      });

    const { getByTestId } = renderProvider();
    const probe = getByTestId('probe');
    await waitFor(() => expect(probe.dataset.loading).toBe('false'));

    expect(probe.dataset.count).toBe('1');

    await act(async () => {
      fireEvent.click(getByTestId('reload'));
    });
    await waitFor(() => expect(probe.dataset.count).toBe('2'));
  });

  it('survives a localStorage write that throws (private-browsing simulation)', async () => {
    // Both projects returned so VALID_UUID_B is valid and won't be overridden by the effect
    getAllProjects.mockResolvedValueOnce({
      data: [makeProject(), makeProject({ id: VALID_UUID_B, name: 'Second' })],
    });

    const { getByTestId } = renderProvider();
    const probe = getByTestId('probe');
    await waitFor(() => expect(probe.dataset.loading).toBe('false'));

    // stub Storage.prototype.setItem to simulate private-browsing quota error
    const setItemSpy = vi
      .spyOn(Storage.prototype, 'setItem')
      .mockImplementation(() => {
        throw new Error('quota');
      });

    try {
      await act(async () => {
        fireEvent.click(getByTestId('set-b'));
      });
      // React state updates even when the storage write silently fails
      expect(probe.dataset.current).toBe(VALID_UUID_B);
    } finally {
      setItemSpy.mockRestore();
    }
  });
});
