// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: string;
};

export type RuntimeHealthDto = {
  /**
   * Whether the runtime backend is reachable
   */
  healthy: boolean;
  /**
   * Runtime type checked
   */
  type: 'Docker' | 'Daytona' | 'K8s';
  /**
   * Error message if the runtime is unhealthy
   */
  error?: string;
};

export type RuntimeInstanceDto = {
  /**
   * Runtime instance ID
   */
  id: string;
  /**
   * Graph ID (null for system operations)
   */
  graphId: string | null;
  /**
   * Node ID
   */
  nodeId: string;
  /**
   * External thread ID (graphId:threadUUID)
   */
  externalThreadId: string;
  /**
   * Runtime type
   */
  type: 'Docker' | 'Daytona' | 'K8s';
  /**
   * Runtime instance status
   */
  status: 'Starting' | 'Running' | 'Stopping' | 'Stopped' | 'Failed';
  /**
   * Container name
   */
  containerName: string;
  /**
   * Container image used to start the runtime (if available)
   */
  image?: string;
  /**
   * Last used timestamp
   */
  lastUsedAt: string;
  /**
   * Creation timestamp
   */
  createdAt: string;
  /**
   * Last update timestamp
   */
  updatedAt: string;
};

export type RuntimeInstanceStateDto = {
  /**
   * Runtime instance ID
   */
  id: string;
  /**
   * Current runtime lifecycle status
   */
  status: 'Starting' | 'Running' | 'Stopping' | 'Stopped' | 'Failed';
  /**
   * Sub-phase while status=Starting; null otherwise
   */
  startingPhase:
    | 'PullingImage'
    | 'ContainerCreated'
    | 'InitScript'
    | 'Ready'
    | null;
  /**
   * Classified failure reason when status=Failed
   */
  errorCode:
    | 'ProviderAuth'
    | 'RuntimeIo'
    | 'ImagePull'
    | 'Timeout'
    | 'Unknown'
    | null;
  /**
   * Raw error message captured on the last failure
   */
  lastError: string | null;
  /**
   * Last used timestamp
   */
  lastUsedAt: string;
  /**
   * Last update timestamp
   */
  updatedAt: string;
};

export type CreateRepositoryDto = {
  /**
   * Repository owner
   */
  owner: string;
  /**
   * Repository name
   */
  repo: string;
  /**
   * HTTPS URL of the repository
   */
  url: string;
  /**
   * Git repository host provider
   */
  provider?: 'GITHUB';
  /**
   * Default branch of the repository (defaults to main)
   */
  defaultBranch?: string;
};

export type GitRepositoryDto = {
  /**
   * Repository ID
   */
  id: string;
  /**
   * Repository owner (GitHub username or organization)
   */
  owner: string;
  /**
   * Repository name
   */
  repo: string;
  /**
   * HTTPS URL of the repository
   */
  url: string;
  /**
   * Git repository host provider
   */
  provider: 'GITHUB';
  /**
   * Default branch of the repository (e.g. main, master)
   */
  defaultBranch: string;
  /**
   * User ID who cloned the repository
   */
  createdBy: string;
  /**
   * Project this repository belongs to
   */
  projectId: string | null;
  createdAt: string;
  updatedAt: string;
  installationId?: number | null;
  syncedAt?: string | null;
};

export type RepoIndexDto = {
  /**
   * Index ID
   */
  id: string;
  /**
   * Repository ID
   */
  repositoryId: string;
  /**
   * Repository URL
   */
  repoUrl: string;
  /**
   * Git branch name this index covers
   */
  branch: string;
  /**
   * Indexing status
   */
  status: 'pending' | 'in_progress' | 'completed' | 'failed';
  /**
   * Qdrant collection name
   */
  qdrantCollection: string;
  /**
   * Last indexed commit hash
   */
  lastIndexedCommit: string | null;
  /**
   * Embedding model used
   */
  embeddingModel: string | null;
  /**
   * Vector dimension size
   */
  vectorSize: number | null;
  /**
   * Chunking configuration hash
   */
  chunkingSignatureHash: string | null;
  /**
   * Estimated token count
   */
  estimatedTokens: number;
  /**
   * Actual indexed tokens
   */
  indexedTokens: number;
  /**
   * Error message if failed
   */
  errorMessage: string | null;
  createdAt: string;
  updatedAt: string;
};

export type SyncRepositoriesResponseDto = {
  synced: number;
  removed: number;
  total: number;
};

export type UpdateRepositoryDto = {
  /**
   * HTTPS URL of the repository
   */
  url?: string;
  /**
   * Default branch of the repository
   */
  defaultBranch?: string;
};

export type TriggerReindexDto = {
  /**
   * Repository ID to reindex
   */
  repositoryId: string;
  /**
   * Branch to reindex. Defaults to the repository default branch (main).
   */
  branch?: string;
};

export type TriggerReindexResponseDto = {
  repoIndex: {
    /**
     * Index ID
     */
    id: string;
    /**
     * Repository ID
     */
    repositoryId: string;
    /**
     * Repository URL
     */
    repoUrl: string;
    /**
     * Git branch name this index covers
     */
    branch: string;
    /**
     * Indexing status
     */
    status: 'pending' | 'in_progress' | 'completed' | 'failed';
    /**
     * Qdrant collection name
     */
    qdrantCollection: string;
    /**
     * Last indexed commit hash
     */
    lastIndexedCommit: string | null;
    /**
     * Embedding model used
     */
    embeddingModel: string | null;
    /**
     * Vector dimension size
     */
    vectorSize: number | null;
    /**
     * Chunking configuration hash
     */
    chunkingSignatureHash: string | null;
    /**
     * Estimated token count
     */
    estimatedTokens: number;
    /**
     * Actual indexed tokens
     */
    indexedTokens: number;
    /**
     * Error message if failed
     */
    errorMessage: string | null;
    createdAt: string;
    updatedAt: string;
  };
  /**
   * Human-readable status message
   */
  message: string;
};

export type LiteLlmModelDto = {
  /**
   * Model identifier
   */
  id: string;
  /**
   * Owner of the model
   */
  ownedBy: string;
  /**
   * Whether this model supports embedding
   */
  supportsEmbedding: boolean;
};

export type ModelDefaultsDto = {
  llmLargeModel: string;
  llmLargeCodeModel: string;
  llmMiniCodeModel: string;
  llmCodeExplorerSubagentModel: string;
  llmMiniModel: string;
  llmEmbeddingModel: string;
};

export type LiteLlmModelInfoItemDto = {
  /**
   * LiteLLM database model ID
   */
  id: string;
  /**
   * Model alias (display name)
   */
  modelName: string;
  /**
   * Underlying provider model identifier
   */
  providerModel: string;
  /**
   * Custom API base URL
   */
  apiBase?: string;
  /**
   * Provider override
   */
  customLlmProvider?: string;
  supportsToolCalling?: boolean;
  supportsStreaming?: boolean;
  supportsReasoning?: boolean;
};

export type TestModelRequestDto = {
  /**
   * Model alias to test
   */
  model: string;
};

export type TestModelResponseDto = {
  success: boolean;
  latencyMs: number;
  error?: string;
};

export type TestModelConnectionDto = {
  /**
   * LiteLLM model string, e.g. openai/gpt-4o
   */
  litellmModel: string;
  /**
   * Provider API key
   */
  apiKey?: string;
  /**
   * Custom API base URL
   */
  apiBase?: string;
  /**
   * Named credential reference (resolved server-side)
   */
  litellmCredentialName?: string;
};

export type CreateLiteLlmModelDto = {
  /**
   * Display name / alias
   */
  modelName: string;
  litellmParams: {
    /**
     * Provider model ID, e.g. openai/gpt-4o
     */
    model: string;
    /**
     * Provider API key
     */
    apiKey?: string;
    /**
     * Custom API base URL
     */
    apiBase?: string;
    customLlmProvider?: string;
    maxTokens?: number;
    temperature?: number;
    requestTimeout?: number;
    customHeaders?: {
      [key: string]: string;
    };
    /**
     * Named credential reference
     */
    litellmCredentialName?: string;
  };
  /**
   * Routing tags for this model
   */
  tags?: Array<string>;
  /**
   * Additional model info metadata
   */
  modelInfo?: {
    [key: string]: unknown;
  };
};

export type UpdateLiteLlmModelDto = {
  /**
   * LiteLLM database model ID from model_info.id
   */
  modelId: string;
  modelName?: string;
  litellmParams?: {
    /**
     * Provider model ID, e.g. openai/gpt-4o
     */
    model?: string;
    /**
     * Provider API key
     */
    apiKey?: string;
    /**
     * Custom API base URL
     */
    apiBase?: string;
    customLlmProvider?: string;
    maxTokens?: number;
    temperature?: number;
    requestTimeout?: number;
    customHeaders?: {
      [key: string]: string;
    };
    /**
     * Named credential reference
     */
    litellmCredentialName?: string;
  };
  /**
   * Routing tags for this model
   */
  tags?: Array<string>;
  /**
   * Additional model info metadata
   */
  modelInfo?: {
    [key: string]: unknown;
  };
};

export type LiteLlmProvidersResponseDto = {
  providers: Array<{
    /**
     * Provider identifier, e.g. openai, anthropic
     */
    name: string;
    /**
     * Human-readable label
     */
    label: string;
    /**
     * Example model name format
     */
    modelHint: string;
  }>;
};

export type LiteLlmCredentialsResponseDto = {
  credentials: Array<{
    /**
     * Unique credential identifier
     */
    credentialName: string;
  }>;
};

export type CreateLiteLlmCredentialDto = {
  /**
   * Unique credential identifier
   */
  credentialName: string;
  /**
   * Key-value pairs, e.g. { api_key: "sk-..." }
   */
  credentialValues: {
    [key: string]: string;
  };
};

export type UserPreferencesDto = {
  id: string;
  userId: string;
  preferences: {
    models?: {
      llmLargeModel?: string | null;
      llmLargeCodeModel?: string | null;
      llmMiniCodeModel?: string | null;
      llmCodeExplorerSubagentModel?: string | null;
      llmMiniModel?: string | null;
      llmEmbeddingModel?: string | null;
    };
    costLimitUsd?: number | null;
  };
  costLimitUsd?: number | null;
  createdAt: string;
  updatedAt: string;
};

export type UpdateUserPreferencesDto = {
  models?: {
    llmLargeModel?: string | null;
    llmLargeCodeModel?: string | null;
    llmMiniCodeModel?: string | null;
    llmCodeExplorerSubagentModel?: string | null;
    llmMiniModel?: string | null;
    llmEmbeddingModel?: string | null;
  };
  costLimitUsd?: number | null;
};

export type CreateProjectDto = {
  name: string;
  description?: string | null;
  icon?: string | null;
  color?: string | null;
  settings?: {
    [key: string]: unknown;
  };
  costLimitUsd?: number | null;
};

export type ProjectDto = {
  id: string;
  name: string;
  description?: string | null;
  icon?: string | null;
  color?: string | null;
  settings: {
    [key: string]: unknown;
  };
  costLimitUsd?: number | null;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
  graphCount: number;
  threadCount: number;
};

export type UpdateProjectDto = {
  name?: string;
  description?: string | null;
  icon?: string | null;
  color?: string | null;
  settings?: {
    [key: string]: unknown;
  };
  costLimitUsd?: number | null;
};

export type SetupInfoResponseDto = {
  /**
   * URL to redirect the user to for GitHub App installation
   */
  installUrl: string;
  /**
   * URL to install the GitHub App on a new organization
   */
  newInstallationUrl: string;
  /**
   * Whether the GitHub App is fully configured
   */
  configured: boolean;
  /**
   * Path the user must set as "Setup URL" in their GitHub App settings (append to their domain)
   */
  callbackPath: string;
  /**
   * URL template for reconfiguring a GitHub App installation (replace {id} with the installation ID)
   */
  reconfigureUrlTemplate?: string;
};

export type OAuthLinkRequestDto = {
  /**
   * GitHub OAuth authorization code
   */
  code: string;
  /**
   * Optional GitHub App installation ID hint — used when the user was redirected from a GitHub App install flow
   */
  installationId?: number;
};

export type LinkInstallationResponseDto = {
  /**
   * Whether the installation was successfully linked
   */
  linked: boolean;
  /**
   * GitHub org/user login where the app is installed
   */
  accountLogin: string;
  /**
   * Account type: Organization or User
   */
  accountType: string;
};

export type ListInstallationsResponseDto = {
  installations: Array<{
    /**
     * Installation record ID
     */
    id: string;
    /**
     * GitHub installation ID
     */
    installationId: number;
    /**
     * GitHub org/user login
     */
    accountLogin: string;
    /**
     * Account type: Organization or User
     */
    accountType: string;
    /**
     * Whether the installation is active
     */
    isActive: boolean;
    createdAt: string;
  }>;
};

export type UnlinkInstallationResponseDto = {
  /**
   * Whether the installation was successfully unlinked
   */
  unlinked: boolean;
};

export type KnowledgeDocCreateDto = {
  /**
   * Knowledge document title
   */
  title: string;
  /**
   * Raw knowledge document content
   */
  content: string;
  /**
   * Optional LLM usage guidance for this document. If the politic instructs to fetch full content (e.g. "always fetch the full content instead of fetching only specific chunks"), full document retrieval is permitted.
   */
  politic?: string | null;
  /**
   * Optional tags to apply to the document
   */
  tags?: Array<string> | null;
};

export type KnowledgeDocDto = {
  id: string;
  publicId: number;
  content: string;
  title: string;
  summary?: string | null;
  politic?: string | null;
  embeddingModel?: string | null;
  tags: Array<string>;
  /**
   * Project this knowledge doc belongs to
   */
  projectId: string | null;
  createdAt: string;
  updatedAt: string;
};

export type KnowledgeDocUpdateDto = {
  /**
   * Knowledge document title
   */
  title?: string;
  /**
   * Raw knowledge document content
   */
  content?: string;
  /**
   * Optional LLM usage guidance for this document. If the politic instructs to fetch full content (e.g. "always fetch the full content instead of fetching only specific chunks"), full document retrieval is permitted.
   */
  politic?: string | null;
  /**
   * Optional tags to apply to the document
   */
  tags?: Array<string> | null;
};

export type KnowledgeDocListResultDto = {
  items: Array<{
    id: string;
    publicId: number;
    content: string;
    title: string;
    summary?: string | null;
    politic?: string | null;
    embeddingModel?: string | null;
    tags: Array<string>;
    /**
     * Project this knowledge doc belongs to
     */
    projectId: string | null;
    createdAt: string;
    updatedAt: string;
  }>;
  total: number;
};

export type NamespaceSummaryDto = {
  namespace: string;
  mode: 'kv' | 'append';
  entryCount: number;
  lastUpdatedAt: string;
};

export type ThreadStoreEntryDto = {
  id: string;
  threadId: string;
  namespace: string;
  key: string;
  value: unknown;
  mode: 'kv' | 'append';
  authorAgentId: string | null;
  tags: Array<string> | null;
  createdAt: string;
  updatedAt: string;
};

export type ThreadDto = {
  /**
   * Thread ID
   */
  id: string;
  /**
   * Graph ID
   */
  graphId: string;
  /**
   * External thread ID from LangChain
   */
  externalThreadId: string;
  /**
   * Last LangGraph run_id observed for this thread
   */
  lastRunId?: string | null;
  /**
   * Timestamp when the thread entered Running status; null when not Running
   */
  runningStartedAt: string | null;
  /**
   * Cumulative milliseconds the thread has spent in Running status
   */
  totalRunningMs: number;
  createdAt: string;
  updatedAt: string;
  /**
   * Additional thread metadata
   */
  metadata?: {
    [key: string]: unknown;
  } | null;
  /**
   * Source of thread creation (e.g., trigger template name)
   */
  source?: string | null;
  /**
   * Thread name (auto-generated from first user message)
   */
  name?: string | null;
  /**
   * Thread execution status
   */
  status: 'running' | 'done' | 'need_more_info' | 'stopped' | 'waiting';
  /**
   * Agents in the graph this thread belongs to
   */
  agents?: Array<{
    /**
     * Graph node ID of the agent
     */
    nodeId: string;
    /**
     * Agent display name
     */
    name: string;
    /**
     * Agent description
     */
    description?: string;
  }> | null;
  /**
   * Reason a stopped thread was terminated — e.g. "cost_limit"
   */
  stopReason?: string | null;
  /**
   * Server-resolved effective USD cost limit for this thread
   */
  effectiveCostLimitUsd?: number | null;
};

export type ThreadMessageDto = {
  id: string;
  threadId: string;
  nodeId: string;
  externalThreadId: string;
  createdAt: string;
  updatedAt: string;
  message:
    | {
        /**
         * Message role
         */
        role: 'human';
        /**
         * Message content — plain string or array of content blocks
         */
        content:
          | string
          | Array<
              | {
                  type: 'text';
                  /**
                   * Text content
                   */
                  text: string;
                }
              | {
                  type: 'image_url';
                  image_url: {
                    /**
                     * Base64 data URL (data:image/...;base64,...)
                     */
                    url: string;
                    /**
                     * Vision detail level
                     */
                    detail?: 'auto' | 'low' | 'high';
                  };
                }
            >;
        /**
         * Run ID associated with this message
         */
        runId?: string | null;
        /**
         * Additional message metadata
         */
        additionalKwargs?: {
          [key: string]: unknown;
        };
      }
    | {
        /**
         * Message role
         */
        role: 'ai';
        /**
         * Message content
         */
        content: string;
        /**
         * Message ID
         */
        id?: string;
        /**
         * Run ID associated with this message
         */
        runId?: string | null;
        /**
         * Tool calls in the message
         */
        toolCalls?: Array<{
          /**
           * Tool name
           */
          name: string;
          /**
           * Tool arguments
           */
          args: {
            [key: string]: unknown;
          };
          /**
           * Tool call type
           */
          type: string;
          /**
           * Tool call ID
           */
          id: string;
          /**
           * Optional human-readable tool call title
           */
          title?: string;
        }>;
        /**
         * Additional message metadata
         */
        additionalKwargs?: {
          [key: string]: unknown;
        };
      }
    | {
        /**
         * Message ID
         */
        id?: string;
        /**
         * Message role
         */
        role: 'reasoning';
        /**
         * Reasoning trace emitted by the model
         */
        content: string;
        /**
         * Run ID associated with this message
         */
        runId?: string | null;
        /**
         * Additional message metadata
         */
        additionalKwargs?: {
          [key: string]: unknown;
        };
      }
    | {
        /**
         * Message role
         */
        role: 'system';
        /**
         * Message content
         */
        content: string;
        /**
         * Run ID associated with this message
         */
        runId?: string | null;
        /**
         * Additional message metadata
         */
        additionalKwargs?: {
          [key: string]: unknown;
        };
      }
    | {
        /**
         * Message role
         */
        role: 'tool';
        /**
         * Tool name
         */
        name: string;
        /**
         * Parsed tool result as JSON
         */
        content: {
          [key: string]: unknown;
        };
        /**
         * Tool call ID
         */
        toolCallId: string;
        /**
         * Run ID associated with this message
         */
        runId?: string | null;
        /**
         * Optional human-readable tool call title
         */
        title?: string;
        /**
         * Additional message metadata
         */
        additionalKwargs?: {
          [key: string]: unknown;
        };
      };
  /**
   * Full LLM request token usage & cost (entire request, not just this message)
   */
  requestTokenUsage?: {
    /**
     * Input tokens
     */
    inputTokens: number;
    /**
     * Cached input tokens
     */
    cachedInputTokens?: number;
    /**
     * Output tokens
     */
    outputTokens: number;
    /**
     * Reasoning tokens
     */
    reasoningTokens?: number;
    /**
     * Total tokens
     */
    totalTokens: number;
    /**
     * Total price in USD
     */
    totalPrice?: number;
    /**
     * Current context size in tokens (snapshot, not additive)
     */
    currentContext?: number;
  } | null;
  /**
   * Tool's own execution token cost (e.g. subagent aggregate tokens). Only present on tool result messages.
   */
  toolTokenUsage?: {
    /**
     * Input tokens
     */
    inputTokens: number;
    /**
     * Cached input tokens
     */
    cachedInputTokens?: number;
    /**
     * Output tokens
     */
    outputTokens: number;
    /**
     * Reasoning tokens
     */
    reasoningTokens?: number;
    /**
     * Total tokens
     */
    totalTokens: number;
    /**
     * Total price in USD
     */
    totalPrice?: number;
    /**
     * Current context size in tokens (snapshot, not additive)
     */
    currentContext?: number;
  } | null;
};

export type ThreadUsageStatisticsDtoSchema0 = {
  /**
   * Tool name
   */
  toolName: string;
  /**
   * Total tokens from LLM requests related to this tool
   */
  totalTokens: number;
  /**
   * Total price from LLM requests related to this tool in USD
   */
  totalPrice?: number;
  /**
   * Number of times this tool was called
   */
  callCount: number;
  /**
   * Tool's own execution token cost (e.g. subagent aggregate tokens)
   */
  toolTokens?: number;
  /**
   * Tool's own execution price in USD
   */
  toolPrice?: number;
  /**
   * Sub-tool calls made within this tool (e.g. tools called by a subagent)
   */
  subCalls?: Array<ThreadUsageStatisticsDtoSchema0>;
};

export type ThreadUsageStatisticsDto = {
  /**
   * Total usage statistics for the entire thread
   */
  total: {
    /**
     * Input tokens
     */
    inputTokens: number;
    /**
     * Cached input tokens
     */
    cachedInputTokens?: number;
    /**
     * Output tokens
     */
    outputTokens: number;
    /**
     * Reasoning tokens
     */
    reasoningTokens?: number;
    /**
     * Total tokens
     */
    totalTokens: number;
    /**
     * Total price in USD
     */
    totalPrice?: number;
    /**
     * Current context size in tokens (snapshot, not additive)
     */
    currentContext?: number;
  };
  /**
   * Total number of requests (messages with requestTokenUsage)
   */
  requests: number;
  /**
   * Usage statistics breakdown by node ID
   */
  byNode: {
    [key: string]: {
      /**
       * Input tokens
       */
      inputTokens: number;
      /**
       * Cached input tokens
       */
      cachedInputTokens?: number;
      /**
       * Output tokens
       */
      outputTokens: number;
      /**
       * Reasoning tokens
       */
      reasoningTokens?: number;
      /**
       * Total tokens
       */
      totalTokens: number;
      /**
       * Total price in USD
       */
      totalPrice?: number;
      /**
       * Current context size in tokens (snapshot, not additive)
       */
      currentContext?: number;
    };
  };
  /**
   * Usage statistics breakdown by tool name
   */
  byTool: Array<ThreadUsageStatisticsDtoSchema0>;
  /**
   * Aggregated statistics for all tool-related LLM requests
   */
  toolsAggregate: {
    /**
     * Input tokens
     */
    inputTokens: number;
    /**
     * Cached input tokens
     */
    cachedInputTokens?: number;
    /**
     * Output tokens
     */
    outputTokens: number;
    /**
     * Reasoning tokens
     */
    reasoningTokens?: number;
    /**
     * Total tokens
     */
    totalTokens: number;
    /**
     * Total price in USD
     */
    totalPrice?: number;
    /**
     * Current context size in tokens (snapshot, not additive)
     */
    currentContext?: number;
    /**
     * Number of requests (messages with requestTokenUsage)
     */
    requestCount: number;
  };
  /**
   * Number of user (human) messages in the thread
   */
  userMessageCount: number;
  /**
   * Distinct LLM model identifiers used across all messages in the thread
   */
  modelsUsed: Array<string>;
};

export type SetThreadMetadataDto = {
  /**
   * Thread metadata to set (replaces existing metadata)
   */
  metadata: {
    [key: string]: unknown;
  };
};

export type ResumeThreadDto = {
  /**
   * Optional message to inject instead of the stored checkPrompt
   */
  message?: string;
};

export type CreateSecretDto = {
  name: string;
  value: string;
  description?: string | null;
};

export type SecretResponseDto = {
  id: string;
  name: string;
  description?: string | null;
  projectId: string;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
};

export type UpdateSecretDto = {
  value?: string;
  description?: string | null;
};

export type CreateGraphDto = {
  name: string;
  description?: string | null;
  schema: {
    nodes: Array<{
      /**
       * Unique identifier for this node
       */
      id: string;
      /**
       * Template id registered in TemplateRegistry
       */
      template: string;
      /**
       * Template-specific configuration
       */
      config: {
        [key: string]: unknown;
      };
    }>;
    edges?: Array<{
      /**
       * Source node ID
       */
      from: string;
      /**
       * Target node ID
       */
      to: string;
      /**
       * Optional edge label
       */
      label?: string;
    }>;
  };
  metadata?: {
    /**
     * Node coordinates and names by node ID
     */
    nodes?: Array<{
      id: string;
      /**
       * X coordinate of the node
       */
      x?: number;
      /**
       * Y coordinate of the node
       */
      y?: number;
      /**
       * Optional display name for the node
       */
      name?: string;
    }>;
    /**
     * Zoom level for graph display
     */
    zoom?: number;
    /**
     * X coordinate
     */
    x?: number;
    /**
     * Y coordinate
     */
    y?: number;
    [key: string]: unknown;
  } | null;
  /**
   * If true, graph will be deleted instead of restored after server restart
   */
  temporary?: boolean | null;
  /**
   * Optional cost limit in USD projected from settings.costLimitUsd
   */
  costLimitUsd?: number | null;
};

export type GraphDto = {
  id: string;
  name: string;
  description?: string | null;
  error?: string | null;
  version: string;
  /**
   * Target version after all queued revisions are applied
   */
  targetVersion: string;
  schema: {
    nodes: Array<{
      /**
       * Unique identifier for this node
       */
      id: string;
      /**
       * Template id registered in TemplateRegistry
       */
      template: string;
      /**
       * Template-specific configuration
       */
      config: {
        [key: string]: unknown;
      };
    }>;
    edges?: Array<{
      /**
       * Source node ID
       */
      from: string;
      /**
       * Target node ID
       */
      to: string;
      /**
       * Optional edge label
       */
      label?: string;
    }>;
  };
  status: 'created' | 'compiling' | 'running' | 'stopped' | 'error';
  metadata?: {
    /**
     * Node coordinates and names by node ID
     */
    nodes?: Array<{
      id: string;
      /**
       * X coordinate of the node
       */
      x?: number;
      /**
       * Y coordinate of the node
       */
      y?: number;
      /**
       * Optional display name for the node
       */
      name?: string;
    }>;
    /**
     * Zoom level for graph display
     */
    zoom?: number;
    /**
     * X coordinate
     */
    x?: number;
    /**
     * Y coordinate
     */
    y?: number;
    [key: string]: unknown;
  } | null;
  /**
   * Number of threads currently in running state
   */
  runningThreads?: number;
  /**
   * Total number of threads for this graph
   */
  totalThreads?: number;
  createdAt: string;
  updatedAt: string;
  /**
   * If true, graph will be deleted instead of restored after server restart
   */
  temporary?: boolean | null;
  /**
   * Project this graph belongs to
   */
  projectId?: string | null;
  /**
   * Arbitrary per-graph settings stored as JSONB
   */
  settings?: {
    [key: string]: unknown;
  };
  /**
   * Optional cost limit in USD projected from settings.costLimitUsd
   */
  costLimitUsd?: number | null;
};

export type GraphPreviewDto = {
  id: string;
  name: string;
  description?: string | null;
  error?: string | null;
  version: string;
  /**
   * Target version after all queued revisions are applied
   */
  targetVersion: string;
  status: 'created' | 'compiling' | 'running' | 'stopped' | 'error';
  runningThreads?: number;
  totalThreads?: number;
  /**
   * Number of nodes in the graph schema
   */
  nodeCount?: number;
  /**
   * Number of edges in the graph schema
   */
  edgeCount?: number;
  /**
   * Agent nodes present in the graph
   */
  agents?: Array<{
    nodeId: string;
    name: string;
    description?: string;
  }>;
  /**
   * Pre-computed trigger nodes from schema
   */
  triggerNodes: Array<{
    /**
     * Node ID
     */
    id: string;
    /**
     * Display name (from metadata or template name)
     */
    name: string;
    /**
     * Template identifier
     */
    template: string;
  }>;
  /**
   * Pre-computed node display names from metadata
   */
  nodeDisplayNames: {
    [key: string]: string;
  };
  createdAt: string;
  updatedAt: string;
  temporary?: boolean | null;
  projectId?: string | null;
  /**
   * Optional cost limit in USD projected from settings.costLimitUsd
   */
  costLimitUsd?: number | null;
};

export type GraphNodeWithStatusDto = {
  /**
   * Node ID
   */
  id: string;
  /**
   * Display name for node
   */
  name: string;
  /**
   * Template identifier
   */
  template: string;
  /**
   * Node kind
   */
  type:
    | 'runtime'
    | 'tool'
    | 'simpleAgent'
    | 'claudeAgent'
    | 'trigger'
    | 'resource'
    | 'mcp'
    | 'instruction';
  /**
   * Current node status
   */
  status: 'stopped' | 'starting' | 'running' | 'idle';
  /**
   * Node configuration
   */
  config: unknown;
  /**
   * Last error message
   */
  error?: string | null;
  metadata?: {
    threadId?: string;
    runId?: string;
    parentThreadId?: string;
  };
  /**
   * Additional metadata exposed by the node implementation
   */
  additionalNodeMetadata?: {
    [key: string]: unknown;
  };
};

export type UpdateGraphDto = {
  name?: string;
  description?: string | null;
  schema?: {
    nodes: Array<{
      /**
       * Unique identifier for this node
       */
      id: string;
      /**
       * Template id registered in TemplateRegistry
       */
      template: string;
      /**
       * Template-specific configuration
       */
      config: {
        [key: string]: unknown;
      };
    }>;
    edges?: Array<{
      /**
       * Source node ID
       */
      from: string;
      /**
       * Target node ID
       */
      to: string;
      /**
       * Optional edge label
       */
      label?: string;
    }>;
  };
  metadata?: {
    /**
     * Node coordinates and names by node ID
     */
    nodes?: Array<{
      id: string;
      /**
       * X coordinate of the node
       */
      x?: number;
      /**
       * Y coordinate of the node
       */
      y?: number;
      /**
       * Optional display name for the node
       */
      name?: string;
    }>;
    /**
     * Zoom level for graph display
     */
    zoom?: number;
    /**
     * X coordinate
     */
    x?: number;
    /**
     * Y coordinate
     */
    y?: number;
    [key: string]: unknown;
  } | null;
  /**
   * If true, graph will be deleted instead of restored after server restart
   */
  temporary?: boolean | null;
  /**
   * Optional cost limit in USD projected from settings.costLimitUsd
   */
  costLimitUsd?: number | null;
  /**
   * Current version of the graph (for optimistic locking and 3-way merge base)
   */
  currentVersion: string;
};

export type UpdateGraphResponseDto = {
  /**
   * Updated graph
   */
  graph: {
    id: string;
    name: string;
    description?: string | null;
    error?: string | null;
    version: string;
    /**
     * Target version after all queued revisions are applied
     */
    targetVersion: string;
    schema: {
      nodes: Array<{
        /**
         * Unique identifier for this node
         */
        id: string;
        /**
         * Template id registered in TemplateRegistry
         */
        template: string;
        /**
         * Template-specific configuration
         */
        config: {
          [key: string]: unknown;
        };
      }>;
      edges?: Array<{
        /**
         * Source node ID
         */
        from: string;
        /**
         * Target node ID
         */
        to: string;
        /**
         * Optional edge label
         */
        label?: string;
      }>;
    };
    status: 'created' | 'compiling' | 'running' | 'stopped' | 'error';
    metadata?: {
      /**
       * Node coordinates and names by node ID
       */
      nodes?: Array<{
        id: string;
        /**
         * X coordinate of the node
         */
        x?: number;
        /**
         * Y coordinate of the node
         */
        y?: number;
        /**
         * Optional display name for the node
         */
        name?: string;
      }>;
      /**
       * Zoom level for graph display
       */
      zoom?: number;
      /**
       * X coordinate
       */
      x?: number;
      /**
       * Y coordinate
       */
      y?: number;
      [key: string]: unknown;
    } | null;
    /**
     * Number of threads currently in running state
     */
    runningThreads?: number;
    /**
     * Total number of threads for this graph
     */
    totalThreads?: number;
    createdAt: string;
    updatedAt: string;
    /**
     * If true, graph will be deleted instead of restored after server restart
     */
    temporary?: boolean | null;
    /**
     * Project this graph belongs to
     */
    projectId?: string | null;
    /**
     * Arbitrary per-graph settings stored as JSONB
     */
    settings?: {
      [key: string]: unknown;
    };
    /**
     * Optional cost limit in USD projected from settings.costLimitUsd
     */
    costLimitUsd?: number | null;
  };
  /**
   * Created revision if update required applying non-metadata changes
   */
  revision?: {
    id: string;
    graphId: string;
    /**
     * Version the client changes were based on
     */
    baseVersion: string;
    /**
     * New head version after this revision
     */
    toVersion: string;
    /**
     * JSON Patch (RFC 6902) operations between old and new schemas
     */
    configDiff: Array<
      | {
          op: 'add';
          path: string;
          value: unknown;
        }
      | {
          op: 'remove';
          path: string;
        }
      | {
          op: 'replace';
          path: string;
          value: unknown;
        }
      | {
          op: 'move';
          from: string;
          path: string;
        }
      | {
          op: 'copy';
          from: string;
          path: string;
        }
      | {
          op: 'test';
          path: string;
          value: unknown;
        }
    >;
    /**
     * Config submitted by the client
     */
    clientConfig: {
      schema: {
        nodes: Array<{
          /**
           * Unique identifier for this node
           */
          id: string;
          /**
           * Template id registered in TemplateRegistry
           */
          template: string;
          /**
           * Template-specific configuration
           */
          config: {
            [key: string]: unknown;
          };
        }>;
        edges?: Array<{
          /**
           * Source node ID
           */
          from: string;
          /**
           * Target node ID
           */
          to: string;
          /**
           * Optional edge label
           */
          label?: string;
        }>;
      };
      name: string;
      description: string | null;
      temporary: boolean;
    };
    /**
     * Merged config result
     */
    newConfig: {
      schema: {
        nodes: Array<{
          /**
           * Unique identifier for this node
           */
          id: string;
          /**
           * Template id registered in TemplateRegistry
           */
          template: string;
          /**
           * Template-specific configuration
           */
          config: {
            [key: string]: unknown;
          };
        }>;
        edges?: Array<{
          /**
           * Source node ID
           */
          from: string;
          /**
           * Target node ID
           */
          to: string;
          /**
           * Optional edge label
           */
          label?: string;
        }>;
      };
      name: string;
      description: string | null;
      temporary: boolean;
    };
    status: 'pending' | 'applying' | 'applied' | 'failed';
    error?: string;
    createdAt: string;
    updatedAt: string;
  } | null;
};

export type ExecuteTriggerDto = {
  /**
   * Array of messages — plain strings or structured objects with content blocks
   */
  messages: Array<
    | string
    | {
        /**
         * Content blocks for multimodal messages
         */
        content: Array<
          | {
              type: 'text';
              /**
               * Text content
               */
              text: string;
            }
          | {
              type: 'image_url';
              image_url: {
                /**
                 * Base64 data URL (data:image/...;base64,...)
                 */
                url: string;
                /**
                 * Vision detail level
                 */
                detail?: 'auto' | 'low' | 'high';
              };
            }
        >;
      }
  >;
  /**
   * Optional thread sub-ID that will be used to create the full thread ID.
   */
  threadSubId?: string;
  /**
   * If true, do not wait for execution to finish (fire-and-forget).
   */
  async?: boolean;
  /**
   * Optional metadata to attach to the thread created by this execution.
   */
  metadata?: {
    [key: string]: unknown;
  };
};

export type ExecuteTriggerResponseDto = {
  /**
   * The thread ID used for this execution
   */
  externalThreadId: string;
  /**
   * The checkpoint namespace for this execution
   */
  checkpointNs?: string;
};

export type GraphRevisionDto = {
  id: string;
  graphId: string;
  /**
   * Version the client changes were based on
   */
  baseVersion: string;
  /**
   * New head version after this revision
   */
  toVersion: string;
  /**
   * JSON Patch (RFC 6902) operations between old and new schemas
   */
  configDiff: Array<
    | {
        op: 'add';
        path: string;
        value: unknown;
      }
    | {
        op: 'remove';
        path: string;
      }
    | {
        op: 'replace';
        path: string;
        value: unknown;
      }
    | {
        op: 'move';
        from: string;
        path: string;
      }
    | {
        op: 'copy';
        from: string;
        path: string;
      }
    | {
        op: 'test';
        path: string;
        value: unknown;
      }
  >;
  /**
   * Config submitted by the client
   */
  clientConfig: {
    schema: {
      nodes: Array<{
        /**
         * Unique identifier for this node
         */
        id: string;
        /**
         * Template id registered in TemplateRegistry
         */
        template: string;
        /**
         * Template-specific configuration
         */
        config: {
          [key: string]: unknown;
        };
      }>;
      edges?: Array<{
        /**
         * Source node ID
         */
        from: string;
        /**
         * Target node ID
         */
        to: string;
        /**
         * Optional edge label
         */
        label?: string;
      }>;
    };
    name: string;
    description: string | null;
    temporary: boolean;
  };
  /**
   * Merged config result
   */
  newConfig: {
    schema: {
      nodes: Array<{
        /**
         * Unique identifier for this node
         */
        id: string;
        /**
         * Template id registered in TemplateRegistry
         */
        template: string;
        /**
         * Template-specific configuration
         */
        config: {
          [key: string]: unknown;
        };
      }>;
      edges?: Array<{
        /**
         * Source node ID
         */
        from: string;
        /**
         * Target node ID
         */
        to: string;
        /**
         * Optional edge label
         */
        label?: string;
      }>;
    };
    name: string;
    description: string | null;
    temporary: boolean;
  };
  status: 'pending' | 'applying' | 'applied' | 'failed';
  error?: string;
  createdAt: string;
  updatedAt: string;
};

export type TemplateDto = {
  id: string;
  name: string;
  description: string;
  kind:
    | 'runtime'
    | 'tool'
    | 'simpleAgent'
    | 'claudeAgent'
    | 'trigger'
    | 'resource'
    | 'mcp'
    | 'instruction';
  schema: {
    [key: string]: unknown;
  };
  inputs?: Array<
    | {
        type: 'kind';
        value:
          | 'runtime'
          | 'tool'
          | 'simpleAgent'
          | 'claudeAgent'
          | 'trigger'
          | 'resource'
          | 'mcp'
          | 'instruction';
        required?: boolean;
        requiredGroup?: string;
        multiple: boolean;
      }
    | {
        type: 'template';
        value: string;
        required?: boolean;
        requiredGroup?: string;
        multiple: boolean;
      }
  >;
  outputs?: Array<
    | {
        type: 'kind';
        value:
          | 'runtime'
          | 'tool'
          | 'simpleAgent'
          | 'claudeAgent'
          | 'trigger'
          | 'resource'
          | 'mcp'
          | 'instruction';
        required?: boolean;
        requiredGroup?: string;
        multiple: boolean;
      }
    | {
        type: 'template';
        value: string;
        required?: boolean;
        requiredGroup?: string;
        multiple: boolean;
      }
  >;
  systemAgentId?: string;
  systemAgentContentHash?: string;
  systemAgentPredefinedTools?: Array<string>;
  instructionBlockId?: string;
  instructionBlockContentHash?: string;
};

export type SuggestAgentInstructionsDto = {
  /**
   * User request describing how to adjust agent instructions
   */
  userRequest: string;
  /**
   * Optional thread id to continue a previous suggestion conversation
   */
  threadId?: string;
  /**
   * Optional LLM model to use for this suggestion
   */
  model?: string;
};

export type SuggestAgentInstructionsResponseDto = {
  /**
   * Updated agent instructions generated by the LLM
   */
  instructions: string;
  /**
   * Thread id used for this suggestion session
   */
  threadId: string;
};

export type SuggestGraphInstructionsDto = {
  /**
   * User request describing how to adjust agent instructions
   */
  userRequest: string;
  /**
   * Optional LLM model to use for this suggestion
   */
  model?: string;
};

export type SuggestGraphInstructionsResponseDto = {
  /**
   * Only agents with changed instructions are returned
   */
  updates: Array<{
    /**
     * Agent node id
     */
    nodeId: string;
    /**
     * Agent display name
     */
    name?: string;
    /**
     * Updated agent instructions generated by the LLM
     */
    instructions: string;
  }>;
};

export type ThreadAnalysisRequestDto = {
  /**
   * Optional user-provided input to guide the analysis
   */
  userInput?: string;
  /**
   * Optional LLM conversation id to continue the existing suggestion thread
   */
  threadId?: string;
  /**
   * Optional LLM model to use for this analysis
   */
  model?: string;
};

export type ThreadAnalysisResponseDto = {
  /**
   * LLM-generated analysis and improvement suggestions
   */
  analysis: string;
  /**
   * Identifier of the LLM conversation used for the analysis
   */
  conversationId: string;
};

export type KnowledgeContentSuggestionRequestDto = {
  /**
   * User request describing knowledge content to create or improve
   */
  userRequest: string;
  /**
   * Optional existing knowledge document title
   */
  currentTitle?: string;
  /**
   * Optional existing knowledge document content
   */
  currentContent?: string;
  /**
   * Optional existing tags for the knowledge document
   */
  currentTags?: Array<string>;
  /**
   * Optional thread id to continue a previous suggestion conversation
   */
  threadId?: string;
  /**
   * Optional LLM model to use for this suggestion
   */
  model?: string;
};

export type KnowledgeContentSuggestionResponseDto = {
  /**
   * Suggested knowledge document title
   */
  title: string;
  /**
   * Suggested knowledge document content
   */
  content: string;
  /**
   * Suggested tags for the knowledge document
   */
  tags?: Array<string>;
  /**
   * Thread id used for this suggestion session
   */
  threadId: string;
};

export type AnalyticsOverviewDto = {
  /**
   * Total number of threads
   */
  totalThreads: number;
  /**
   * Sum of input tokens
   */
  inputTokens: number;
  /**
   * Sum of cached input tokens
   */
  cachedInputTokens: number;
  /**
   * Sum of output tokens
   */
  outputTokens: number;
  /**
   * Sum of reasoning tokens
   */
  reasoningTokens: number;
  /**
   * Sum of all tokens
   */
  totalTokens: number;
  /**
   * Total cost in USD
   */
  totalPrice: number;
};

export type AnalyticsByGraphResponseDto = {
  graphs: Array<{
    /**
     * Total number of threads
     */
    totalThreads: number;
    /**
     * Sum of input tokens
     */
    inputTokens: number;
    /**
     * Sum of cached input tokens
     */
    cachedInputTokens: number;
    /**
     * Sum of output tokens
     */
    outputTokens: number;
    /**
     * Sum of reasoning tokens
     */
    reasoningTokens: number;
    /**
     * Sum of all tokens
     */
    totalTokens: number;
    /**
     * Total cost in USD
     */
    totalPrice: number;
    /**
     * Graph ID
     */
    graphId: string;
    /**
     * Graph name
     */
    graphName: string;
  }>;
};

export type SystemAgentResponseDto = {
  id: string;
  templateId: string;
  name: string;
  description: string;
  tools: Array<string>;
  defaultModel: string | null;
  instructions: string;
  contentHash: string;
};

export type InstructionBlockResponseDto = {
  id: string;
  templateId: string;
  name: string;
  description: string;
  instructions: string;
  contentHash: string;
};

export type OAuthStartResponseDto = {
  /**
   * Provider authorize URL to navigate the new tab to
   */
  authorizeUrl: string;
};

export type OAuthStatusResponseDto = {
  provider: 'linear';
  /**
   * Whether a valid credential exists for this project + provider
   */
  authenticated: boolean;
  accountLabel: string | null;
  secretName: string | null;
};

export type OAuthExchangeRequestDto = {
  provider: 'linear';
  code: string;
  state: string;
};

export type OAuthExchangeResponseDto = {
  provider: 'linear';
  authenticated: true;
  accountLabel: string;
  secretName: string;
};

export type SystemSettingsResponseDto = {
  /**
   * Whether the GitHub App integration is configured and available
   */
  githubAppEnabled: boolean;
  /**
   * Whether the LiteLLM model management UI is enabled for the frontend
   */
  litellmManagementEnabled: boolean;
  /**
   * Whether the current user has the admin role
   */
  isAdmin: boolean;
  /**
   * Whether the GitHub webhook receiver is configured and available
   */
  githubWebhookEnabled: boolean;
  /**
   * Current API server version
   */
  apiVersion: string;
  /**
   * Current web client version
   */
  webVersion: string;
};

export type AuthConfigResponseDto = {
  /**
   * Active auth provider
   */
  provider: 'keycloak' | 'zitadel';
  /**
   * Token issuer URL
   */
  issuer: string;
  /**
   * OAuth client ID for the auth provider
   */
  clientId: string;
};

export type CheckHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/runtimes/health';
};

export type CheckHealthResponses = {
  200: RuntimeHealthDto;
};

export type CheckHealthResponse =
  CheckHealthResponses[keyof CheckHealthResponses];

export type GetRuntimesData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Filter by thread ID
     */
    threadId: string;
    /**
     * Filter by runtime instance status
     */
    status?: 'Starting' | 'Running' | 'Stopping' | 'Stopped' | 'Failed';
  };
  url: '/api/v1/runtimes';
};

export type GetRuntimesResponses = {
  200: Array<RuntimeInstanceDto>;
};

export type GetRuntimesResponse =
  GetRuntimesResponses[keyof GetRuntimesResponses];

export type GetRuntimeStateData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/runtimes/{id}/state';
};

export type GetRuntimeStateResponses = {
  200: RuntimeInstanceStateDto;
};

export type GetRuntimeStateResponse =
  GetRuntimeStateResponses[keyof GetRuntimeStateResponses];

export type GetRepositoriesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Filter by repository owner
     */
    owner?: string;
    /**
     * Filter by repository name
     */
    repo?: string;
    /**
     * Filter by host provider
     */
    provider?: 'GITHUB';
    /**
     * Filter by GitHub App installation ID
     */
    installationId?: number;
    /**
     * Maximum number of repositories to return
     */
    limit?: number;
    /**
     * Number of repositories to skip
     */
    offset?: number;
  };
  url: '/api/v1/git-repositories';
};

export type GetRepositoriesResponses = {
  200: Array<GitRepositoryDto>;
};

export type GetRepositoriesResponse =
  GetRepositoriesResponses[keyof GetRepositoriesResponses];

export type CreateRepositoryData = {
  body: CreateRepositoryDto;
  path?: never;
  query?: never;
  url: '/api/v1/git-repositories';
};

export type CreateRepositoryResponses = {
  201: GitRepositoryDto;
};

export type CreateRepositoryResponse =
  CreateRepositoryResponses[keyof CreateRepositoryResponses];

export type GetRepoIndexesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Filter by repository ID
     */
    repositoryId?: string;
    /**
     * Filter by single branch name
     */
    branch?: string;
    /**
     * Filter by multiple branch names (comma-separated or repeated query param)
     */
    branches?: string | Array<string>;
    /**
     * Filter by status
     */
    status?: 'pending' | 'in_progress' | 'completed' | 'failed';
    /**
     * Maximum number of indexes to return
     */
    limit?: number;
    /**
     * Number of indexes to skip
     */
    offset?: number;
  };
  url: '/api/v1/git-repositories/indexes';
};

export type GetRepoIndexesResponses = {
  200: Array<RepoIndexDto>;
};

export type GetRepoIndexesResponse =
  GetRepoIndexesResponses[keyof GetRepoIndexesResponses];

export type SyncRepositoriesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/git-repositories/sync';
};

export type SyncRepositoriesResponses = {
  201: SyncRepositoriesResponseDto;
};

export type SyncRepositoriesResponse =
  SyncRepositoriesResponses[keyof SyncRepositoriesResponses];

export type DeleteRepositoryData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/git-repositories/{id}';
};

export type DeleteRepositoryResponses = {
  200: unknown;
};

export type GetRepositoryByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/git-repositories/{id}';
};

export type GetRepositoryByIdResponses = {
  200: GitRepositoryDto;
};

export type GetRepositoryByIdResponse =
  GetRepositoryByIdResponses[keyof GetRepositoryByIdResponses];

export type UpdateRepositoryData = {
  body: UpdateRepositoryDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/git-repositories/{id}';
};

export type UpdateRepositoryResponses = {
  200: GitRepositoryDto;
};

export type UpdateRepositoryResponse =
  UpdateRepositoryResponses[keyof UpdateRepositoryResponses];

export type GetRepoIndexByRepositoryIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: {
    /**
     * Optional branch name to filter repo indexes
     */
    branch?: string;
  };
  url: '/api/v1/git-repositories/{id}/index';
};

export type GetRepoIndexByRepositoryIdResponses = {
  200: RepoIndexDto;
};

export type GetRepoIndexByRepositoryIdResponse =
  GetRepoIndexByRepositoryIdResponses[keyof GetRepoIndexByRepositoryIdResponses];

export type TriggerReindexData = {
  body: TriggerReindexDto;
  path?: never;
  query?: never;
  url: '/api/v1/git-repositories/reindex';
};

export type TriggerReindexResponses = {
  201: TriggerReindexResponseDto;
};

export type TriggerReindexResponse =
  TriggerReindexResponses[keyof TriggerReindexResponses];

export type ListModelsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/litellm/models';
};

export type ListModelsResponses = {
  200: Array<LiteLlmModelDto>;
};

export type ListModelsResponse = ListModelsResponses[keyof ListModelsResponses];

export type UpdateModelData = {
  body: UpdateLiteLlmModelDto;
  path?: never;
  query?: never;
  url: '/api/v1/litellm/models';
};

export type UpdateModelResponses = {
  200: unknown;
};

export type CreateModelData = {
  body: CreateLiteLlmModelDto;
  path?: never;
  query?: never;
  url: '/api/v1/litellm/models';
};

export type CreateModelResponses = {
  201: unknown;
};

export type GetModelDefaultsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/litellm/model-defaults';
};

export type GetModelDefaultsResponses = {
  200: ModelDefaultsDto;
};

export type GetModelDefaultsResponse =
  GetModelDefaultsResponses[keyof GetModelDefaultsResponses];

export type ListModelsInfoData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/litellm/models/info';
};

export type ListModelsInfoResponses = {
  200: Array<LiteLlmModelInfoItemDto>;
};

export type ListModelsInfoResponse =
  ListModelsInfoResponses[keyof ListModelsInfoResponses];

export type TestModelData = {
  body: TestModelRequestDto;
  path?: never;
  query?: never;
  url: '/api/v1/litellm/models/test';
};

export type TestModelResponses = {
  200: TestModelResponseDto;
};

export type TestModelResponse = TestModelResponses[keyof TestModelResponses];

export type TestModelConnectionData = {
  body: TestModelConnectionDto;
  path?: never;
  query?: never;
  url: '/api/v1/litellm/models/test-connection';
};

export type TestModelConnectionResponses = {
  200: TestModelResponseDto;
};

export type TestModelConnectionResponse =
  TestModelConnectionResponses[keyof TestModelConnectionResponses];

export type DeleteModelData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/litellm/models/{id}';
};

export type DeleteModelResponses = {
  200: unknown;
};

export type ListProvidersData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/litellm/providers';
};

export type ListProvidersResponses = {
  200: LiteLlmProvidersResponseDto;
};

export type ListProvidersResponse =
  ListProvidersResponses[keyof ListProvidersResponses];

export type ListCredentialsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/litellm/credentials';
};

export type ListCredentialsResponses = {
  200: LiteLlmCredentialsResponseDto;
};

export type ListCredentialsResponse =
  ListCredentialsResponses[keyof ListCredentialsResponses];

export type CreateCredentialData = {
  body: CreateLiteLlmCredentialDto;
  path?: never;
  query?: never;
  url: '/api/v1/litellm/credentials';
};

export type CreateCredentialResponses = {
  201: unknown;
};

export type DeleteCredentialData = {
  body?: never;
  path: {
    name: string;
  };
  query?: never;
  url: '/api/v1/litellm/credentials/{name}';
};

export type DeleteCredentialResponses = {
  200: unknown;
};

export type GetPreferencesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/user-preferences';
};

export type GetPreferencesResponses = {
  200: UserPreferencesDto;
};

export type GetPreferencesResponse =
  GetPreferencesResponses[keyof GetPreferencesResponses];

export type UpdatePreferencesData = {
  body: UpdateUserPreferencesDto;
  path?: never;
  query?: never;
  url: '/api/v1/user-preferences';
};

export type UpdatePreferencesResponses = {
  200: UserPreferencesDto;
};

export type UpdatePreferencesResponse =
  UpdatePreferencesResponses[keyof UpdatePreferencesResponses];

export type GetAllProjectsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/projects';
};

export type GetAllProjectsResponses = {
  200: Array<ProjectDto>;
};

export type GetAllProjectsResponse =
  GetAllProjectsResponses[keyof GetAllProjectsResponses];

export type CreateProjectData = {
  body: CreateProjectDto;
  path?: never;
  query?: never;
  url: '/api/v1/projects';
};

export type CreateProjectResponses = {
  201: ProjectDto;
};

export type CreateProjectResponse =
  CreateProjectResponses[keyof CreateProjectResponses];

export type DeleteProjectData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/projects/{id}';
};

export type DeleteProjectResponses = {
  204: void;
};

export type DeleteProjectResponse =
  DeleteProjectResponses[keyof DeleteProjectResponses];

export type FindProjectByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/projects/{id}';
};

export type FindProjectByIdResponses = {
  200: ProjectDto;
};

export type FindProjectByIdResponse =
  FindProjectByIdResponses[keyof FindProjectByIdResponses];

export type UpdateProjectData = {
  body: UpdateProjectDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/projects/{id}';
};

export type UpdateProjectResponses = {
  200: ProjectDto;
};

export type UpdateProjectResponse =
  UpdateProjectResponses[keyof UpdateProjectResponses];

export type GetSetupInfoData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/git-auth/github/setup';
};

export type GetSetupInfoResponses = {
  200: SetupInfoResponseDto;
};

export type GetSetupInfoResponse =
  GetSetupInfoResponses[keyof GetSetupInfoResponses];

export type LinkViaOAuthCodeData = {
  body: OAuthLinkRequestDto;
  path?: never;
  query?: never;
  url: '/api/v1/git-auth/github/oauth/link';
};

export type LinkViaOAuthCodeResponses = {
  201: LinkInstallationResponseDto;
};

export type LinkViaOAuthCodeResponse =
  LinkViaOAuthCodeResponses[keyof LinkViaOAuthCodeResponses];

export type ListInstallationsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/git-auth/github/installations';
};

export type ListInstallationsResponses = {
  200: ListInstallationsResponseDto;
};

export type ListInstallationsResponse =
  ListInstallationsResponses[keyof ListInstallationsResponses];

export type UnlinkInstallationData = {
  body?: never;
  path: {
    installationId: string;
  };
  query?: never;
  url: '/api/v1/git-auth/github/installations/{installationId}';
};

export type UnlinkInstallationResponses = {
  200: UnlinkInstallationResponseDto;
};

export type UnlinkInstallationResponse =
  UnlinkInstallationResponses[keyof UnlinkInstallationResponses];

export type DisconnectAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/git-auth/github/disconnect';
};

export type DisconnectAllResponses = {
  200: UnlinkInstallationResponseDto;
};

export type DisconnectAllResponse =
  DisconnectAllResponses[keyof DisconnectAllResponses];

export type ListDocsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Filter by tags (match any)
     */
    tags?: Array<string>;
    /**
     * Search in title/summary/content
     */
    search?: string;
    limit?: number;
    offset?: number;
  };
  url: '/api/v1/knowledge-docs';
};

export type ListDocsResponses = {
  200: KnowledgeDocListResultDto;
};

export type ListDocsResponse = ListDocsResponses[keyof ListDocsResponses];

export type CreateDocData = {
  body: KnowledgeDocCreateDto;
  path?: never;
  query?: never;
  url: '/api/v1/knowledge-docs';
};

export type CreateDocResponses = {
  201: KnowledgeDocDto;
};

export type CreateDocResponse = CreateDocResponses[keyof CreateDocResponses];

export type DeleteDocData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/knowledge-docs/{id}';
};

export type DeleteDocResponses = {
  204: void;
};

export type DeleteDocResponse = DeleteDocResponses[keyof DeleteDocResponses];

export type GetDocData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/knowledge-docs/{id}';
};

export type GetDocResponses = {
  200: KnowledgeDocDto;
};

export type GetDocResponse = GetDocResponses[keyof GetDocResponses];

export type UpdateDocData = {
  body: KnowledgeDocUpdateDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/knowledge-docs/{id}';
};

export type UpdateDocResponses = {
  200: KnowledgeDocDto;
};

export type UpdateDocResponse = UpdateDocResponses[keyof UpdateDocResponses];

export type ListNamespacesData = {
  body?: never;
  path: {
    threadId: string;
  };
  query?: never;
  url: '/api/v1/threads/{threadId}/store';
};

export type ListNamespacesResponses = {
  200: Array<NamespaceSummaryDto>;
};

export type ListNamespacesResponse =
  ListNamespacesResponses[keyof ListNamespacesResponses];

export type ListEntriesData = {
  body?: never;
  path: {
    threadId: string;
    namespace: string;
  };
  query?: {
    limit?: number;
    offset?: number;
  };
  url: '/api/v1/threads/{threadId}/store/{namespace}';
};

export type ListEntriesResponses = {
  200: Array<ThreadStoreEntryDto>;
};

export type ListEntriesResponse =
  ListEntriesResponses[keyof ListEntriesResponses];

export type GetEntryData = {
  body?: never;
  path: {
    threadId: string;
    namespace: string;
    key: string;
  };
  query?: never;
  url: '/api/v1/threads/{threadId}/store/{namespace}/{key}';
};

export type GetEntryResponses = {
  200: ThreadStoreEntryDto;
};

export type GetEntryResponse = GetEntryResponses[keyof GetEntryResponses];

export type GetThreadsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Filter by graph ID
     */
    graphId?: string;
    /**
     * Filter by thread statuses
     */
    statuses?: Array<
      'running' | 'done' | 'need_more_info' | 'stopped' | 'waiting'
    >;
    /**
     * Maximum number of threads to return
     */
    limit?: number;
    /**
     * Number of threads to skip
     */
    offset?: number;
  };
  url: '/api/v1/threads';
};

export type GetThreadsResponses = {
  200: Array<ThreadDto>;
};

export type GetThreadsResponse = GetThreadsResponses[keyof GetThreadsResponses];

export type DeleteThreadData = {
  body?: never;
  path: {
    threadId: string;
  };
  query?: never;
  url: '/api/v1/threads/{threadId}';
};

export type DeleteThreadResponses = {
  200: unknown;
};

export type GetThreadByIdData = {
  body?: never;
  path: {
    threadId: string;
  };
  query?: never;
  url: '/api/v1/threads/{threadId}';
};

export type GetThreadByIdResponses = {
  200: ThreadDto;
};

export type GetThreadByIdResponse =
  GetThreadByIdResponses[keyof GetThreadByIdResponses];

export type GetThreadByExternalIdData = {
  body?: never;
  path: {
    externalThreadId: string;
  };
  query?: never;
  url: '/api/v1/threads/external/{externalThreadId}';
};

export type GetThreadByExternalIdResponses = {
  200: ThreadDto;
};

export type GetThreadByExternalIdResponse =
  GetThreadByExternalIdResponses[keyof GetThreadByExternalIdResponses];

export type GetThreadMessagesData = {
  body?: never;
  path: {
    threadId: string;
  };
  query?: {
    /**
     * Filter messages by node ID (agent node)
     */
    nodeId?: string;
    /**
     * Maximum number of messages to return
     */
    limit?: number;
    /**
     * Number of messages to skip
     */
    offset?: number;
  };
  url: '/api/v1/threads/{threadId}/messages';
};

export type GetThreadMessagesResponses = {
  200: Array<ThreadMessageDto>;
};

export type GetThreadMessagesResponse =
  GetThreadMessagesResponses[keyof GetThreadMessagesResponses];

export type GetThreadUsageStatisticsData = {
  body?: never;
  path: {
    threadId: string;
  };
  query?: never;
  url: '/api/v1/threads/{threadId}/usage-statistics';
};

export type GetThreadUsageStatisticsResponses = {
  200: ThreadUsageStatisticsDto;
};

export type GetThreadUsageStatisticsResponse =
  GetThreadUsageStatisticsResponses[keyof GetThreadUsageStatisticsResponses];

export type ExportThreadData = {
  body?: never;
  path: {
    threadId: string;
  };
  query?: never;
  url: '/api/v1/threads/{threadId}/export';
};

export type ExportThreadResponses = {
  /**
   * Thread export as a downloadable file.
   */
  200: unknown;
};

export type SetThreadMetadataData = {
  body: SetThreadMetadataDto;
  path: {
    threadId: string;
  };
  query?: never;
  url: '/api/v1/threads/{threadId}/metadata';
};

export type SetThreadMetadataResponses = {
  200: ThreadDto;
};

export type SetThreadMetadataResponse =
  SetThreadMetadataResponses[keyof SetThreadMetadataResponses];

export type SetThreadMetadataByExternalIdData = {
  body: SetThreadMetadataDto;
  path: {
    externalThreadId: string;
  };
  query?: never;
  url: '/api/v1/threads/external/{externalThreadId}/metadata';
};

export type SetThreadMetadataByExternalIdResponses = {
  200: ThreadDto;
};

export type SetThreadMetadataByExternalIdResponse =
  SetThreadMetadataByExternalIdResponses[keyof SetThreadMetadataByExternalIdResponses];

export type StopThreadData = {
  body?: never;
  path: {
    threadId: string;
  };
  query?: never;
  url: '/api/v1/threads/{threadId}/stop';
};

export type StopThreadResponses = {
  201: ThreadDto;
};

export type StopThreadResponse = StopThreadResponses[keyof StopThreadResponses];

export type StopThreadByExternalIdData = {
  body?: never;
  path: {
    externalThreadId: string;
  };
  query?: never;
  url: '/api/v1/threads/external/{externalThreadId}/stop';
};

export type StopThreadByExternalIdResponses = {
  201: ThreadDto;
};

export type StopThreadByExternalIdResponse =
  StopThreadByExternalIdResponses[keyof StopThreadByExternalIdResponses];

export type ResumeThreadData = {
  body: ResumeThreadDto;
  path: {
    threadId: string;
  };
  query?: never;
  url: '/api/v1/threads/{threadId}/resume';
};

export type ResumeThreadResponses = {
  201: ThreadDto;
};

export type ResumeThreadResponse =
  ResumeThreadResponses[keyof ResumeThreadResponses];

export type CancelWaitData = {
  body?: never;
  path: {
    threadId: string;
  };
  query?: never;
  url: '/api/v1/threads/{threadId}/cancel-wait';
};

export type CancelWaitResponses = {
  201: ThreadDto;
};

export type CancelWaitResponse = CancelWaitResponses[keyof CancelWaitResponses];

export type ListData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/secrets';
};

export type ListResponses = {
  200: Array<SecretResponseDto>;
};

export type ListResponse = ListResponses[keyof ListResponses];

export type CreateData = {
  body: CreateSecretDto;
  path?: never;
  query?: never;
  url: '/api/v1/secrets';
};

export type CreateResponses = {
  201: SecretResponseDto;
};

export type CreateResponse = CreateResponses[keyof CreateResponses];

export type DeleteData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/secrets/{id}';
};

export type DeleteResponses = {
  204: void;
};

export type DeleteResponse = DeleteResponses[keyof DeleteResponses];

export type GetByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/secrets/{id}';
};

export type GetByIdResponses = {
  200: SecretResponseDto;
};

export type GetByIdResponse = GetByIdResponses[keyof GetByIdResponses];

export type UpdateData = {
  body: UpdateSecretDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/secrets/{id}';
};

export type UpdateResponses = {
  200: SecretResponseDto;
};

export type UpdateResponse = UpdateResponses[keyof UpdateResponses];

export type GetAllGraphsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Filter graphs by IDs (comma-separated or repeated params)
     */
    ids?: Array<string>;
  };
  url: '/api/v1/graphs';
};

export type GetAllGraphsResponses = {
  200: Array<GraphDto>;
};

export type GetAllGraphsResponse =
  GetAllGraphsResponses[keyof GetAllGraphsResponses];

export type CreateGraphData = {
  body: CreateGraphDto;
  path?: never;
  query?: never;
  url: '/api/v1/graphs';
};

export type CreateGraphResponses = {
  201: GraphDto;
};

export type CreateGraphResponse =
  CreateGraphResponses[keyof CreateGraphResponses];

export type GetGraphsPreviewData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Filter graphs by IDs (comma-separated or repeated params)
     */
    ids?: Array<string>;
  };
  url: '/api/v1/graphs/preview';
};

export type GetGraphsPreviewResponses = {
  200: Array<GraphPreviewDto>;
};

export type GetGraphsPreviewResponse =
  GetGraphsPreviewResponses[keyof GetGraphsPreviewResponses];

export type DeleteGraphData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/graphs/{id}';
};

export type DeleteGraphResponses = {
  200: unknown;
};

export type FindGraphByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/graphs/{id}';
};

export type FindGraphByIdResponses = {
  200: GraphDto;
};

export type FindGraphByIdResponse =
  FindGraphByIdResponses[keyof FindGraphByIdResponses];

export type UpdateGraphData = {
  body: UpdateGraphDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/graphs/{id}';
};

export type UpdateGraphResponses = {
  200: UpdateGraphResponseDto;
};

export type UpdateGraphResponse =
  UpdateGraphResponses[keyof UpdateGraphResponses];

export type GetCompiledNodesData = {
  body?: never;
  path: {
    id: string;
  };
  query?: {
    threadId?: string;
    runId?: string;
  };
  url: '/api/v1/graphs/{id}/nodes';
};

export type GetCompiledNodesResponses = {
  200: Array<GraphNodeWithStatusDto>;
};

export type GetCompiledNodesResponse =
  GetCompiledNodesResponses[keyof GetCompiledNodesResponses];

export type RunGraphData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/graphs/{id}/run';
};

export type RunGraphResponses = {
  201: GraphDto;
};

export type RunGraphResponse = RunGraphResponses[keyof RunGraphResponses];

export type DestroyGraphData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/graphs/{id}/destroy';
};

export type DestroyGraphResponses = {
  201: GraphDto;
};

export type DestroyGraphResponse =
  DestroyGraphResponses[keyof DestroyGraphResponses];

export type ExecuteTriggerData = {
  body: ExecuteTriggerDto;
  path: {
    graphId: string;
    triggerId: string;
  };
  query?: never;
  url: '/api/v1/graphs/{graphId}/triggers/{triggerId}/execute';
};

export type ExecuteTriggerResponses = {
  201: ExecuteTriggerResponseDto;
};

export type ExecuteTriggerResponse =
  ExecuteTriggerResponses[keyof ExecuteTriggerResponses];

export type GetGraphRevisionsData = {
  body?: never;
  path: {
    graphId: string;
  };
  query?: {
    status?: 'pending' | 'applying' | 'applied' | 'failed';
    /**
     * Maximum number of revisions to return
     */
    limit?: number;
  };
  url: '/api/v1/graphs/{graphId}/revisions';
};

export type GetGraphRevisionsResponses = {
  200: Array<GraphRevisionDto>;
};

export type GetGraphRevisionsResponse =
  GetGraphRevisionsResponses[keyof GetGraphRevisionsResponses];

export type GetGraphRevisionData = {
  body?: never;
  path: {
    graphId: string;
    id: string;
  };
  query?: never;
  url: '/api/v1/graphs/{graphId}/revisions/{id}';
};

export type GetGraphRevisionResponses = {
  200: GraphRevisionDto;
};

export type GetGraphRevisionResponse =
  GetGraphRevisionResponses[keyof GetGraphRevisionResponses];

export type GetAllTemplatesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/templates';
};

export type GetAllTemplatesResponses = {
  200: Array<TemplateDto>;
};

export type GetAllTemplatesResponse =
  GetAllTemplatesResponses[keyof GetAllTemplatesResponses];

export type SuggestAgentInstructionsData = {
  body: SuggestAgentInstructionsDto;
  path: {
    graphId: string;
    nodeId: string;
  };
  query?: never;
  url: '/api/v1/graphs/{graphId}/nodes/{nodeId}/suggest-instructions';
};

export type SuggestAgentInstructionsResponses = {
  201: SuggestAgentInstructionsResponseDto;
};

export type SuggestAgentInstructionsResponse =
  SuggestAgentInstructionsResponses[keyof SuggestAgentInstructionsResponses];

export type SuggestGraphInstructionsData = {
  body: SuggestGraphInstructionsDto;
  path: {
    graphId: string;
  };
  query?: never;
  url: '/api/v1/graphs/{graphId}/suggest-instructions';
};

export type SuggestGraphInstructionsResponses = {
  201: SuggestGraphInstructionsResponseDto;
};

export type SuggestGraphInstructionsResponse =
  SuggestGraphInstructionsResponses[keyof SuggestGraphInstructionsResponses];

export type AnalyzeThreadData = {
  body: ThreadAnalysisRequestDto;
  path: {
    threadId: string;
  };
  query?: never;
  url: '/api/v1/threads/{threadId}/analyze';
};

export type AnalyzeThreadResponses = {
  201: ThreadAnalysisResponseDto;
};

export type AnalyzeThreadResponse =
  AnalyzeThreadResponses[keyof AnalyzeThreadResponses];

export type SuggestKnowledgeContentData = {
  body: KnowledgeContentSuggestionRequestDto;
  path?: never;
  query?: never;
  url: '/api/v1/knowledge-docs/suggest';
};

export type SuggestKnowledgeContentResponses = {
  201: KnowledgeContentSuggestionResponseDto;
};

export type SuggestKnowledgeContentResponse =
  SuggestKnowledgeContentResponses[keyof SuggestKnowledgeContentResponses];

export type GetOverviewData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Include threads created on or after this ISO 8601 datetime
     */
    dateFrom?: string;
    /**
     * Include threads created before this ISO 8601 datetime
     */
    dateTo?: string;
  };
  url: '/api/v1/analytics/overview';
};

export type GetOverviewResponses = {
  200: AnalyticsOverviewDto;
};

export type GetOverviewResponse =
  GetOverviewResponses[keyof GetOverviewResponses];

export type GetByGraphData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Include threads created on or after this ISO 8601 datetime
     */
    dateFrom?: string;
    /**
     * Include threads created before this ISO 8601 datetime
     */
    dateTo?: string;
    /**
     * Filter to a specific graph
     */
    graphId?: string;
  };
  url: '/api/v1/analytics/by-graph';
};

export type GetByGraphResponses = {
  200: AnalyticsByGraphResponseDto;
};

export type GetByGraphResponse = GetByGraphResponses[keyof GetByGraphResponses];

export type ListSystemAgentsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/system-agents';
};

export type ListSystemAgentsResponses = {
  200: Array<SystemAgentResponseDto>;
};

export type ListSystemAgentsResponse =
  ListSystemAgentsResponses[keyof ListSystemAgentsResponses];

export type GetSystemAgentByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/system-agents/{id}';
};

export type GetSystemAgentByIdResponses = {
  200: SystemAgentResponseDto;
};

export type GetSystemAgentByIdResponse =
  GetSystemAgentByIdResponses[keyof GetSystemAgentByIdResponses];

export type ListInstructionBlocksData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/instruction-blocks';
};

export type ListInstructionBlocksResponses = {
  200: Array<InstructionBlockResponseDto>;
};

export type ListInstructionBlocksResponse =
  ListInstructionBlocksResponses[keyof ListInstructionBlocksResponses];

export type GetInstructionBlockByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/instruction-blocks/{id}';
};

export type GetInstructionBlockByIdResponses = {
  200: InstructionBlockResponseDto;
};

export type GetInstructionBlockByIdResponse =
  GetInstructionBlockByIdResponses[keyof GetInstructionBlockByIdResponses];

export type StartData = {
  body?: never;
  path: {
    provider: 'linear';
  };
  query?: {
    graphId?: string;
    nodeId?: string;
  };
  url: '/api/v1/oauth/{provider}/start';
};

export type StartResponses = {
  200: OAuthStartResponseDto;
};

export type StartResponse = StartResponses[keyof StartResponses];

export type StatusData = {
  body?: never;
  path: {
    provider: 'linear';
  };
  query?: never;
  url: '/api/v1/oauth/{provider}/status';
};

export type StatusResponses = {
  200: OAuthStatusResponseDto;
};

export type StatusResponse = StatusResponses[keyof StatusResponses];

export type ExchangeData = {
  body: OAuthExchangeRequestDto;
  path?: never;
  query?: never;
  url: '/api/v1/oauth/credentials/exchange';
};

export type ExchangeResponses = {
  200: OAuthExchangeResponseDto;
};

export type ExchangeResponse = ExchangeResponses[keyof ExchangeResponses];

export type GetSettingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/system/settings';
};

export type GetSettingsResponses = {
  200: SystemSettingsResponseDto;
};

export type GetSettingsResponse =
  GetSettingsResponses[keyof GetSettingsResponses];

export type GetAuthConfigData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/system/config';
};

export type GetAuthConfigResponses = {
  200: AuthConfigResponseDto;
};

export type GetAuthConfigResponse =
  GetAuthConfigResponses[keyof GetAuthConfigResponses];
