import { formatDistanceToNow } from 'date-fns';
import { Pencil, Plus, Trash2 } from 'lucide-react';
import { useCallback, useEffect, useRef, useState } from 'react';
import { useParams } from 'react-router';
import { toast } from 'sonner';

import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Skeleton } from '@/components/ui/skeleton';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { Textarea } from '@/components/ui/textarea';

import { agentMemoryApi } from '../../api';
import {
  type AgentMemoryEntryDto,
  AgentMemoryEntryDtoModeEnum,
  type NamespaceSummaryDto,
} from '../../autogenerated';
import { extractApiErrorMessage } from '../../utils/errors';

const stringifyValue = (value: unknown): string =>
  typeof value === 'string' ? value : JSON.stringify(value, null, 2);

// Memories may hold a string or a JSON object. Only parse object/array literals;
// scalar-looking text ("123", "true", "null") stays the literal string the user
// typed, so plain notes are never silently coerced to a typed value.
const parseValue = (raw: string): unknown => {
  const trimmed = raw.trim();
  if (!trimmed) {
    return '';
  }
  if (trimmed.startsWith('{') || trimmed.startsWith('[')) {
    try {
      return JSON.parse(trimmed);
    } catch {
      return raw;
    }
  }
  return raw;
};

type FormState = {
  namespace: string;
  key: string;
  title: string;
  value: string;
  tags: string;
};

const EMPTY_FORM: FormState = {
  namespace: '',
  key: '',
  title: '',
  value: '',
  tags: '',
};

export function MemoryListPage() {
  const { projectId } = useParams<{ projectId: string }>();
  const [namespaces, setNamespaces] = useState<NamespaceSummaryDto[]>([]);
  const [selected, setSelected] = useState<string | null>(null);
  const [entries, setEntries] = useState<AgentMemoryEntryDto[]>([]);
  const [loading, setLoading] = useState(true);
  const [entriesLoading, setEntriesLoading] = useState(false);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editing, setEditing] = useState<AgentMemoryEntryDto | null>(null);
  const [form, setForm] = useState<FormState>(EMPTY_FORM);
  const [saving, setSaving] = useState(false);
  // Guards against an out-of-order entries response from a previous namespace
  // overwriting the currently-selected namespace's entries.
  const latestNamespaceRef = useRef<string | null>(null);

  const loadNamespaces = useCallback(async () => {
    setLoading(true);
    try {
      const { data } = await agentMemoryApi.listMemoryNamespaces();
      setNamespaces(data);
      setSelected((prev) => {
        if (prev && data.some((n) => n.namespace === prev)) {
          return prev;
        }
        return data[0]?.namespace ?? null;
      });
    } catch (err) {
      toast.error(extractApiErrorMessage(err, 'Failed to load project memory'));
    } finally {
      setLoading(false);
    }
  }, []);

  const loadEntries = useCallback(async (namespace: string) => {
    latestNamespaceRef.current = namespace;
    setEntriesLoading(true);
    try {
      const { data } = await agentMemoryApi.listMemoryEntries(namespace);
      if (latestNamespaceRef.current === namespace) {
        setEntries(data);
      }
    } catch (err) {
      toast.error(extractApiErrorMessage(err, 'Failed to load memory entries'));
    } finally {
      if (latestNamespaceRef.current === namespace) {
        setEntriesLoading(false);
      }
    }
  }, []);

  useEffect(() => {
    void loadNamespaces();
  }, [loadNamespaces, projectId]);

  useEffect(() => {
    if (selected) {
      void loadEntries(selected);
    } else {
      setEntries([]);
    }
  }, [selected, loadEntries]);

  const openCreate = () => {
    setEditing(null);
    setForm({ ...EMPTY_FORM, namespace: selected ?? '' });
    setDialogOpen(true);
  };

  const openEdit = (entry: AgentMemoryEntryDto) => {
    setEditing(entry);
    setForm({
      namespace: entry.namespace,
      key: entry.key,
      title: entry.title ?? '',
      value: stringifyValue(entry.value),
      tags: (entry.tags ?? []).join(', '),
    });
    setDialogOpen(true);
  };

  const handleSave = async () => {
    const namespace = form.namespace.trim();
    const key = form.key.trim();
    if (!namespace || !key) {
      toast.error('Namespace and key are required');
      return;
    }
    setSaving(true);
    try {
      const tags = form.tags
        .split(',')
        .map((t) => t.trim())
        .filter(Boolean);
      await agentMemoryApi.saveMemoryEntry({
        namespace,
        key,
        title: form.title.trim() || null,
        value: parseValue(form.value),
        tags: tags.length ? tags : null,
      });
      toast.success(editing ? 'Memory updated' : 'Memory created');
      setDialogOpen(false);
      await loadNamespaces();
      if (selected === namespace) {
        await loadEntries(namespace);
      } else {
        setSelected(namespace);
      }
    } catch (err) {
      toast.error(extractApiErrorMessage(err, 'Failed to save memory'));
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async (entry: AgentMemoryEntryDto) => {
    if (!window.confirm(`Delete memory "${entry.namespace}/${entry.key}"?`)) {
      return;
    }
    try {
      await agentMemoryApi.deleteMemoryEntry(entry.namespace, entry.key);
      toast.success('Memory deleted');
      await loadNamespaces();
      if (selected) {
        await loadEntries(selected);
      }
    } catch (err) {
      toast.error(extractApiErrorMessage(err, 'Failed to delete memory'));
    }
  };

  return (
    <div className="flex flex-col gap-4 p-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold">Project Memory</h1>
          <p className="text-muted-foreground text-sm">
            Durable memory agents share across threads and sessions in this
            project.
          </p>
        </div>
        <Button onClick={openCreate}>
          <Plus className="mr-2 size-4" />
          New memory
        </Button>
      </div>

      {loading ? (
        <div className="flex flex-col gap-2">
          <Skeleton className="h-10 w-64" />
          <Skeleton className="h-40 w-full" />
        </div>
      ) : namespaces.length === 0 ? (
        <Card className="text-muted-foreground p-8 text-center">
          No memories yet. Agents in this project will fill this in, or create
          one manually with “New memory”.
        </Card>
      ) : (
        <>
          <div className="flex items-center gap-2">
            <Label htmlFor="namespace-select" className="text-sm">
              Namespace
            </Label>
            <Select
              value={selected ?? undefined}
              onValueChange={(v) => setSelected(v)}>
              <SelectTrigger id="namespace-select" className="w-64">
                <SelectValue placeholder="Select a namespace" />
              </SelectTrigger>
              <SelectContent>
                {namespaces.map((ns) => (
                  <SelectItem key={ns.namespace} value={ns.namespace}>
                    {ns.namespace} ({ns.entryCount})
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <Card className="overflow-hidden">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Key</TableHead>
                  <TableHead>Title</TableHead>
                  <TableHead>Mode</TableHead>
                  <TableHead>Tags</TableHead>
                  <TableHead>Updated</TableHead>
                  <TableHead className="w-24 text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {entriesLoading ? (
                  <TableRow>
                    <TableCell colSpan={6}>
                      <Skeleton className="h-6 w-full" />
                    </TableCell>
                  </TableRow>
                ) : entries.length === 0 ? (
                  <TableRow>
                    <TableCell
                      colSpan={6}
                      className="text-muted-foreground text-center">
                      No entries in this namespace.
                    </TableCell>
                  </TableRow>
                ) : (
                  entries.map((entry) => (
                    <TableRow key={entry.id}>
                      <TableCell className="font-mono text-xs">
                        {entry.key}
                      </TableCell>
                      <TableCell>{entry.title ?? '—'}</TableCell>
                      <TableCell>
                        <Badge
                          variant={
                            entry.mode === AgentMemoryEntryDtoModeEnum.Append
                              ? 'secondary'
                              : 'default'
                          }>
                          {entry.mode}
                        </Badge>
                      </TableCell>
                      <TableCell>
                        <div className="flex flex-wrap gap-1">
                          {(entry.tags ?? []).map((tag) => (
                            <Badge key={tag} variant="outline">
                              {tag}
                            </Badge>
                          ))}
                        </div>
                      </TableCell>
                      <TableCell className="text-muted-foreground text-xs">
                        {formatDistanceToNow(new Date(entry.updatedAt), {
                          addSuffix: true,
                        })}
                      </TableCell>
                      <TableCell className="text-right">
                        {entry.mode === AgentMemoryEntryDtoModeEnum.Kv && (
                          <div className="flex justify-end gap-1">
                            <Button
                              size="icon"
                              variant="ghost"
                              aria-label="Edit memory"
                              onClick={() => openEdit(entry)}>
                              <Pencil className="size-4" />
                            </Button>
                            <Button
                              size="icon"
                              variant="ghost"
                              aria-label="Delete memory"
                              onClick={() => handleDelete(entry)}>
                              <Trash2 className="size-4" />
                            </Button>
                          </div>
                        )}
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </Card>
        </>
      )}

      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{editing ? 'Edit memory' : 'New memory'}</DialogTitle>
            <DialogDescription>
              Memories persist across sessions and are shared by every agent in
              the project.
            </DialogDescription>
          </DialogHeader>
          <div className="flex flex-col gap-3">
            <div className="flex flex-col gap-1">
              <Label htmlFor="form-namespace">Namespace</Label>
              <Input
                id="form-namespace"
                value={form.namespace}
                disabled={!!editing}
                onChange={(e) =>
                  setForm((f) => ({ ...f, namespace: e.target.value }))
                }
                placeholder="conventions"
              />
            </div>
            <div className="flex flex-col gap-1">
              <Label htmlFor="form-key">Key</Label>
              <Input
                id="form-key"
                value={form.key}
                disabled={!!editing}
                onChange={(e) =>
                  setForm((f) => ({ ...f, key: e.target.value }))
                }
                placeholder="package-manager"
              />
            </div>
            <div className="flex flex-col gap-1">
              <Label htmlFor="form-title">Title</Label>
              <Input
                id="form-title"
                value={form.title}
                onChange={(e) =>
                  setForm((f) => ({ ...f, title: e.target.value }))
                }
                placeholder="Short, recognizable label"
              />
            </div>
            <div className="flex flex-col gap-1">
              <Label htmlFor="form-value">Value</Label>
              <Textarea
                id="form-value"
                value={form.value}
                onChange={(e) =>
                  setForm((f) => ({ ...f, value: e.target.value }))
                }
                rows={6}
                placeholder="Text or JSON"
              />
            </div>
            <div className="flex flex-col gap-1">
              <Label htmlFor="form-tags">Tags (comma-separated)</Label>
              <Input
                id="form-tags"
                value={form.tags}
                onChange={(e) =>
                  setForm((f) => ({ ...f, tags: e.target.value }))
                }
                placeholder="build, conventions"
              />
            </div>
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setDialogOpen(false)}
              disabled={saving}>
              Cancel
            </Button>
            <Button onClick={handleSave} disabled={saving}>
              {saving ? 'Saving…' : 'Save'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
