import { formatDistanceToNow } from 'date-fns';
import { Pencil, Trash2 } from 'lucide-react';

import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';

import {
  type AgentMemoryEntryDto,
  AgentMemoryEntryDtoModeEnum,
} from '../../autogenerated';

type MemoryEntriesTableProps = {
  entries: AgentMemoryEntryDto[];
  loading: boolean;
  onEdit: (entry: AgentMemoryEntryDto) => void;
  onDelete: (entry: AgentMemoryEntryDto) => void;
};

/**
 * Presentational table for one namespace's memory entries. Stateless — the page
 * owns data fetching and the edit/delete dialogs and passes the callbacks in.
 * Edit/delete affordances show only for overwritable (kv) entries; append
 * entries are immutable.
 */
export function MemoryEntriesTable({
  entries,
  loading,
  onEdit,
  onDelete,
}: MemoryEntriesTableProps) {
  return (
    <Card className="overflow-hidden">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>Key</TableHead>
            <TableHead>Title</TableHead>
            <TableHead>Mode</TableHead>
            <TableHead>Tags</TableHead>
            <TableHead>Updated</TableHead>
            <TableHead className="w-24 text-right">Actions</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {loading ? (
            <TableRow>
              <TableCell colSpan={6}>
                <Skeleton className="h-6 w-full" />
              </TableCell>
            </TableRow>
          ) : entries.length === 0 ? (
            <TableRow>
              <TableCell
                colSpan={6}
                className="text-muted-foreground text-center">
                No entries in this namespace.
              </TableCell>
            </TableRow>
          ) : (
            entries.map((entry) => (
              <TableRow key={entry.id}>
                <TableCell className="font-mono text-xs">{entry.key}</TableCell>
                <TableCell>{entry.title ?? '—'}</TableCell>
                <TableCell>
                  <Badge
                    variant={
                      entry.mode === AgentMemoryEntryDtoModeEnum.Append
                        ? 'secondary'
                        : 'default'
                    }>
                    {entry.mode}
                  </Badge>
                </TableCell>
                <TableCell>
                  <div className="flex flex-wrap gap-1">
                    {(entry.tags ?? []).map((tag) => (
                      <Badge key={tag} variant="outline">
                        {tag}
                      </Badge>
                    ))}
                  </div>
                </TableCell>
                <TableCell className="text-muted-foreground text-xs">
                  {formatDistanceToNow(new Date(entry.updatedAt), {
                    addSuffix: true,
                  })}
                </TableCell>
                <TableCell className="text-right">
                  {entry.mode === AgentMemoryEntryDtoModeEnum.Kv && (
                    <div className="flex justify-end gap-1">
                      <Button
                        size="icon"
                        variant="ghost"
                        aria-label="Edit memory"
                        onClick={() => onEdit(entry)}>
                        <Pencil className="size-4" />
                      </Button>
                      <Button
                        size="icon"
                        variant="ghost"
                        aria-label="Delete memory"
                        onClick={() => onDelete(entry)}>
                        <Trash2 className="size-4" />
                      </Button>
                    </div>
                  )}
                </TableCell>
              </TableRow>
            ))
          )}
        </TableBody>
      </Table>
    </Card>
  );
}
