import { Loader2, RefreshCw, X } from 'lucide-react';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';

import { threadStoreApi } from '../../../api';
import type {
  NamespaceSummaryDto,
  ThreadStoreEntryDto,
} from '../../../autogenerated';
import { Badge } from '../../../components/ui/badge';
import { Button } from '../../../components/ui/button';
import { ScrollArea } from '../../../components/ui/scroll-area';
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from '../../../components/ui/tooltip';
import { useWebSocketEvent } from '../../../hooks/useWebSocket';
import type { ThreadStoreUpdateNotification } from '../../../services/WebSocketTypes';
import { formatTimestamp, formatValue } from './threadStoreUtils';

interface ThreadStoreSidebarProps {
  open: boolean;
  onClose: () => void;
  /** Internal DB thread id (UUID). Required for REST calls. */
  threadId: string;
  /**
   * External thread id (graphId:subId). Used to filter websocket events,
   * which are scoped to the external id.
   */
  externalThreadId?: string;
}

export const ThreadStoreSidebar = ({
  open,
  onClose,
  threadId,
  externalThreadId,
}: ThreadStoreSidebarProps) => {
  const [namespaces, setNamespaces] = useState<NamespaceSummaryDto[]>([]);
  const [activeNamespace, setActiveNamespace] = useState<string | null>(null);
  const [entries, setEntries] = useState<ThreadStoreEntryDto[]>([]);
  const [loadingNamespaces, setLoadingNamespaces] = useState(false);
  const [loadingEntries, setLoadingEntries] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const nsAbortRef = useRef<AbortController | null>(null);
  const entryAbortRef = useRef<AbortController | null>(null);

  useEffect(
    () => () => {
      nsAbortRef.current?.abort();
      entryAbortRef.current?.abort();
    },
    [],
  );

  const fetchNamespaces = useCallback(async () => {
    nsAbortRef.current?.abort();
    nsAbortRef.current = new AbortController();
    const signal = nsAbortRef.current.signal;
    const capturedThreadId = threadId;

    setLoadingNamespaces(true);
    setError(null);
    try {
      const response = await threadStoreApi.listNamespaces(capturedThreadId, {
        signal,
      });
      if (capturedThreadId !== threadId) {
        return;
      }
      const data = response.data;
      setNamespaces(data);
      setActiveNamespace((prev) => {
        if (data.length > 0 && !data.some((n) => n.namespace === prev)) {
          return data[0]!.namespace;
        }
        if (data.length === 0) {
          return null;
        }
        return prev;
      });
    } catch (err) {
      if (err instanceof Error && err.name === 'CanceledError') {
        return;
      }
      setError(
        err instanceof Error ? err.message : 'Failed to load namespaces',
      );
    } finally {
      if (nsAbortRef.current?.signal === signal) {
        setLoadingNamespaces(false);
      }
    }
  }, [threadId]);

  const fetchEntries = useCallback(
    async (namespace: string) => {
      entryAbortRef.current?.abort();
      entryAbortRef.current = new AbortController();
      const signal = entryAbortRef.current.signal;
      const capturedThreadId = threadId;

      setLoadingEntries(true);
      try {
        const response = await threadStoreApi.listEntries(
          capturedThreadId,
          namespace,
          100,
          undefined,
          { signal },
        );
        if (capturedThreadId !== threadId) {
          return;
        }
        setEntries(response.data);
      } catch (err) {
        if (err instanceof Error && err.name === 'CanceledError') {
          return;
        }
        setError(err instanceof Error ? err.message : 'Failed to load entries');
      } finally {
        if (entryAbortRef.current?.signal === signal) {
          setLoadingEntries(false);
        }
      }
    },
    [threadId],
  );

  useEffect(() => {
    setEntries([]);
  }, [activeNamespace]);

  useEffect(() => {
    if (namespaces.length === 0) {
      setEntries([]);
    }
  }, [namespaces]);

  useEffect(() => {
    if (!open) {
      return;
    }
    void fetchNamespaces();
  }, [open, fetchNamespaces]);

  useEffect(() => {
    if (!open || !activeNamespace) {
      return;
    }
    void fetchEntries(activeNamespace);
  }, [open, activeNamespace, fetchEntries]);

  useWebSocketEvent('thread.store.update', (event) => {
    const notification = event as ThreadStoreUpdateNotification;
    const eventExternalId = notification.threadId;

    const matchesExternal =
      externalThreadId && eventExternalId === externalThreadId;

    if (!matchesExternal) {
      return;
    }

    if (!open) {
      return;
    }

    void fetchNamespaces();
    if (notification.data.namespace === activeNamespace) {
      void fetchEntries(notification.data.namespace);
    }
  });

  const totalEntries = useMemo(
    () => namespaces.reduce((sum, ns) => sum + ns.entryCount, 0),
    [namespaces],
  );

  const handleRefresh = useCallback(() => {
    void fetchNamespaces();
    if (activeNamespace) {
      void fetchEntries(activeNamespace);
    }
  }, [fetchNamespaces, fetchEntries, activeNamespace]);

  const activeSummary = namespaces.find((n) => n.namespace === activeNamespace);

  if (!open) {
    return null;
  }

  const showLoading = loadingNamespaces && namespaces.length === 0;
  const refreshing = loadingNamespaces || loadingEntries;

  return (
    <div className="w-72 shrink-0 border-l border-border flex flex-col bg-background overflow-hidden">
      {/* Header */}
      <div className="px-4 py-4 border-b border-border flex justify-between items-center shrink-0">
        <h3 className="text-base font-semibold">
          Thread store
          {namespaces.length > 0 ? (
            <Badge variant="secondary" className="ml-2">
              {namespaces.length} ns · {totalEntries}
            </Badge>
          ) : null}
        </h3>
        <div className="flex items-center gap-1">
          <Tooltip>
            <TooltipTrigger asChild>
              <Button
                variant="ghost"
                size="icon"
                className="h-7 w-7"
                onClick={handleRefresh}
                disabled={refreshing}>
                {refreshing ? (
                  <Loader2 className="h-3.5 w-3.5 animate-spin" />
                ) : (
                  <RefreshCw className="h-3.5 w-3.5" />
                )}
              </Button>
            </TooltipTrigger>
            <TooltipContent>Refresh store</TooltipContent>
          </Tooltip>
          <Tooltip>
            <TooltipTrigger asChild>
              <Button
                variant="ghost"
                size="icon"
                className="h-7 w-7"
                onClick={onClose}>
                <X className="h-3.5 w-3.5" />
              </Button>
            </TooltipTrigger>
            <TooltipContent>Close</TooltipContent>
          </Tooltip>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 min-h-0 overflow-y-auto px-3 py-3 space-y-3">
        {error ? <p className="text-sm text-destructive">{error}</p> : null}

        {showLoading ? (
          <div className="flex justify-center items-center pt-12">
            <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
          </div>
        ) : null}

        {!showLoading && namespaces.length === 0 && !error ? (
          <div className="flex flex-col items-center justify-center py-12 text-center">
            <p className="text-sm text-muted-foreground">
              No entries yet. Agents can write here via the Thread Store tools
              (put, append).
            </p>
          </div>
        ) : null}

        {namespaces.length > 0 ? (
          <div className="flex items-center gap-2 flex-wrap">
            {namespaces.map((ns) => (
              <Button
                key={ns.namespace}
                type="button"
                size="sm"
                variant={
                  ns.namespace === activeNamespace ? 'default' : 'outline'
                }
                onClick={() => setActiveNamespace(ns.namespace)}>
                {ns.namespace}
                <Badge variant="secondary" className="ml-2">
                  {ns.entryCount}
                </Badge>
              </Button>
            ))}
          </div>
        ) : null}

        {activeSummary ? (
          <div className="text-xs text-muted-foreground">
            Last update: {formatTimestamp(activeSummary.lastUpdatedAt)}
          </div>
        ) : null}

        {activeNamespace ? (
          <ScrollArea className="max-h-[calc(100vh-260px)]">
            {loadingEntries && entries.length === 0 ? (
              <div className="flex items-center justify-center py-6">
                <Loader2 className="h-4 w-4 animate-spin text-muted-foreground" />
              </div>
            ) : entries.length === 0 ? (
              <p className="text-sm text-muted-foreground">
                This namespace is empty.
              </p>
            ) : (
              <ul className="space-y-2">
                {entries.map((entry) => (
                  <li
                    key={entry.id}
                    className="rounded-md border border-border bg-card p-2">
                    <div className="flex items-center gap-2 flex-wrap text-xs text-muted-foreground">
                      <span className="font-mono text-foreground break-all">
                        {entry.key}
                      </span>
                      <Badge
                        variant={
                          entry.mode === 'append' ? 'secondary' : 'outline'
                        }>
                        {entry.mode}
                      </Badge>
                      {entry.authorAgentId ? (
                        <Badge variant="outline">{entry.authorAgentId}</Badge>
                      ) : null}
                      <span>{formatTimestamp(entry.updatedAt)}</span>
                    </div>
                    {entry.tags && entry.tags.length > 0 ? (
                      <div className="mt-1 flex items-center gap-1 flex-wrap">
                        {entry.tags.map((tag) => (
                          <Badge key={tag} variant="secondary">
                            {tag}
                          </Badge>
                        ))}
                      </div>
                    ) : null}
                    <pre className="mt-2 whitespace-pre-wrap break-words text-xs font-mono text-foreground bg-muted/40 rounded p-2">
                      {formatValue(entry.value)}
                    </pre>
                  </li>
                ))}
              </ul>
            )}
          </ScrollArea>
        ) : null}
      </div>
    </div>
  );
};
