// @vitest-environment jsdom
import { cleanup, render, screen } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';

import { ThreadDtoStatusEnum } from '../../../autogenerated/api';
import { ThreadTokenUsageLine } from './ThreadTokenUsageLine';

// useLiveThreadDuration is a timer hook; mock it so tests are deterministic.
const mocks = vi.hoisted(() => ({
  useLiveThreadDuration: vi.fn<() => number>(),
}));

vi.mock('../hooks/useLiveThreadDuration', () => ({
  useLiveThreadDuration: mocks.useLiveThreadDuration,
}));

afterEach(() => {
  cleanup();
});

const baseUsage = {
  totalTokens: 1000,
  totalPrice: 0.01,
  inputTokens: 600,
  outputTokens: 400,
};

describe('ThreadTokenUsageLine — duration suffix visibility', () => {
  it('shows duration suffix when runningStartedAt + threadStatus=Running', () => {
    // Hook returns a positive duration so formatDurationMs produces a non-dash string
    mocks.useLiveThreadDuration.mockReturnValue(5000);

    render(
      <ThreadTokenUsageLine
        usage={baseUsage}
        runningStartedAt={new Date().toISOString()}
        threadStatus={ThreadDtoStatusEnum.Running}
      />,
    );

    // Suffix " · 5s" should appear — the "·" separator is the clearest marker
    const label = screen.getByText(/·/);
    expect(label).toBeDefined();
    expect(label.textContent).toMatch(/5s/);
  });

  it('shows duration suffix when totalRunningMs > 0 + threadStatus=Done', () => {
    // Hook returns the frozen totalRunningMs value
    mocks.useLiveThreadDuration.mockReturnValue(90_000);

    render(
      <ThreadTokenUsageLine
        usage={baseUsage}
        totalRunningMs={90_000}
        threadStatus={ThreadDtoStatusEnum.Done}
      />,
    );

    const label = screen.getByText(/·/);
    expect(label).toBeDefined();
    // 90 000 ms = 1m 30s
    expect(label.textContent).toMatch(/1m 30s/);
  });

  it('does NOT show duration suffix when only threadStatus=Done, no time fields', () => {
    // Hook returns 0 (totalRunningMs is undefined → 0)
    mocks.useLiveThreadDuration.mockReturnValue(0);

    const { container } = render(
      <ThreadTokenUsageLine
        usage={baseUsage}
        threadStatus={ThreadDtoStatusEnum.Done}
      />,
    );

    // The "·" separator should be absent from this render's output
    expect(container.textContent).not.toMatch(/·/);
  });
});
