import axios from 'axios';
import {
  AlertTriangle,
  ChevronDown,
  CircleX,
  GitBranch,
  Loader2,
  Play,
  Send,
  Square,
  Timer,
  Zap,
} from 'lucide-react';
import React, {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from 'react';
import { toast } from 'sonner';

import { GithubIcon as Github } from '@/components/ui/icons';

import { gitRepositoriesApi, graphsApi, threadsApi } from '../../../api';
import type {
  ExecuteTriggerDtoMessagesInner,
  GitRepositoryDto,
  ThreadDto,
  ThreadMessageDto,
} from '../../../autogenerated';
import { ThreadDtoStatusEnum } from '../../../autogenerated';
import { Badge } from '../../../components/ui/badge';
import { Button } from '../../../components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '../../../components/ui/dropdown-menu';
import { Input } from '../../../components/ui/input';
import { PickerTrigger } from '../../../components/ui/picker-trigger';
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '../../../components/ui/popover';
import { Textarea } from '../../../components/ui/textarea';
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from '../../../components/ui/tooltip';
import { cn } from '../../../components/ui/utils';
import { formatCountdown, useCountdown } from '../../../hooks/useCountdown';
import { useSystemSettings } from '../../../hooks/useSystemSettings';
import { extractApiErrorMessage } from '../../../utils/errors';
import {
  extractThreadSubId,
  type TriggerNodeInfo,
} from '../../../utils/graphThreads';
import {
  buildContentBlocks,
  extractTextFromContentBlocks,
  fileToDataUrl,
  type ImageAttachment,
  MAX_IMAGES_PER_MESSAGE,
  validateImageFile,
} from '../../../utils/imageAttachments';
import { sortMessagesChronologically } from '../../../utils/threadMessages';
import ThreadMessagesView from '../../graphs/components/ThreadMessagesView';
import type { PendingMessage } from '../../graphs/types/messages';

interface ThreadChatPanelProps {
  graphId: string;
  thread: ThreadDto;
  triggerNodes: TriggerNodeInfo[];
  nodeDisplayNames?: Record<string, string>;
  templatesLoading?: boolean;
  graphLoaded?: boolean;
  graphIsRunning?: boolean;
  onRequestThreadSwitch?: (externalThreadId: string | null) => void;
  isDraft?: boolean;
  onDraftMessageSent?: (newThread: ThreadDto) => void;
  style?: React.CSSProperties;
  messages: ThreadMessageDto[];
  messagesLoading: boolean;
  hasMoreMessages: boolean;
  loadingMoreMessages: boolean;
  pendingMessages?: PendingMessage[];
  externalThreadId?: string;
  onLoadMoreMessages?: () => void;
  onUpdateSharedMessages: (
    threadId: string,
    updater: (prev: ThreadMessageDto[]) => ThreadMessageDto[],
    nodeId?: string,
  ) => void;
  onUpdatePendingMessages?: (
    threadId: string,
    updater: (prev: PendingMessage[]) => PendingMessage[],
    nodeId?: string,
  ) => void;
  newMessageMode?: 'inject_after_tool_call' | 'wait_for_completion';
}

export const ThreadChatPanel: React.FC<ThreadChatPanelProps> = ({
  graphId,
  thread,
  triggerNodes,
  nodeDisplayNames,
  templatesLoading = false,
  graphLoaded = true,
  graphIsRunning = true,
  onRequestThreadSwitch,
  isDraft = false,
  onDraftMessageSent,
  style,
  messages,
  messagesLoading,
  hasMoreMessages,
  loadingMoreMessages,
  pendingMessages: pendingMessagesProp = [],
  externalThreadId,
  onLoadMoreMessages,
  onUpdateSharedMessages,
  onUpdatePendingMessages,
  newMessageMode = 'wait_for_completion',
}) => {
  const [selectedTriggerId, setSelectedTriggerId] = useState<
    string | undefined
  >(() => triggerNodes[0]?.id);
  const [messageInput, setMessageInput] = useState('');
  const [imageAttachments, setImageAttachments] = useState<ImageAttachment[]>(
    [],
  );
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const sendingRef = useRef(false);
  const [sendingMessage, setSendingMessage] = useState(false);
  const [stoppingThread, setStoppingThread] = useState(false);
  const [threadStatusOverride, setThreadStatusOverride] = useState<
    ThreadDto['status'] | undefined
  >(undefined);
  const [selectedThreadExternalId, setSelectedThreadExternalId] = useState<
    string | undefined
  >(externalThreadId ?? thread.externalThreadId ?? undefined);
  const pendingDraftExternalIdRef = useRef<string | undefined>(undefined);
  const previousThreadIdRef = useRef<string>(thread.id);

  // --- Repository selector state ---
  const [repos, setRepos] = useState<GitRepositoryDto[]>([]);
  const [reposLoading, setReposLoading] = useState(false);
  const [selectedRepoId, setSelectedRepoId] = useState<string | undefined>(
    () => {
      const metaRepoId = thread.metadata?.repositoryId as string | undefined;
      return metaRepoId || undefined;
    },
  );
  const [repoLocked, setRepoLocked] = useState<boolean>(
    () => !!thread.metadata?.repositoryId,
  );
  const [repoPopoverOpen, setRepoPopoverOpen] = useState(false);
  const [repoSearch, setRepoSearch] = useState('');

  const { settings: systemSettings } = useSystemSettings();

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect -- mirror parent prop into local override
    setSelectedThreadExternalId(
      externalThreadId ?? thread.externalThreadId ?? undefined,
    );
  }, [externalThreadId, thread.externalThreadId]);

  // Load repositories once on mount
  useEffect(() => {
    let mounted = true;
    const loadRepos = async () => {
      try {
        setReposLoading(true);
        const response = await gitRepositoriesApi.getRepositories();
        if (mounted) {
          setRepos(response.data || []);
        }
      } catch (error) {
        console.error('Error loading repositories', error);
      } finally {
        if (mounted) {
          setReposLoading(false);
        }
      }
    };
    void loadRepos();
    return () => {
      mounted = false;
    };
  }, []);

  useEffect(() => {
    const previousThreadId = previousThreadIdRef.current;
    previousThreadIdRef.current = thread.id;
    if (previousThreadId === thread.id) {
      return;
    }

    setMessageInput('');
    setImageAttachments([]);
    setThreadStatusOverride(undefined);

    // Sync repo state from thread metadata
    const metaRepoId = thread.metadata?.repositoryId as string | undefined;
    if (metaRepoId) {
      // eslint-disable-next-line react-hooks/set-state-in-effect -- reconcile repo selection when thread changes
      setSelectedRepoId(metaRepoId);
      setRepoLocked(true);
    } else {
      setSelectedRepoId(undefined);
      setRepoLocked(false);
    }

    if (!isDraft) {
      pendingDraftExternalIdRef.current = undefined;
    }
  }, [thread.id, isDraft, thread.metadata]);

  useEffect(() => {
    if (threadStatusOverride && thread.status !== ThreadDtoStatusEnum.Running) {
      // eslint-disable-next-line react-hooks/set-state-in-effect -- clear stale optimistic status
      setThreadStatusOverride(undefined);
    }
  }, [thread.status, threadStatusOverride]);

  useEffect(() => {
    if (!triggerNodes.length) {
      // eslint-disable-next-line react-hooks/set-state-in-effect -- clear trigger selection when none available
      setSelectedTriggerId(undefined);
      return;
    }
    setSelectedTriggerId((prev) => {
      if (prev && triggerNodes.some((node) => node.id === prev)) {
        return prev;
      }
      return triggerNodes[0].id;
    });
  }, [triggerNodes, thread.id]);

  const effectiveThreadStatus = threadStatusOverride ?? thread.status;
  const isThreadRunning = effectiveThreadStatus === ThreadDtoStatusEnum.Running;
  const isThreadWaiting = effectiveThreadStatus === ThreadDtoStatusEnum.Waiting;
  const prevIsThreadRunningRef = useRef<boolean>(isThreadRunning);

  const scheduledResumeAt = thread.metadata?.scheduledResumeAt as
    | string
    | undefined;
  const waitReason = thread.metadata?.waitReason as string | undefined;
  const countdown = useCountdown(
    isThreadWaiting ? scheduledResumeAt : undefined,
  );

  const [resumingThread, setResumingThread] = useState(false);
  const [cancellingWait, setCancellingWait] = useState(false);

  // Use pending messages provided from the shared store
  const pendingMessages = useMemo(() => {
    if (isDraft) {
      return undefined;
    }
    return pendingMessagesProp && pendingMessagesProp.length > 0
      ? pendingMessagesProp
      : undefined;
  }, [pendingMessagesProp, isDraft]);

  // Send pending messages when thread completes (for wait_for_completion mode)
  // or after tool execution (for inject_after_tool_call mode)
  const sendPendingMessage = useCallback(
    async (message: PendingMessage) => {
      if (!selectedTriggerId || isDraft) {
        return;
      }

      const messageText = extractTextFromContentBlocks(message.content);
      const isStructured = Array.isArray(message.content);
      const now = new Date().toISOString();
      const optimisticMessageId = `optimistic-${Date.now()}-${Math.random().toString(36).substring(2, 11)}`;

      const optimisticMessage: ThreadMessageDto = {
        id: optimisticMessageId,
        threadId: thread.id,
        nodeId: selectedTriggerId,
        externalThreadId:
          thread.externalThreadId ?? selectedThreadExternalId ?? '',
        createdAt: now,
        updatedAt: now,
        message: {
          role: 'human',
          content: isStructured ? message.content : messageText,
        } as ThreadMessageDto['message'],
      };

      // Add optimistic message to both scopes
      onUpdateSharedMessages(thread.id, (prev) =>
        sortMessagesChronologically([...prev, optimisticMessage]),
      );
      onUpdateSharedMessages(
        thread.id,
        (prev) => sortMessagesChronologically([...prev, optimisticMessage]),
        selectedTriggerId,
      );

      try {
        const threadSubId = extractThreadSubId(
          thread.externalThreadId ?? selectedThreadExternalId,
        );
        const executeTriggerDto = {
          messages: (isStructured
            ? [{ content: message.content }]
            : [
                { content: [{ type: 'text' as const, text: messageText }] },
              ]) as ExecuteTriggerDtoMessagesInner[],
          async: true,
          ...(threadSubId ? { threadSubId } : {}),
        };
        await graphsApi.executeTrigger(
          graphId,
          selectedTriggerId,
          executeTriggerDto,
        );
      } catch (error) {
        console.error('Error sending pending message', error);

        // Remove optimistic message on error
        onUpdateSharedMessages(thread.id, (prev) =>
          prev.filter((msg) => msg.id !== optimisticMessageId),
        );
        onUpdateSharedMessages(
          thread.id,
          (prev) => prev.filter((msg) => msg.id !== optimisticMessageId),
          selectedTriggerId,
        );

        const errorMessage = extractApiErrorMessage(
          error,
          'Failed to send pending message',
        );
        toast.error(errorMessage);
      }
    },
    [
      selectedTriggerId,
      isDraft,
      thread.id,
      thread.externalThreadId,
      selectedThreadExternalId,
      onUpdateSharedMessages,
      graphId,
    ],
  );

  // Effect to send pending messages when thread transitions from Running to not-Running
  useEffect(() => {
    const wasRunning = prevIsThreadRunningRef.current;
    prevIsThreadRunningRef.current = isThreadRunning;

    // Only send pending messages when transitioning from running to not-running
    // and only in wait_for_completion mode
    if (
      wasRunning &&
      !isThreadRunning &&
      newMessageMode === 'wait_for_completion' &&
      pendingMessages &&
      pendingMessages.length > 0 &&
      onUpdatePendingMessages
    ) {
      // Send all pending messages
      pendingMessages.forEach((msg) => {
        sendPendingMessage(msg);
      });

      // Clear pending messages after sending
      onUpdatePendingMessages(thread.id, () => []);
      toast.success('Pending messages sent');
    }
  }, [
    isThreadRunning,
    pendingMessages,
    sendPendingMessage,
    onUpdatePendingMessages,
    thread.id,
    newMessageMode,
  ]);

  const handleStopThread = useCallback(async () => {
    if (isDraft) {
      return;
    }
    try {
      setStoppingThread(true);
      setThreadStatusOverride(ThreadDtoStatusEnum.Stopped);
      const response = await threadsApi.stopThread(thread.id);
      const stoppedThread = response.data;
      if (
        stoppedThread?.status &&
        stoppedThread.status !== ThreadDtoStatusEnum.Running
      ) {
        setThreadStatusOverride(stoppedThread.status);
      }
      toast.success('Thread stop requested');
    } catch (error) {
      console.error('Error stopping thread', error);
      toast.error(
        extractApiErrorMessage(error, 'Failed to stop thread execution'),
      );
      setThreadStatusOverride(undefined);
    } finally {
      setStoppingThread(false);
    }
  }, [isDraft, thread.id]);

  const handleResumeThread = useCallback(async () => {
    if (isDraft) {
      return;
    }
    try {
      setResumingThread(true);
      // TODO: replace with threadsApi.resumeThread() after pnpm generate:api
      await axios.post(`/api/v1/threads/${thread.id}/resume`, {});
      toast.success('Thread resume requested');
    } catch (error) {
      console.error('Error resuming thread', error);
      toast.error(extractApiErrorMessage(error, 'Failed to resume thread'));
    } finally {
      setResumingThread(false);
    }
  }, [isDraft, thread.id]);

  const handleCancelWait = useCallback(async () => {
    if (isDraft) {
      return;
    }
    try {
      setCancellingWait(true);
      // TODO: replace with threadsApi.cancelWait() after pnpm generate:api
      await axios.post(`/api/v1/threads/${thread.id}/cancel-wait`);
      toast.success('Wait cancelled');
    } catch (error) {
      console.error('Error cancelling wait', error);
      toast.error(extractApiErrorMessage(error, 'Failed to cancel wait'));
    } finally {
      setCancellingWait(false);
    }
  }, [isDraft, thread.id]);

  const handleSendMessage = useCallback(async () => {
    if (!selectedTriggerId || !messageInput.trim()) {
      toast.warning('Select a trigger and enter a message');
      return;
    }

    const messageText = messageInput.trim();

    // If thread is running, add to pending messages instead of sending immediately
    if (isThreadRunning && !isDraft && onUpdatePendingMessages) {
      const hasImages = imageAttachments.length > 0;
      const pendingMessage: PendingMessage = {
        role: 'human',
        content: hasImages
          ? buildContentBlocks(messageText, imageAttachments)
          : messageText,
      };

      onUpdatePendingMessages(thread.id, (prev) => [...prev, pendingMessage]);
      setMessageInput('');
      setImageAttachments([]);
      toast.info(
        newMessageMode === 'inject_after_tool_call'
          ? 'Message will be sent after next tool execution'
          : 'Message will be sent after agent completes current task',
      );
      return;
    }

    if (sendingRef.current) {
      return;
    }
    sendingRef.current = true;

    // Prepend repo context to the first message when a repo is selected
    const selectedRepo = selectedRepoId
      ? repos.find((r) => r.id === selectedRepoId)
      : undefined;
    const isFirstMessageWithRepo = isDraft && selectedRepo && !repoLocked;
    const repoSignature = selectedRepo
      ? `Repository: ${selectedRepo.owner}/${selectedRepo.repo}`
      : '';
    const alreadyHasRepo = repoSignature
      ? messageText.includes(repoSignature)
      : false;
    const effectiveMessageText =
      isFirstMessageWithRepo && !alreadyHasRepo
        ? `${messageText}\n\n\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n${repoSignature}, Branch: ${selectedRepo.defaultBranch}`
        : messageText;

    const hasImages = imageAttachments.length > 0;
    const messageContent = hasImages
      ? buildContentBlocks(effectiveMessageText, imageAttachments)
      : effectiveMessageText;
    const now = new Date().toISOString();
    const optimisticMessageId = `optimistic-${Date.now()}-${Math.random().toString(36).substring(2, 11)}`;

    const optimisticMessage: ThreadMessageDto = {
      id: optimisticMessageId,
      threadId: thread.id,
      nodeId: selectedTriggerId,
      externalThreadId:
        thread.externalThreadId ?? selectedThreadExternalId ?? '',
      createdAt: now,
      updatedAt: now,
      message: {
        role: 'human',
        content: messageContent,
      } as ThreadMessageDto['message'],
    };

    // Add optimistic message to both scopes
    onUpdateSharedMessages(thread.id, (prev) =>
      sortMessagesChronologically([...prev, optimisticMessage]),
    );
    onUpdateSharedMessages(
      thread.id,
      (prev) => sortMessagesChronologically([...prev, optimisticMessage]),
      selectedTriggerId,
    );

    setMessageInput('');
    setImageAttachments([]);

    // Lock the repo selector after first message is sent
    if (isFirstMessageWithRepo) {
      setRepoLocked(true);
    }

    try {
      setSendingMessage(true);
      const threadSubId = extractThreadSubId(
        thread.externalThreadId ?? selectedThreadExternalId,
      );
      const executeTriggerDto = {
        messages: (hasImages
          ? [{ content: messageContent }]
          : [
              {
                content: [
                  { type: 'text' as const, text: effectiveMessageText },
                ],
              },
            ]) as ExecuteTriggerDtoMessagesInner[],
        async: true,
        ...(threadSubId ? { threadSubId } : {}),
        ...(isFirstMessageWithRepo && selectedRepo
          ? {
              metadata: {
                repositoryId: selectedRepo.id,
                repositoryOwner: selectedRepo.owner,
                repositoryName: selectedRepo.repo,
                branch: selectedRepo.defaultBranch,
              },
            }
          : {}),
      };
      const response = await graphsApi.executeTrigger(
        graphId,
        selectedTriggerId,
        executeTriggerDto,
      );

      const returnedExternalThreadId = response.data?.externalThreadId;
      const shouldSelectNewThread =
        returnedExternalThreadId &&
        returnedExternalThreadId !== selectedThreadExternalId &&
        returnedExternalThreadId !== thread.externalThreadId;

      if (isDraft && returnedExternalThreadId && onDraftMessageSent) {
        pendingDraftExternalIdRef.current = returnedExternalThreadId;
        if (onRequestThreadSwitch) {
          onRequestThreadSwitch(returnedExternalThreadId);
        }
        setTimeout(async () => {
          if (
            pendingDraftExternalIdRef.current === returnedExternalThreadId &&
            onDraftMessageSent
          ) {
            try {
              const threadResponse = await threadsApi.getThreadByExternalId(
                returnedExternalThreadId,
              );
              const existingThread = threadResponse.data;
              if (existingThread) {
                onDraftMessageSent(existingThread);
                pendingDraftExternalIdRef.current = undefined;
              }
            } catch (error) {
              console.error('Error fetching thread by external ID:', error);
              toast.error(
                extractApiErrorMessage(
                  error,
                  'Failed to load thread after sending message',
                ),
              );
            }
          }
        }, 2000);
      } else if (onRequestThreadSwitch) {
        onRequestThreadSwitch(
          shouldSelectNewThread ? returnedExternalThreadId : null,
        );
      }

      toast.success('Message sent');
    } catch (error) {
      console.error('Error sending message', error);

      // Remove optimistic message on error
      onUpdateSharedMessages(thread.id, (prev) =>
        prev.filter((msg) => msg.id !== optimisticMessageId),
      );
      onUpdateSharedMessages(
        thread.id,
        (prev) => prev.filter((msg) => msg.id !== optimisticMessageId),
        selectedTriggerId,
      );

      const errorMessage = extractApiErrorMessage(
        error,
        'Failed to send message',
      );
      toast.error(errorMessage);
      setMessageInput(messageText);
    } finally {
      setSendingMessage(false);
      sendingRef.current = false;
    }
  }, [
    selectedTriggerId,
    messageInput,
    imageAttachments,
    graphId,
    thread.id,
    thread.externalThreadId,
    selectedThreadExternalId,
    onRequestThreadSwitch,
    isDraft,
    onDraftMessageSent,
    onUpdateSharedMessages,
    isThreadRunning,
    onUpdatePendingMessages,
    newMessageMode,
    repos,
    selectedRepoId,
    repoLocked,
  ]);

  useEffect(() => {
    if (externalThreadId && !selectedThreadExternalId) {
      // eslint-disable-next-line react-hooks/set-state-in-effect -- backfill external id once parent provides it
      setSelectedThreadExternalId(externalThreadId);
    }
  }, [externalThreadId, selectedThreadExternalId]);

  const triggerHelperText = templatesLoading
    ? 'Loading triggers...'
    : graphLoaded
      ? 'No trigger nodes available for this graph. Add a trigger node to send messages.'
      : 'Loading graph data...';

  // Memoize onLoadMoreMessages to prevent creating new function reference
  const memoizedOnLoadMoreMessages = useMemo(
    () => (hasMoreMessages ? onLoadMoreMessages : undefined),
    [hasMoreMessages, onLoadMoreMessages],
  );

  // Memoize input change handler to prevent recreation
  const handleInputChange = useCallback(
    (e: React.ChangeEvent<HTMLTextAreaElement>) => {
      setMessageInput(e.target.value);
      const textarea = e.target;
      textarea.style.height = 'auto';
      const lineHeight =
        parseInt(getComputedStyle(textarea).lineHeight, 10) || 20;
      const maxHeight = lineHeight * 7;
      textarea.style.height = `${Math.min(textarea.scrollHeight, maxHeight)}px`;
      textarea.style.overflowY =
        textarea.scrollHeight > maxHeight ? 'auto' : 'hidden';
    },
    [],
  );

  // Reset textarea height when input is cleared programmatically
  useEffect(() => {
    if (!messageInput && textareaRef.current) {
      textareaRef.current.style.height = 'auto';
      textareaRef.current.style.overflowY = 'hidden';
    }
  }, [messageInput]);

  // Paste handler: intercept image items from clipboard
  const handlePaste = useCallback(
    async (e: React.ClipboardEvent) => {
      const items = Array.from(e.clipboardData.items);
      const imageItems = items.filter((item) => item.type.startsWith('image/'));
      if (imageItems.length === 0) {
        return; // let default paste handle text
      }

      e.preventDefault();
      const remainingSlots = MAX_IMAGES_PER_MESSAGE - imageAttachments.length;
      const itemsToProcess = imageItems.slice(0, remainingSlots);
      if (imageItems.length > remainingSlots) {
        toast.error(`Maximum ${MAX_IMAGES_PER_MESSAGE} images per message`);
      }

      const newAttachments: ImageAttachment[] = [];
      for (const item of itemsToProcess) {
        const file = item.getAsFile();
        if (!file) {
          continue;
        }
        const error = validateImageFile(file);
        if (error) {
          toast.error(error);
          continue;
        }
        const dataUrl = await fileToDataUrl(file);
        newAttachments.push({
          id: crypto.randomUUID(),
          dataUrl,
          fileName: file.name || 'pasted-image',
          sizeBytes: file.size,
        });
      }
      if (newAttachments.length > 0) {
        setImageAttachments((prev) =>
          [...prev, ...newAttachments].slice(0, MAX_IMAGES_PER_MESSAGE),
        );
      }
    },
    [imageAttachments.length],
  );

  // Memoize input enter handler
  const handleInputEnter = useCallback(
    (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
      if (!e.shiftKey && e.key === 'Enter') {
        e.preventDefault();
        handleSendMessage();
      }
    },
    [handleSendMessage],
  );

  const selectedRepoDisplay = useMemo(() => {
    if (!selectedRepoId) {
      return null;
    }
    const repo = repos.find((r) => r.id === selectedRepoId);
    if (!repo) {
      return null;
    }
    return { owner: repo.owner, name: repo.repo, branch: repo.defaultBranch };
  }, [selectedRepoId, repos]);

  const handleRepoChange = useCallback(
    (value: string | undefined) => {
      if (!repoLocked) {
        setSelectedRepoId(value);
        setRepoPopoverOpen(false);
      }
    },
    [repoLocked],
  );

  const repoPopoverContent = useMemo(() => {
    if (reposLoading) {
      return (
        <div className="p-2 text-center">
          <span className="text-xs text-muted-foreground">Loading\u2026</span>
        </div>
      );
    }
    if (repos.length === 0) {
      if (!systemSettings.githubAppEnabled) {
        return (
          <div className="p-3 min-w-[220px]">
            <p className="text-xs text-muted-foreground mb-1.5">
              No GitHub App connected.
            </p>
            <a
              href="/settings/integrations"
              className="text-xs text-primary underline-offset-4 hover:underline">
              Configure integrations
            </a>
          </div>
        );
      }
      return (
        <div className="p-3 min-w-[220px]">
          <p className="text-xs text-muted-foreground mb-1.5">
            No repositories synced yet.
          </p>
          <a
            href="/repositories"
            className="text-xs text-primary underline-offset-4 hover:underline">
            Go to repositories
          </a>
        </div>
      );
    }
    const filteredRepos = repoSearch
      ? repos.filter(
          (r) =>
            r.owner?.toLowerCase().includes(repoSearch.toLowerCase()) ||
            r.repo?.toLowerCase().includes(repoSearch.toLowerCase()),
        )
      : repos;
    return (
      <div className="min-w-[240px] flex flex-col gap-0.5">
        <div className="px-1 pt-1 pb-0.5">
          <Input
            placeholder="Search repos..."
            value={repoSearch}
            onChange={(e) => setRepoSearch(e.target.value)}
            className="h-7 text-xs"
          />
        </div>
        {selectedRepoId && (
          <Button
            variant="ghost"
            size="sm"
            className="w-full justify-start text-[11px] text-muted-foreground h-7 px-2"
            onClick={() => handleRepoChange(undefined)}>
            Clear selection
          </Button>
        )}
        {filteredRepos.length === 0 ? (
          <div className="p-2">
            <span className="text-xs text-muted-foreground">
              No repos match &quot;{repoSearch}&quot;
            </span>
          </div>
        ) : (
          <div className="max-h-[220px] overflow-y-auto flex flex-col gap-0.5">
            {filteredRepos.map((repo) => (
              <Button
                key={repo.id}
                variant="ghost"
                size="sm"
                className={cn(
                  'w-full justify-start text-left h-auto py-1.5 px-2 leading-snug',
                  repo.id === selectedRepoId ? 'bg-accent/50' : '',
                )}
                onClick={() => handleRepoChange(repo.id)}>
                <Github className="h-3 w-3 shrink-0 text-muted-foreground" />
                <span className="font-medium text-xs">
                  {repo.owner}/{repo.repo}
                </span>
                {repo.defaultBranch && (
                  <Badge
                    variant="outline"
                    className="text-[9px] px-1.5 py-0 rounded-full gap-0.5">
                    <GitBranch className="h-2.5 w-2.5" />
                    {repo.defaultBranch}
                  </Badge>
                )}
              </Button>
            ))}
          </div>
        )}
      </div>
    );
  }, [
    repos,
    reposLoading,
    selectedRepoId,
    handleRepoChange,
    systemSettings,
    repoSearch,
  ]);

  const WaitingBanner = useMemo(() => {
    if (!isThreadWaiting) {
      return null;
    }
    return (
      <div className="px-4 py-2.5 border-t border-purple-200 bg-purple-50 dark:border-purple-800 dark:bg-purple-950/30">
        <div className="flex items-center justify-between gap-3">
          <div className="flex items-center gap-2 min-w-0">
            <Timer className="h-4 w-4 shrink-0 text-purple-600 dark:text-purple-400" />
            <div className="flex flex-col min-w-0">
              <span className="text-sm font-medium text-purple-700 dark:text-purple-300">
                Waiting
                {waitReason ? ` \u2014 ${waitReason}` : ''}
              </span>
              {countdown !== null && (
                <span className="text-xs text-purple-600/80 dark:text-purple-400/80">
                  {countdown > 0
                    ? `Resuming in ${formatCountdown(countdown)}`
                    : 'Resuming soon'}
                </span>
              )}
            </div>
          </div>
          <div className="flex items-center gap-1.5 shrink-0">
            <Button
              variant="outline"
              size="sm"
              className="h-7 text-xs border-purple-300 text-purple-700 hover:bg-purple-100 dark:border-purple-700 dark:text-purple-300 dark:hover:bg-purple-900"
              onClick={handleResumeThread}
              disabled={resumingThread}>
              {resumingThread ? (
                <Loader2 className="h-3 w-3 animate-spin" />
              ) : (
                <Play className="h-3 w-3" />
              )}
              Resume Now
            </Button>
            <Button
              variant="ghost"
              size="sm"
              className="h-7 text-xs text-muted-foreground hover:text-destructive"
              onClick={handleCancelWait}
              disabled={cancellingWait}>
              {cancellingWait ? (
                <Loader2 className="h-3 w-3 animate-spin" />
              ) : (
                <CircleX className="h-3 w-3" />
              )}
              Cancel
            </Button>
          </div>
        </div>
      </div>
    );
  }, [
    isThreadWaiting,
    waitReason,
    countdown,
    handleResumeThread,
    handleCancelWait,
    resumingThread,
    cancellingWait,
  ]);

  // Extract input section to prevent rerenders of ThreadMessagesView when typing
  const ChatInputSection = useMemo(
    () => (
      <div className="px-4 py-3 border-t border-border bg-card">
        {triggerNodes.length > 0 && !graphIsRunning ? (
          <div className="flex items-center gap-2 rounded-lg border border-amber-500/30 bg-amber-500/5 px-3 py-2.5">
            <AlertTriangle className="h-4 w-4 shrink-0 text-amber-500" />
            <span className="text-sm text-muted-foreground">
              Graph is not running. Start the graph to send messages.
            </span>
          </div>
        ) : triggerNodes.length > 0 ? (
          <div className="flex flex-col gap-1.5">
            {/* Main row: textarea + action buttons */}
            <div className="flex items-end gap-2">
              <Textarea
                ref={textareaRef}
                placeholder="Type your message..."
                value={messageInput}
                onChange={handleInputChange}
                onKeyDown={handleInputEnter}
                onPaste={handlePaste}
                disabled={sendingMessage || !selectedTriggerId}
                className="flex-1 resize-none min-h-[36px] overflow-hidden"
                rows={1}
              />
              {!isDraft && isThreadRunning && (
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button
                      variant="outline"
                      size="icon"
                      className="shrink-0 border-destructive text-destructive hover:bg-destructive/10"
                      onClick={handleStopThread}
                      disabled={stoppingThread}
                      aria-label="Stop thread execution">
                      {stoppingThread ? (
                        <Loader2 className="h-4 w-4 animate-spin" />
                      ) : (
                        <Square className="h-4 w-4" />
                      )}
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent>Stop thread execution</TooltipContent>
                </Tooltip>
              )}
              <Button
                onClick={handleSendMessage}
                disabled={
                  !messageInput.trim() ||
                  !selectedTriggerId ||
                  templatesLoading ||
                  sendingMessage
                }
                className="shrink-0">
                {sendingMessage ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : (
                  <Send className="h-4 w-4" />
                )}
                Send
              </Button>
            </div>
            {/* Image attachment previews */}
            {imageAttachments.length > 0 && (
              <div className="flex gap-2 px-1 py-1.5 flex-wrap items-center">
                {imageAttachments.map((img) => (
                  <div key={img.id} className="relative group">
                    <img
                      src={img.dataUrl}
                      alt={img.fileName}
                      className="h-16 w-16 object-cover rounded-md border border-border"
                    />
                    <button
                      type="button"
                      onClick={() =>
                        setImageAttachments((prev) =>
                          prev.filter((a) => a.id !== img.id),
                        )
                      }
                      className="absolute -top-1.5 -right-1.5 h-5 w-5 rounded-full bg-destructive text-destructive-foreground flex items-center justify-center text-xs opacity-0 group-hover:opacity-100 transition-opacity">
                      <CircleX className="h-3.5 w-3.5" />
                    </button>
                  </div>
                ))}
                <span className="text-[11px] text-muted-foreground">
                  {imageAttachments.length}/{MAX_IMAGES_PER_MESSAGE} images
                </span>
              </div>
            )}
            {/* Vision model warning */}
            {imageAttachments.length > 0 && (
              <div className="flex items-center gap-1.5 px-1 text-[11px] text-amber-600 dark:text-amber-400">
                <AlertTriangle className="h-3 w-3 shrink-0" />
                <span>
                  Images require a vision-capable model (e.g. GPT-4o, Claude
                  Sonnet). Non-vision models will ignore images.
                </span>
              </div>
            )}
            {/* Sub row: small text links for trigger + repo */}
            <div className="flex items-center gap-3 pl-0.5">
              <DropdownMenu>
                <DropdownMenuTrigger className="flex items-center gap-1 px-2 py-1 rounded-md bg-muted/60 hover:bg-muted text-[11px] text-muted-foreground hover:text-foreground transition-colors outline-none">
                  <Zap className="w-3 h-3" />
                  <span>
                    {triggerNodes.find((t) => t.id === selectedTriggerId)
                      ?.name || 'Select'}
                  </span>
                  <ChevronDown className="w-3 h-3" />
                </DropdownMenuTrigger>
                <DropdownMenuContent>
                  {triggerNodes.map((trigger) => (
                    <DropdownMenuItem
                      key={trigger.id}
                      onClick={() => setSelectedTriggerId(trigger.id)}>
                      {trigger.name}
                    </DropdownMenuItem>
                  ))}
                </DropdownMenuContent>
              </DropdownMenu>
              {/* Repo selector: interactive only for draft threads, static for locked threads */}
              {isDraft && !repoLocked ? (
                <Popover
                  open={repoPopoverOpen}
                  onOpenChange={(open) => {
                    setRepoPopoverOpen(open);
                    if (!open) {
                      setRepoSearch('');
                    }
                  }}>
                  <PopoverTrigger asChild>
                    <PickerTrigger className="text-[11px] text-muted-foreground gap-1 px-2 py-1">
                      <Github className="w-3 h-3" />
                      <span>
                        {selectedRepoDisplay
                          ? `${selectedRepoDisplay.owner}/${selectedRepoDisplay.name}`
                          : 'Select repo'}
                      </span>
                    </PickerTrigger>
                  </PopoverTrigger>
                  <PopoverContent
                    side="top"
                    align="start"
                    className="w-auto p-1">
                    {repoPopoverContent}
                  </PopoverContent>
                </Popover>
              ) : (
                selectedRepoDisplay && (
                  <span className="flex items-center gap-1 px-2 py-1 rounded-md bg-muted/60 text-[11px] text-muted-foreground select-none">
                    <Github className="w-3 h-3" />
                    <span>
                      {selectedRepoDisplay.owner}/{selectedRepoDisplay.name}
                    </span>
                    <Badge
                      variant="outline"
                      className="text-[9px] px-1.5 py-0 rounded-full gap-0.5 ml-0.5">
                      <GitBranch className="h-2.5 w-2.5" />
                      {selectedRepoDisplay.branch}
                    </Badge>
                  </span>
                )
              )}
            </div>
          </div>
        ) : (
          <div className="text-center py-2">
            <span className="text-sm text-muted-foreground">
              {triggerHelperText}
            </span>
          </div>
        )}
      </div>
    ),
    [
      triggerNodes,
      selectedTriggerId,
      messageInput,
      imageAttachments,
      sendingMessage,
      isDraft,
      isThreadRunning,
      stoppingThread,
      templatesLoading,
      graphIsRunning,
      triggerHelperText,
      handleInputChange,
      handleInputEnter,
      handlePaste,
      handleStopThread,
      handleSendMessage,
      selectedRepoDisplay,
      repoLocked,
      repoPopoverOpen,
      repoPopoverContent,
      setRepoSearch,
    ],
  );

  return (
    <div style={style} className="flex flex-col flex-1 min-h-0 overflow-hidden">
      <div className="flex-1 min-h-0 rounded-lg flex flex-col overflow-hidden">
        <ThreadMessagesView
          messages={messages}
          messagesLoading={messagesLoading}
          selectedThreadId={thread.id}
          isAgentNode
          onLoadMoreMessages={memoizedOnLoadMoreMessages}
          hasMoreMessages={hasMoreMessages}
          loadingMore={loadingMoreMessages}
          isNodeRunning={isThreadRunning}
          isThreadStopped={
            effectiveThreadStatus === ThreadDtoStatusEnum.Stopped
          }
          currentThreadLastRunId={thread.lastRunId}
          nodeDisplayNames={nodeDisplayNames}
          showNodeHeadings
          pendingMessages={pendingMessages}
          newMessageMode={newMessageMode}
          stopReason={thread.stopReason}
          stopCostUsd={
            typeof thread.metadata?.stopCostUsd === 'number' &&
            Number.isFinite(thread.metadata.stopCostUsd)
              ? thread.metadata.stopCostUsd
              : null
          }
        />
      </div>

      {WaitingBanner}
      {ChatInputSection}
    </div>
  );
};

export default ThreadChatPanel;
