// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest';

import { cleanup, render, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

const { getAllProjects } = vi.hoisted(() => ({ getAllProjects: vi.fn() }));
vi.mock('../api', () => ({ projectsApi: { getAllProjects } }));

// ProjectProvider subscribes to its project room via useWebSocket; stub it so
// these tests don't open a real socket.
vi.mock('./useWebSocket', () => ({
  useWebSocket: vi.fn(() => ({
    isConnected: false,
    subscribeToGraph: vi.fn(),
    unsubscribeFromGraph: vi.fn(),
    subscribeToProject: vi.fn(),
    unsubscribeFromProject: vi.fn(),
    on: vi.fn(() => vi.fn()),
    off: vi.fn(),
  })),
}));

import React from 'react';
import { MemoryRouter, Route, Routes } from 'react-router';

import type { ProjectDto } from '../autogenerated';
import { ProjectProvider } from '../contexts/ProjectContext';
import { useCurrentProject } from './useCurrentProject';

const VALID = '11111111-1111-4111-8111-111111111111';
const MISSING = '99999999-9999-4999-8999-999999999999';

const makeProject = (id: string): ProjectDto => ({
  id,
  name: 'Project',
  description: null,
  icon: null,
  color: '#3B82F6',
  settings: {},
  costLimitUsd: null,
  createdBy: 'user-1',
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
  graphCount: 0,
  threadCount: 0,
});

const ChatsProbe = () => {
  const { projectId, currentProject } = useCurrentProject();
  return (
    <div
      data-testid="chats"
      data-project={projectId ?? ''}
      data-current={currentProject?.id ?? ''}
    />
  );
};

const renderAt = (path: string) =>
  render(
    <MemoryRouter initialEntries={[path]}>
      <ProjectProvider>
        <Routes>
          <Route
            path="/projects"
            element={<div data-testid="projects-list" />}
          />
          <Route path="/projects/:projectId/chats" element={<ChatsProbe />} />
        </Routes>
      </ProjectProvider>
    </MemoryRouter>,
  );

describe('useCurrentProject — invalid project URL', () => {
  beforeEach(() => {
    localStorage.clear();
    getAllProjects.mockReset();
  });

  afterEach(() => {
    cleanup();
  });

  it('redirects to /projects without an infinite update loop when the URL project is not in the list', async () => {
    // A deleted / inaccessible project in the URL used to make useCurrentProject
    // (URL → state) and ProjectProvider (state-not-in-list → reset to first)
    // fight forever → "Maximum update depth exceeded". The guard must redirect
    // instead. Rendering without the guard throws here.
    getAllProjects.mockResolvedValueOnce({ data: [makeProject(VALID)] });

    const { getByTestId } = renderAt(`/projects/${MISSING}/chats`);

    await waitFor(() => {
      expect(getByTestId('projects-list')).toBeInTheDocument();
    });
  });

  it('keeps a valid project URL and resolves currentProject', async () => {
    getAllProjects.mockResolvedValueOnce({ data: [makeProject(VALID)] });

    const { getByTestId } = renderAt(`/projects/${VALID}/chats`);

    await waitFor(() => {
      expect(getByTestId('chats').dataset.current).toBe(VALID);
    });
    expect(getByTestId('chats').dataset.project).toBe(VALID);
  });
});
