// @vitest-environment jsdom
import { act, renderHook, waitFor } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';

import {
  type GitRepositoryDto,
  GitRepositoryDtoProviderEnum,
  type RepoIndexDto,
  RepoIndexDtoStatusEnum,
} from '../autogenerated';

const { getRepositories, getRepoIndexes } = vi.hoisted(() => ({
  getRepositories: vi.fn(),
  getRepoIndexes: vi.fn(),
}));

vi.mock('../api', () => ({
  gitRepositoriesApi: { getRepositories, getRepoIndexes },
}));

const makeRepo = (i: number): GitRepositoryDto => ({
  id: `repo-${i}`,
  owner: 'octo',
  repo: `r${i}`,
  url: `https://github.com/octo/r${i}`,
  provider: GitRepositoryDtoProviderEnum.Github,
  defaultBranch: 'main',
  createdBy: 'user-1',
  projectId: null,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
});

const makeIndex = (repositoryId: string, branch: string): RepoIndexDto => ({
  id: `idx-${repositoryId}`,
  repositoryId,
  repoUrl: `https://github.com/octo/${repositoryId}`,
  branch,
  status: RepoIndexDtoStatusEnum.Completed,
  qdrantCollection: 'col',
  lastIndexedCommit: null,
  embeddingModel: null,
  vectorSize: null,
  chunkingSignatureHash: null,
  estimatedTokens: 0,
  indexedTokens: 0,
  errorMessage: null,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
});

// Paginated repo source: 150 repos returned as a full page (100) + a short
// page (50). limit is the 5th positional arg, offset the 6th.
const repoPage = async (..._args: unknown[]) => {
  const offset = _args[5] as number;
  const all = Array.from({ length: 150 }, (_, i) => makeRepo(i));
  return { data: all.slice(offset, offset + 100) };
};

const loadHook = async () => {
  const { useRepositories } = await import('./useRepositories');
  return useRepositories;
};

describe('useRepositories', () => {
  beforeEach(() => {
    vi.resetModules();
    getRepositories.mockReset();
    getRepoIndexes.mockReset();
  });

  it('paginates past the 50-item default to fetch the full set', async () => {
    getRepositories.mockImplementation(repoPage);
    getRepoIndexes.mockResolvedValue({ data: [makeIndex('repo-0', 'main')] });

    const useRepositories = await loadHook();
    const { result } = renderHook(() => useRepositories());

    await waitFor(() => expect(result.current.loading).toBe(false));

    expect(result.current.repositories).toHaveLength(150);
    // Two pages requested: offset 0 then offset 100.
    expect(getRepositories).toHaveBeenCalledTimes(2);
    expect(getRepositories.mock.calls[0][5]).toBe(0);
    expect(getRepositories.mock.calls[1][5]).toBe(100);
    // A short final page (50 < 100) stops the loop — no third request.
    expect(result.current.error).toBeNull();
  });

  it('joins each repo with its default-branch index', async () => {
    getRepositories.mockImplementation(repoPage);
    getRepoIndexes.mockResolvedValue({ data: [makeIndex('repo-0', 'main')] });

    const useRepositories = await loadHook();
    const { result } = renderHook(() => useRepositories());

    await waitFor(() => expect(result.current.loading).toBe(false));

    const repo0 = result.current.repositories.find((r) => r.id === 'repo-0');
    const repo1 = result.current.repositories.find((r) => r.id === 'repo-1');
    expect(repo0?.index?.status).toBe(RepoIndexDtoStatusEnum.Completed);
    expect(repo1?.index).toBeUndefined();
  });

  it('serves cached rows on remount without a loading flash', async () => {
    getRepositories.mockImplementation(repoPage);
    getRepoIndexes.mockResolvedValue({ data: [] });

    const useRepositories = await loadHook();
    const first = renderHook(() => useRepositories());
    await waitFor(() => expect(first.result.current.loading).toBe(false));
    first.unmount();

    // Second mount of the SAME module: cache is warm, so the first render
    // already has data and never enters the loading state.
    const second = renderHook(() => useRepositories());
    expect(second.result.current.loading).toBe(false);
    expect(second.result.current.repositories).toHaveLength(150);
  });

  it('write-through setRepositories keeps the cache consistent across mounts', async () => {
    getRepositories.mockImplementation(repoPage);
    getRepoIndexes.mockResolvedValue({ data: [] });

    const useRepositories = await loadHook();
    const first = renderHook(() => useRepositories());
    await waitFor(() => expect(first.result.current.loading).toBe(false));

    act(() => {
      first.result.current.setRepositories((prev) => prev.slice(0, 1));
    });
    expect(first.result.current.repositories).toHaveLength(1);
    first.unmount();

    const second = renderHook(() => useRepositories());
    expect(second.result.current.repositories).toHaveLength(1);
  });

  it('surfaces a blocking error only on a cold load', async () => {
    getRepositories.mockRejectedValue(new Error('network down'));
    getRepoIndexes.mockResolvedValue({ data: [] });

    const useRepositories = await loadHook();
    const { result } = renderHook(() => useRepositories());

    await waitFor(() => expect(result.current.loading).toBe(false));
    expect(result.current.error).not.toBeNull();
    expect(result.current.repositories).toHaveLength(0);
  });
});
