import { useCallback, useEffect, useState } from 'react';

import { gitRepositoriesApi } from '../api';
import type { GitRepositoryDto, RepoIndexDto } from '../autogenerated';
import type { Repository } from '../components/ui/repo-card';
import { extractApiErrorMessage } from '../utils/errors';

// The list endpoints cap `limit` at 100, so we page through the full set
// instead of relying on the server default (50) that silently truncated the list.
const PAGE_SIZE = 100;

// Module-level cache: survives unmount so navigating away and back renders
// instantly while a background refresh keeps the data fresh
// (stale-while-revalidate, mirroring `useSystemSettings`).
let cachedRepositories: Repository[] | null = null;

const indexKey = (repositoryId: string, branch: string): string =>
  `${repositoryId}::${branch}`;

async function fetchAllPages<T>(
  fetchPage: (limit: number, offset: number) => Promise<T[]>,
): Promise<T[]> {
  const all: T[] = [];
  let offset = 0;
  for (;;) {
    const page = await fetchPage(PAGE_SIZE, offset);
    all.push(...page);
    if (page.length < PAGE_SIZE) {
      break;
    }
    offset += PAGE_SIZE;
  }
  return all;
}

function mergeReposWithIndexes(
  repos: GitRepositoryDto[],
  indexes: RepoIndexDto[],
): Repository[] {
  const indexByKey = new Map<string, RepoIndexDto>();
  for (const idx of indexes) {
    indexByKey.set(indexKey(idx.repositoryId, idx.branch), idx);
  }
  return repos.map((repo) => ({
    ...repo,
    index: indexByKey.get(indexKey(repo.id, repo.defaultBranch)),
  }));
}

export interface UseRepositoriesResult {
  repositories: Repository[];
  loading: boolean;
  error: string | null;
  /** Re-fetch the full set from the server and refresh the cache. */
  refetch: () => Promise<void>;
  /** Write-through setter so optimistic local mutations stay cached. */
  setRepositories: (
    value: Repository[] | ((prev: Repository[]) => Repository[]),
  ) => void;
}

/**
 * Loads every repository (paginating past the server's 50-item default) joined
 * with its default-branch index, and caches the result across mounts. The page
 * does client-side search / sort / aggregate counts over the whole set, so it
 * genuinely needs all rows in memory.
 */
export const useRepositories = (): UseRepositoriesResult => {
  const [repositories, setRepositoriesState] = useState<Repository[]>(
    cachedRepositories ?? [],
  );
  const [loading, setLoading] = useState(!cachedRepositories);
  const [error, setError] = useState<string | null>(null);

  const setRepositories = useCallback(
    (value: Repository[] | ((prev: Repository[]) => Repository[])) => {
      setRepositoriesState((prev) => {
        const next = typeof value === 'function' ? value(prev) : value;
        cachedRepositories = next;
        return next;
      });
    },
    [],
  );

  const refetch = useCallback(async () => {
    try {
      const [repos, indexes] = await Promise.all([
        fetchAllPages<GitRepositoryDto>(async (limit, offset) => {
          const res = await gitRepositoriesApi.getRepositories(
            undefined,
            undefined,
            undefined,
            undefined,
            limit,
            offset,
          );
          return res.data || [];
        }),
        fetchAllPages<RepoIndexDto>(async (limit, offset) => {
          const res = await gitRepositoriesApi.getRepoIndexes(
            undefined,
            undefined,
            undefined,
            undefined,
            limit,
            offset,
          );
          return res.data || [];
        }),
      ]);

      const merged = mergeReposWithIndexes(repos, indexes);
      cachedRepositories = merged;
      setRepositoriesState(merged);
      setError(null);
    } catch (e) {
      console.error('Error fetching repositories:', e);
      // Only block the page on a cold load; a failed background refresh
      // keeps showing the cached rows.
      if (!cachedRepositories) {
        setError(extractApiErrorMessage(e, 'Failed to load repositories'));
      }
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect -- refetch is async; setState fires after awaits, not synchronously in the effect body
    void refetch();
  }, [refetch]);

  return { repositories, loading, error, refetch, setRepositories };
};
