// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest';

import { cleanup, render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

// ── Hoisted mocks — vi.hoisted() runs before all imports, satisfying ESM hoisting ──

const {
  navigate,
  toast,
  createProject,
  updateProject,
  createGraph,
  contextMock,
} = vi.hoisted(() => {
  const navigate = vi.fn();
  const toast = { success: vi.fn(), error: vi.fn() };
  const createProject = vi.fn();
  const updateProject = vi.fn();
  const createGraph = vi.fn();
  const contextMock = {
    projects: [] as unknown[],
    loading: false,
    loadProjects: vi.fn(),
    currentProjectId: null as string | null,
    setCurrentProjectId: vi.fn(),
  };
  return {
    navigate,
    toast,
    createProject,
    updateProject,
    createGraph,
    contextMock,
  };
});

vi.mock('react-router', () => ({ useNavigate: () => navigate }));
vi.mock('sonner', () => ({ toast }));
vi.mock('../../api', () => ({
  projectsApi: { createProject, updateProject },
  graphsApi: { createGraph },
}));
vi.mock('../../contexts/ProjectContext', () => ({
  useProjectContext: () => contextMock,
}));

import React from 'react';

import type { ProjectDto } from '../../autogenerated';
import { CreateProjectPage } from './create';

const makeProject = (overrides: Partial<ProjectDto> = {}): ProjectDto => ({
  id: 'p-new',
  name: 'My Project',
  description: null,
  icon: null,
  color: '#3B82F6',
  settings: {},
  costLimitUsd: null,
  createdBy: 'u-1',
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
  graphCount: 0,
  threadCount: 0,
  ...overrides,
});

const completeStep1 = async (
  user: ReturnType<typeof userEvent.setup>,
  projectName = 'My Project',
) => {
  const nameInput = screen.getByPlaceholderText('My First Project');
  await user.clear(nameInput);
  await user.type(nameInput, projectName);
  await user.click(screen.getByRole('button', { name: /Create Project/i }));
};

beforeEach(() => {
  vi.clearAllMocks();
  contextMock.loading = false;
  contextMock.loadProjects = vi.fn().mockResolvedValue(undefined);
});

afterEach(() => {
  cleanup();
});

describe('CreateProjectPage', () => {
  it('renders skeleton while projectsLoading=true', () => {
    contextMock.loading = true;
    render(<CreateProjectPage />);
    expect(screen.queryByText('Create your first project')).toBeNull();
  });

  it('renders step 1 (Project) when not loading', () => {
    render(<CreateProjectPage />);
    expect(screen.getByText('Create your first project')).toBeInTheDocument();
    expect(
      screen.getByRole('button', { name: /Create Project/i }),
    ).toBeInTheDocument();
  });

  it('"Create Project" button is disabled until name is non-empty', async () => {
    const user = userEvent.setup();
    render(<CreateProjectPage />);

    const btn = screen.getByRole('button', { name: /Create Project/i });
    expect(btn).toBeDisabled();

    await user.type(screen.getByPlaceholderText('My First Project'), 'x');
    expect(btn).not.toBeDisabled();
  });

  it('submits step 1: createProject with trimmed payload, then loadProjects, then advances to step 2', async () => {
    const user = userEvent.setup();
    createProject.mockResolvedValueOnce({ data: makeProject({ id: 'p-new' }) });

    render(<CreateProjectPage />);
    await user.type(
      screen.getByPlaceholderText('My First Project'),
      '  My Project  ',
    );
    await user.click(screen.getByRole('button', { name: /Create Project/i }));

    expect(createProject).toHaveBeenCalledWith(
      expect.objectContaining({
        name: 'My Project',
        description: null,
        icon: null,
        color: '#3B82F6',
      }),
    );
    expect(contextMock.loadProjects).toHaveBeenCalled();
    expect(
      await screen.findByText('Create your first graph'),
    ).toBeInTheDocument();
  });

  it('after step 1 succeeds, the step indicator marks step 1 complete (Check icon) and step 2 active', async () => {
    const user = userEvent.setup();
    createProject.mockResolvedValueOnce({ data: makeProject({ id: 'p-new' }) });

    const { container } = render(<CreateProjectPage />);
    await completeStep1(user);

    await screen.findByText('Create your first graph');

    // Lucide Check renders an svg with class containing "lucide-check"
    const checkIcon = container.querySelector('[class*="lucide-check"]');
    expect(checkIcon).not.toBeNull();

    // The step-1 indicator circle must no longer have "1" as its sole text
    const stepIndicators = container.querySelectorAll('.w-8.h-8.rounded-full');
    const firstIndicatorText = stepIndicators[0]?.textContent?.trim();
    expect(firstIndicatorText).not.toBe('1');
  });

  it('on step 1 API failure: toast.error fired, stays on step 1, no advance', async () => {
    const user = userEvent.setup();
    createProject.mockRejectedValueOnce(new Error('boom'));

    render(<CreateProjectPage />);
    await completeStep1(user);

    expect(toast.error).toHaveBeenCalledWith(expect.stringContaining('boom'));
    expect(screen.queryByText('Create your first graph')).toBeNull();
    expect(screen.getByText('Create your first project')).toBeInTheDocument();
  });

  it('errorFields-shaped failure on step 1: no toast, no advance', async () => {
    const user = userEvent.setup();
    createProject.mockRejectedValueOnce({
      errorFields: [{ name: ['name'], errors: ['too short'] }],
    });

    render(<CreateProjectPage />);
    await completeStep1(user);

    expect(toast.error).not.toHaveBeenCalled();
    expect(screen.queryByText('Create your first graph')).toBeNull();
  });

  it('step 2 "Create Graph" button is disabled until graph name is non-empty', async () => {
    const user = userEvent.setup();
    createProject.mockResolvedValueOnce({ data: makeProject({ id: 'p-new' }) });

    render(<CreateProjectPage />);
    await completeStep1(user);
    await screen.findByText('Create your first graph');

    const createGraphBtn = screen.getByRole('button', {
      name: /Create Graph/i,
    });
    expect(createGraphBtn).toBeDisabled();

    await user.type(screen.getByPlaceholderText('My First Graph'), 'x');
    expect(createGraphBtn).not.toBeDisabled();
  });

  it('submits step 2: createGraph with x-project-id header, then navigates to /projects/<id>/graphs/<id> with replace:true', async () => {
    const user = userEvent.setup();
    createProject.mockResolvedValueOnce({ data: makeProject({ id: 'p-new' }) });
    createGraph.mockResolvedValueOnce({ data: { id: 'g-1' } });

    render(<CreateProjectPage />);
    await completeStep1(user);
    await screen.findByText('Create your first graph');

    await user.type(screen.getByPlaceholderText('My First Graph'), 'My Graph');
    await user.click(screen.getByRole('button', { name: /Create Graph/i }));

    expect(createGraph).toHaveBeenCalledWith(
      expect.objectContaining({
        name: 'My Graph',
        description: null,
        schema: { nodes: [], edges: [] },
      }),
      { headers: { 'x-project-id': 'p-new' } },
    );
    expect(navigate).toHaveBeenCalledWith('/projects/p-new/graphs/g-1', {
      replace: true,
    });
  });

  it('on step 2 API failure: toast.error fired, stays on step 2', async () => {
    const user = userEvent.setup();
    createProject.mockResolvedValueOnce({ data: makeProject({ id: 'p-new' }) });
    createGraph.mockRejectedValueOnce(new Error('graph-boom'));

    render(<CreateProjectPage />);
    await completeStep1(user);
    await screen.findByText('Create your first graph');

    await user.type(screen.getByPlaceholderText('My First Graph'), 'My Graph');
    await user.click(screen.getByRole('button', { name: /Create Graph/i }));

    expect(toast.error).toHaveBeenCalled();
    expect(screen.getByText('Create your first graph')).toBeInTheDocument();
    expect(navigate).not.toHaveBeenCalled();
  });

  it('clicking Back on step 2 returns to step 1 with project values re-populated from createdProject', async () => {
    const user = userEvent.setup();
    createProject.mockResolvedValueOnce({
      data: makeProject({ id: 'p-new', name: 'My Project' }),
    });

    render(<CreateProjectPage />);
    await completeStep1(user, 'My Project');
    await screen.findByText('Create your first graph');

    await user.click(screen.getByRole('button', { name: /Back/i }));

    expect(screen.getByText('Create your first project')).toBeInTheDocument();
    const nameInput = screen.getByPlaceholderText(
      'My First Project',
    ) as HTMLInputElement;
    expect(nameInput.value).toBe('My Project');
  });

  it('re-submitting step 1 after Back uses updateProject(createdProject.id, payload) instead of createProject', async () => {
    const user = userEvent.setup();
    createProject.mockResolvedValueOnce({
      data: makeProject({ id: 'p-new', name: 'My Project' }),
    });
    updateProject.mockResolvedValueOnce({
      data: makeProject({ id: 'p-new', name: 'Renamed' }),
    });

    render(<CreateProjectPage />);
    await completeStep1(user, 'My Project');
    await screen.findByText('Create your first graph');

    await user.click(screen.getByRole('button', { name: /Back/i }));
    expect(screen.getByText('Create your first project')).toBeInTheDocument();

    // After Back, createdProject exists — button label changes to "Update & Continue"
    const nameInput = screen.getByPlaceholderText('My First Project');
    await user.clear(nameInput);
    await user.type(nameInput, 'Renamed');

    await user.click(
      screen.getByRole('button', { name: /Update & Continue/i }),
    );

    expect(updateProject).toHaveBeenCalledWith(
      'p-new',
      expect.objectContaining({ name: 'Renamed' }),
    );
    expect(createProject).toHaveBeenCalledTimes(1);
  });
});
