// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest';

import { cleanup, render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

// ── Hoisted mock stubs — vi.hoisted runs before vi.mock factories ─────────────

const {
  navigate,
  toastMock,
  createProject,
  updateProject,
  deleteProject,
  contextMock,
} = vi.hoisted(() => {
  const navigate = vi.fn();
  const toastMock = { success: vi.fn(), error: vi.fn() };
  const createProject = vi.fn();
  const updateProject = vi.fn();
  const deleteProject = vi.fn();
  const contextMock = {
    projects: [] as unknown[],
    loading: false,
    loadProjects: vi.fn(),
    currentProjectId: null as string | null,
    setCurrentProjectId: vi.fn(),
  };
  return {
    navigate,
    toastMock,
    createProject,
    updateProject,
    deleteProject,
    contextMock,
  };
});

// ── Module mocks — must come before the SUT import (ESM hoisting) ─────────────

vi.mock('react-router', () => ({
  useNavigate: () => navigate,
  Navigate: ({ to }: { to: string }) => (
    <div data-testid="nav-redirect">{to}</div>
  ),
}));

vi.mock('sonner', () => ({ toast: toastMock }));

vi.mock('../../api', () => ({
  projectsApi: { createProject, updateProject, deleteProject },
}));

vi.mock('../../contexts/ProjectContext', () => ({
  useProjectContext: () => contextMock,
}));

vi.mock('./ProjectSettingsModal', () => ({
  ProjectSettingsModal: () => null,
}));

import React from 'react';

import type { ProjectDto } from '../../autogenerated';
import { ProjectsListPage } from './list';

const makeProject = (overrides: Partial<ProjectDto> = {}): ProjectDto => ({
  id: 'p-1',
  name: 'Alpha',
  description: 'desc',
  icon: '🚀',
  color: '#3B82F6',
  settings: {},
  costLimitUsd: null,
  createdBy: 'u-1',
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-01-01T00:00:00.000Z',
  graphCount: 0,
  threadCount: 0,
  ...overrides,
});

const resetContext = (overrides: Partial<typeof contextMock> = {}) => {
  contextMock.projects = [];
  contextMock.loading = false;
  contextMock.currentProjectId = null;
  contextMock.loadProjects = vi.fn().mockResolvedValue(undefined);
  contextMock.setCurrentProjectId = vi.fn();
  Object.assign(contextMock, overrides);
};

beforeEach(() => {
  vi.clearAllMocks();
  resetContext();
});

afterEach(() => {
  cleanup();
});

// project-card.tsx renders Settings (lucide-settings), Pencil (lucide-pencil), and
// Trash2 (lucide-trash-2) as icon-only buttons. Lucide injects a kebab-case class on
// each SVG (e.g. Pencil → lucide-pencil). Walk up from the SVG to find the parent button.
const findIconButton = (iconClass: string): HTMLElement => {
  const svg = document.querySelector(`svg.${iconClass}`);
  if (!svg) {
    throw new Error(`No icon ${iconClass} found`);
  }
  const btn = svg.closest('button');
  if (!btn) {
    throw new Error(`Icon ${iconClass} has no button parent`);
  }
  return btn as HTMLElement;
};

describe('ProjectsListPage', () => {
  it('renders skeletons while loading', () => {
    resetContext({ loading: true });
    const { container } = render(<ProjectsListPage />);

    expect(screen.queryByTestId('nav-redirect')).toBeNull();
    expect(screen.queryByRole('button', { name: /new project/i })).toBeNull();
    // Tailwind animate-pulse class is applied to the shadcn Skeleton primitive
    const skeletons = container.querySelectorAll('.animate-pulse');
    expect(skeletons.length).toBeGreaterThan(0);
  });

  it('redirects to /onboarding when loading=false and projects=[]', () => {
    render(<ProjectsListPage />);
    const redirect = screen.getByTestId('nav-redirect');
    expect(redirect.textContent).toBe('/onboarding');
  });

  it('renders one ProjectCard per project when projects exist', () => {
    resetContext({
      projects: [makeProject(), makeProject({ id: 'p-2', name: 'Beta' })],
    });
    render(<ProjectsListPage />);

    expect(screen.getByText('Alpha')).toBeInTheDocument();
    expect(screen.getByText('Beta')).toBeInTheDocument();
    expect(
      screen.getByRole('button', { name: /new project/i }),
    ).toBeInTheDocument();
  });

  it('clicking "New Project" opens the dialog with empty form fields', async () => {
    const user = userEvent.setup();
    resetContext({ projects: [makeProject()] });
    render(<ProjectsListPage />);

    await user.click(screen.getByRole('button', { name: /new project/i }));

    // Use heading role to disambiguate from the "New Project" button
    expect(
      screen.getByRole('heading', { name: 'New Project' }),
    ).toBeInTheDocument();
    const nameInput = screen.getByPlaceholderText('My Project');
    expect((nameInput as HTMLInputElement).value).toBe('');
  });

  it('disables Save while name is whitespace-only', async () => {
    const user = userEvent.setup();
    resetContext({ projects: [makeProject()] });
    render(<ProjectsListPage />);

    await user.click(screen.getByRole('button', { name: /new project/i }));
    const nameInput = screen.getByPlaceholderText('My Project');
    await user.type(nameInput, '   ');

    const saveBtn = screen.getByRole('button', { name: /^save$/i });
    expect(saveBtn).toBeDisabled();
  });

  it('submits create with trimmed payload and null fallbacks', async () => {
    const user = userEvent.setup();
    createProject.mockResolvedValueOnce({ data: makeProject({ id: 'p-new' }) });
    resetContext({ projects: [makeProject()] });
    render(<ProjectsListPage />);

    await user.click(screen.getByRole('button', { name: /new project/i }));
    await user.type(
      screen.getByPlaceholderText('My Project'),
      '  My Project  ',
    );
    await user.click(screen.getByRole('button', { name: /^save$/i }));

    expect(createProject).toHaveBeenCalledWith({
      name: 'My Project',
      description: null,
      icon: null,
      color: '#3B82F6',
    });
  });

  it('after successful create: loadProjects + setCurrentProjectId + navigate + toast.success + dialog closes', async () => {
    const user = userEvent.setup();
    createProject.mockResolvedValueOnce({ data: makeProject({ id: 'p-new' }) });
    resetContext({ projects: [makeProject()] });
    render(<ProjectsListPage />);

    await user.click(screen.getByRole('button', { name: /new project/i }));
    await user.type(screen.getByPlaceholderText('My Project'), 'My Project');
    await user.click(screen.getByRole('button', { name: /^save$/i }));

    expect(contextMock.loadProjects).toHaveBeenCalled();
    expect(contextMock.setCurrentProjectId).toHaveBeenCalledWith('p-new');
    expect(navigate).toHaveBeenCalledWith('/dashboard');
    expect(toastMock.success).toHaveBeenCalled();
    expect(screen.queryByRole('heading', { name: 'New Project' })).toBeNull();

    // Production calls loadProjects before setCurrentProjectId so the dashboard sees fresh data;
    // verify the order isn't accidentally swapped.
    const loadProjectsOrder = vi.mocked(contextMock.loadProjects).mock
      .invocationCallOrder[0];
    const setCurrentOrder = vi.mocked(contextMock.setCurrentProjectId).mock
      .invocationCallOrder[0];
    const navigateOrder = navigate.mock.invocationCallOrder[0];

    expect(loadProjectsOrder).toBeLessThan(setCurrentOrder);
    expect(setCurrentOrder).toBeLessThan(navigateOrder);
  });

  it('on create API failure: toast.error with extracted message; dialog stays open; loadProjects NOT called', async () => {
    const user = userEvent.setup();
    createProject.mockRejectedValueOnce(new Error('boom'));
    resetContext({ projects: [makeProject()] });
    render(<ProjectsListPage />);

    await user.click(screen.getByRole('button', { name: /new project/i }));
    await user.type(screen.getByPlaceholderText('My Project'), 'My Project');
    await user.click(screen.getByRole('button', { name: /^save$/i }));

    expect(toastMock.error).toHaveBeenCalledWith(
      expect.stringContaining('boom'),
    );
    expect(
      screen.getByRole('heading', { name: 'New Project' }),
    ).toBeInTheDocument();
    expect(contextMock.loadProjects).not.toHaveBeenCalled();
  });

  it('clicking edit on a card opens the dialog pre-filled with that project', async () => {
    const user = userEvent.setup();
    const project = makeProject({ name: 'Alpha', description: 'desc' });
    resetContext({ projects: [project] });
    render(<ProjectsListPage />);

    // project-card.tsx renders Pencil (lucide-pencil) for the edit button.
    await user.click(findIconButton('lucide-pencil'));

    expect(screen.getByText('Edit Project')).toBeInTheDocument();
    const nameInput = screen.getByPlaceholderText(
      'My Project',
    ) as HTMLInputElement;
    expect(nameInput.value).toBe('Alpha');
  });

  it('saving an edit calls updateProject(id, payload), then loadProjects, and does NOT navigate or set current project', async () => {
    const user = userEvent.setup();
    updateProject.mockResolvedValueOnce({ data: makeProject() });
    resetContext({ projects: [makeProject()] });
    render(<ProjectsListPage />);

    // project-card.tsx renders Pencil (lucide-pencil) for the edit button.
    await user.click(findIconButton('lucide-pencil'));

    await user.click(screen.getByRole('button', { name: /^save$/i }));

    expect(updateProject).toHaveBeenCalledWith(
      'p-1',
      expect.objectContaining({ name: 'Alpha' }),
    );
    expect(contextMock.loadProjects).toHaveBeenCalled();
    expect(navigate).not.toHaveBeenCalled();
    expect(contextMock.setCurrentProjectId).not.toHaveBeenCalled();
  });

  it('clicking delete trash opens confirmation; cancelling closes without calling deleteProject', async () => {
    const user = userEvent.setup();
    resetContext({ projects: [makeProject()] });
    render(<ProjectsListPage />);

    // project-card.tsx renders Trash2 (lucide-trash-2) for the delete button.
    await user.click(findIconButton('lucide-trash-2'));

    expect(screen.getByText('Delete project')).toBeInTheDocument();

    await user.click(screen.getByRole('button', { name: /^cancel$/i }));

    expect(screen.queryByText('Delete project')).toBeNull();
    expect(deleteProject).not.toHaveBeenCalled();
  });

  it('confirming delete calls deleteProject(id), shows success toast, calls loadProjects', async () => {
    const user = userEvent.setup();
    deleteProject.mockResolvedValueOnce({});
    resetContext({ projects: [makeProject()] });
    render(<ProjectsListPage />);

    // project-card.tsx renders Trash2 (lucide-trash-2) for the delete button.
    await user.click(findIconButton('lucide-trash-2'));

    await user.click(screen.getByRole('button', { name: /^delete$/i }));

    expect(deleteProject).toHaveBeenCalledWith('p-1');
    expect(toastMock.success).toHaveBeenCalled();
    expect(contextMock.loadProjects).toHaveBeenCalled();
  });

  it('color picker click updates selected color and create payload', async () => {
    const user = userEvent.setup();
    createProject.mockResolvedValueOnce({ data: makeProject({ id: 'p-col' }) });
    resetContext({ projects: [makeProject()] });
    render(<ProjectsListPage />);

    await user.click(screen.getByRole('button', { name: /new project/i }));

    // Color swatches are plain <button type="button"> elements with no accessible name.
    // The color list starts with '#3B82F6' (index 0). We click index 1 → '#10B981'.
    const colorButtons = screen.getAllByRole('button').filter((btn) => {
      const style = (btn as HTMLButtonElement).style;
      return style.backgroundColor !== '';
    });
    await user.click(colorButtons[1]);

    await user.type(screen.getByPlaceholderText('My Project'), 'Color Project');
    await user.click(screen.getByRole('button', { name: /^save$/i }));

    expect(createProject).toHaveBeenCalledWith(
      expect.objectContaining({ color: '#10B981' }),
    );
  });

  it('errorFields-shaped failure does NOT call toast.error', async () => {
    const user = userEvent.setup();
    createProject.mockRejectedValueOnce({
      errorFields: [{ name: ['name'], errors: ['too short'] }],
    });
    resetContext({ projects: [makeProject()] });
    render(<ProjectsListPage />);

    await user.click(screen.getByRole('button', { name: /new project/i }));
    await user.type(screen.getByPlaceholderText('My Project'), 'x');
    await user.click(screen.getByRole('button', { name: /^save$/i }));

    expect(toastMock.error).not.toHaveBeenCalled();
    expect(
      screen.getByRole('heading', { name: 'New Project' }),
    ).toBeInTheDocument();
  });
});
