import { isAxiosError } from 'axios';
import { Loader2, X } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { toast } from 'sonner';

import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';

import { litellmApi, projectsApi, userPreferencesApi } from '../../api';
import type {
  LiteLlmModelDto,
  ModelDefaultsDto,
  ProjectDto,
  UserPreferencesDtoPreferencesModels,
} from '../../autogenerated';
import { parseCostLimitInput } from '../../utils/costLimit';
import { extractApiErrorMessage } from '../../utils/errors';
import {
  MODEL_SLOTS,
  type ModelOverrides,
  type ModelSlotKey,
} from '../settings/modelSlots';

interface ProjectSettingsModalProps {
  open: boolean;
  onClose: () => void;
  project: ProjectDto;
  onSaved: () => void;
}

export const ProjectSettingsModal = ({
  open,
  onClose,
  project,
  onSaved,
}: ProjectSettingsModalProps) => {
  const [models, setModels] = useState<LiteLlmModelDto[]>([]);
  const [defaults, setDefaults] = useState<ModelDefaultsDto | null>(null);
  const [userModels, setUserModels] = useState<
    UserPreferencesDtoPreferencesModels | undefined
  >(undefined);
  const [selectedModels, setSelectedModels] = useState<ModelOverrides>({});
  const [costLimitUsd, setCostLimitUsd] = useState<number | null>(null);
  const [saving, setSaving] = useState(false);
  const [loadingData, setLoadingData] = useState(true);

  const loadData = useCallback(async () => {
    setLoadingData(true);
    try {
      const [modelsResponse, defaultsResponse, loadedUserModels] =
        await Promise.all([
          litellmApi.listModels(),
          litellmApi.getModelDefaults(),
          userPreferencesApi
            .getPreferences()
            .then((res) => res.data.preferences.models)
            .catch((err: unknown) => {
              if (isAxiosError(err) && err.response?.status === 404) {
                return undefined;
              }
              throw err;
            }),
        ]);
      setModels(modelsResponse.data);
      setDefaults(defaultsResponse.data);
      setUserModels(loadedUserModels);

      // Initialize from project settings
      const projectModels =
        (project.settings?.models as ModelOverrides | undefined) ?? {};
      setSelectedModels(projectModels);
      setCostLimitUsd(project.costLimitUsd ?? null);
    } catch (err) {
      toast.error(extractApiErrorMessage(err, 'Failed to load model data'));
    } finally {
      setLoadingData(false);
    }
  }, [project.settings, project.costLimitUsd]);

  useEffect(() => {
    if (open) {
      // eslint-disable-next-line react-hooks/set-state-in-effect -- fetch settings each time modal opens
      loadData();
    }
  }, [open, loadData]);

  const getSource = (slotKey: ModelSlotKey): 'Project' | 'User' | 'Default' => {
    const projectValue = selectedModels[slotKey];
    if (projectValue) {
      return 'Project';
    }
    const userValue = userModels?.[slotKey];
    if (userValue) {
      return 'User';
    }
    return 'Default';
  };

  const nonEmbeddingModels = useMemo(
    () => models.filter((m) => !m.supportsEmbedding),
    [models],
  );
  const embeddingModels = useMemo(
    () => models.filter((m) => m.supportsEmbedding),
    [models],
  );

  const handleModelChange = (slotKey: ModelSlotKey, value: string) => {
    setSelectedModels((prev) => ({ ...prev, [slotKey]: value }));
  };

  const handleClear = (slotKey: ModelSlotKey) => {
    setSelectedModels((prev) => ({ ...prev, [slotKey]: null }));
  };

  const handleSave = async () => {
    setSaving(true);
    try {
      // Build the models object: only include keys with actual values
      const cleanModels: ModelOverrides = {};
      for (const slot of MODEL_SLOTS) {
        const value = selectedModels[slot.key];
        if (value) {
          cleanModels[slot.key] = value;
        }
      }

      await projectsApi.updateProject(project.id, {
        settings: {
          ...project.settings,
          models: cleanModels,
        },
        costLimitUsd,
      });
      toast.success('Project settings saved');
      onSaved();
      onClose();
    } catch (err) {
      toast.error(
        extractApiErrorMessage(err, 'Failed to save project settings'),
      );
    } finally {
      setSaving(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={(isOpen) => !isOpen && onClose()}>
      <DialogContent className="sm:max-w-[600px]">
        <DialogHeader>
          <DialogTitle>Project Settings — {project.name}</DialogTitle>
          <DialogDescription className="sr-only">
            Override default LLM models and cost limits for this project.
          </DialogDescription>
        </DialogHeader>

        {loadingData ? (
          <div className="flex items-center justify-center py-12">
            <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
          </div>
        ) : (
          <div className="space-y-4 py-2 max-h-[60vh] overflow-y-auto">
            <div className="space-y-1.5">
              <h3 className="text-sm font-medium">Default Cost Limit</h3>
              <p className="text-xs text-muted-foreground">
                Applies to threads in this project when no graph-level limit is
                set. Leave empty or 0 for unlimited.
              </p>
              <Label className="sr-only" htmlFor="project-cost-limit-input">
                Cost Limit (USD)
              </Label>
              <Input
                id="project-cost-limit-input"
                type="number"
                min={0}
                step="0.01"
                value={costLimitUsd === null ? '' : costLimitUsd}
                placeholder="Empty or 0 = unlimited"
                onChange={(e) =>
                  setCostLimitUsd(parseCostLimitInput(e.target.value))
                }
              />
            </div>
            <p className="text-sm text-muted-foreground">
              Override the default LLM models for this project. These settings
              take priority over user-level preferences.
            </p>
            {MODEL_SLOTS.map((slot) => {
              const source = getSource(slot.key);
              const filteredModels = slot.embeddingOnly
                ? embeddingModels
                : nonEmbeddingModels;
              const currentValue = selectedModels[slot.key];

              return (
                <div key={slot.key} className="space-y-1.5">
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-medium">{slot.label}</span>
                    <Badge
                      variant={source === 'Project' ? 'default' : 'secondary'}
                      className="text-[10px] px-1.5 py-0">
                      {source}
                    </Badge>
                  </div>
                  <p className="text-xs text-muted-foreground">
                    {slot.description}
                  </p>
                  <div className="flex items-center gap-2">
                    <Select
                      value={currentValue ?? ''}
                      onValueChange={(val) => handleModelChange(slot.key, val)}>
                      <SelectTrigger className="flex-1">
                        <SelectValue
                          placeholder={(() => {
                            const userModel = userModels?.[slot.key];
                            if (userModel) {
                              return `Use user setting (${userModel})`;
                            }
                            return defaults?.[slot.key]
                              ? `Use default (${defaults[slot.key]})`
                              : 'Use default';
                          })()}
                        />
                      </SelectTrigger>
                      <SelectContent>
                        {filteredModels.map((model) => (
                          <SelectItem key={model.id} value={model.id}>
                            {model.id}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    {currentValue && (
                      <Button
                        variant="ghost"
                        size="sm"
                        className="h-8 w-8 p-0"
                        onClick={() => handleClear(slot.key)}>
                        <X className="w-4 h-4 text-muted-foreground" />
                      </Button>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        )}

        <DialogFooter className="gap-2">
          <Button variant="outline" onClick={onClose}>
            Cancel
          </Button>
          <Button onClick={handleSave} disabled={saving || loadingData}>
            {saving && <Loader2 className="w-4 h-4 animate-spin mr-1" />}
            Save
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};
