import { Loader2 } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { toast } from 'sonner';

import {
  type DisconnectOAuthCredentialProviderEnum,
  type OAuthStatusResponseDto,
  type StartProviderEnum,
  StatusProviderEnum,
} from '@/autogenerated/api';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { useCurrentProject } from '@/hooks/useCurrentProject';
import { useWebSocketEvent } from '@/hooks/useWebSocket';

import { extractApiErrorMessage } from '../../utils/errors';
import {
  isOAuthSuccessMessage,
  OAUTH_BROADCAST_CHANNEL,
  oauthApi,
} from './oauth-api';

/** Display label per provider. Falls back to the raw provider id. */
const PROVIDER_LABELS: Record<string, string> = {
  [StatusProviderEnum.Linear]: 'Linear',
};

/** Every provider Geniro can authenticate — the page lists all of them. */
const ALL_PROVIDERS = Object.values(StatusProviderEnum);

const providerLabel = (provider: string): string =>
  PROVIDER_LABELS[provider] ?? provider;

// --- DisconnectConfirmationDialog ---

interface DisconnectConfirmationProps {
  provider: string | null;
  onClose: () => void;
  onDisconnected: () => void;
}

const DisconnectConfirmationDialog = ({
  provider,
  onClose,
  onDisconnected,
}: DisconnectConfirmationProps) => {
  const [disconnecting, setDisconnecting] = useState(false);

  const handleDisconnect = async () => {
    if (!provider) {
      return;
    }
    setDisconnecting(true);
    try {
      await oauthApi.disconnectOAuthCredential(
        provider as DisconnectOAuthCredentialProviderEnum,
      );
      toast.success(`Disconnected ${providerLabel(provider)}`);
      onDisconnected();
      onClose();
    } catch (err: unknown) {
      toast.error(extractApiErrorMessage(err, 'Failed to disconnect'));
    } finally {
      setDisconnecting(false);
    }
  };

  return (
    <AlertDialog
      open={Boolean(provider)}
      onOpenChange={(o) => {
        if (!o) {
          onClose();
        }
      }}>
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogTitle>Disconnect provider</AlertDialogTitle>
          <AlertDialogDescription>
            Are you sure you want to disconnect{' '}
            <span className="font-semibold">
              {provider ? providerLabel(provider) : ''}
            </span>
            ? The stored token will be deleted. Any agents using this connection
            will stop working until you reconnect.
          </AlertDialogDescription>
        </AlertDialogHeader>
        <AlertDialogFooter>
          <AlertDialogCancel disabled={disconnecting}>Cancel</AlertDialogCancel>
          <AlertDialogAction
            onClick={(e) => {
              e.preventDefault();
              handleDisconnect();
            }}
            disabled={disconnecting}
            className="bg-destructive text-destructive-foreground hover:bg-destructive/90">
            {disconnecting && <Loader2 className="mr-1 size-4 animate-spin" />}
            Disconnect
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  );
};

// --- ConnectionsPage ---

export const ConnectionsPage = () => {
  // Reading the current project here keeps the `x-project-id` header in sync for
  // the list/disconnect calls when the page is the entry route.
  useCurrentProject();

  const [credentials, setCredentials] = useState<OAuthStatusResponseDto[]>([]);
  const [loading, setLoading] = useState(true);
  const [connecting, setConnecting] = useState<string | null>(null);
  const [disconnectProvider, setDisconnectProvider] = useState<string | null>(
    null,
  );
  const [fallback, setFallback] = useState<{
    provider: string;
    url: string;
  } | null>(null);

  const fetchCredentials = useCallback(async () => {
    try {
      const { data } = await oauthApi.listOAuthCredentials();
      setCredentials(data);
    } catch (err: unknown) {
      toast.error(extractApiErrorMessage(err, 'Failed to load connections'));
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect -- one-shot fetch on mount
    void fetchCredentials();
  }, [fetchCredentials]);

  // Live-refresh: a credential acquired anywhere in this project (the in-editor
  // flow, this page, or a cap-link on another device) fans out on the project
  // room — refetch the list so the card flips to connected without a reload.
  useWebSocketEvent('credential.acquired', () => {
    void fetchCredentials();
  });

  // Same-browser connect: the callback tab signals success via postMessage +
  // BroadcastChannel (the socket event covers the cross-device case).
  useEffect(() => {
    const handleSignal = (data: unknown): void => {
      if (isOAuthSuccessMessage(data)) {
        void fetchCredentials();
      }
    };
    const onMessage = (event: MessageEvent): void => {
      if (event.origin !== window.location.origin) {
        return;
      }
      handleSignal(event.data);
    };
    window.addEventListener('message', onMessage);
    const channel =
      typeof BroadcastChannel !== 'undefined'
        ? new BroadcastChannel(OAUTH_BROADCAST_CHANNEL)
        : null;
    if (channel) {
      channel.onmessage = (event) => handleSignal(event.data);
    }
    return () => {
      window.removeEventListener('message', onMessage);
      channel?.close();
    };
  }, [fetchCredentials]);

  const statusByProvider = new Map(
    credentials.map((credential) => [credential.provider, credential]),
  );

  const handleConnect = useCallback(async (provider: string) => {
    setFallback(null);
    // Open a BLANK tab SYNCHRONOUSLY in the click handler so the popup blocker
    // allows it; navigate it once /start resolves. NOT `noopener` — the
    // same-origin callback needs `window.opener` to post the success signal.
    const tab = window.open('', '_blank');
    setConnecting(provider);
    try {
      const { data } = await oauthApi.start(provider as StartProviderEnum);
      if (tab) {
        tab.location.href = data.authorizeUrl;
      } else {
        setFallback({ provider, url: data.authorizeUrl });
      }
    } catch (err: unknown) {
      toast.error(
        extractApiErrorMessage(err, 'Failed to start authentication'),
      );
      tab?.close();
    } finally {
      setConnecting(null);
    }
  }, []);

  return (
    <div className="space-y-6 p-6">
      <div>
        <h2 className="text-base font-semibold">Connections</h2>
        <p className="text-muted-foreground mt-1 text-sm">
          Authenticate OAuth providers for this project so agents can use them
          without interruption. Connect once here, or whenever a run asks for
          access.
        </p>
      </div>

      {loading ? (
        <div className="flex items-center justify-center py-12">
          <Loader2 className="text-muted-foreground size-6 animate-spin" />
        </div>
      ) : (
        <div className="space-y-3">
          {ALL_PROVIDERS.map((provider) => {
            const status = statusByProvider.get(provider);
            const connected = status?.authenticated ?? false;
            // A stored-but-not-authenticated credential is an expired session.
            const expired = Boolean(status) && !connected;
            const busy = connecting === provider;

            return (
              <Card key={provider} data-testid={`connection-card-${provider}`}>
                <CardContent className="flex items-center justify-between gap-4 py-4">
                  <div className="flex flex-col gap-1">
                    <div className="flex items-center gap-2">
                      <span className="text-sm font-semibold">
                        {providerLabel(provider)}
                      </span>
                      {connected ? (
                        <Badge variant="secondary">Connected</Badge>
                      ) : expired ? (
                        <Badge variant="destructive">Session expired</Badge>
                      ) : (
                        <Badge variant="outline">Not connected</Badge>
                      )}
                    </div>
                    <span className="text-muted-foreground text-xs">
                      {connected
                        ? `Authenticated${
                            status?.accountLabel
                              ? ` as ${status.accountLabel}`
                              : ''
                          }`
                        : expired
                          ? 'The stored session expired — reconnect to continue.'
                          : 'Not connected.'}
                    </span>
                  </div>

                  <div className="flex items-center gap-2">
                    {connected || expired ? (
                      <>
                        <Button
                          size="sm"
                          variant="outline"
                          disabled={busy}
                          onClick={() => handleConnect(provider)}>
                          {busy ? (
                            <Loader2 className="size-4 animate-spin" />
                          ) : (
                            'Reconnect'
                          )}
                        </Button>
                        <Button
                          size="sm"
                          variant="outline"
                          className="text-destructive hover:text-destructive"
                          onClick={() => setDisconnectProvider(provider)}>
                          Disconnect
                        </Button>
                      </>
                    ) : (
                      <Button
                        size="sm"
                        disabled={busy}
                        onClick={() => handleConnect(provider)}>
                        {busy ? (
                          <Loader2 className="size-4 animate-spin" />
                        ) : (
                          'Connect'
                        )}
                      </Button>
                    )}
                  </div>
                </CardContent>
                {fallback?.provider === provider && (
                  <CardContent className="pt-0">
                    <a
                      href={fallback.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-primary text-xs underline"
                      data-testid="oauth-fallback-link">
                      Popup blocked — click here to continue authentication
                    </a>
                  </CardContent>
                )}
              </Card>
            );
          })}
        </div>
      )}

      <DisconnectConfirmationDialog
        provider={disconnectProvider}
        onClose={() => setDisconnectProvider(null)}
        onDisconnected={fetchCredentials}
      />
    </div>
  );
};
