import { OauthApi } from '@/autogenerated/api';

import { API_URL } from '../../config';

/**
 * Configured generated OAuth client. The generated operation paths already
 * include `/api/v1`, and it uses the global axios instance — so the
 * Authorization header + `x-project-id` interceptor set up in App apply
 * automatically.
 */
export const oauthApi = new OauthApi(undefined, API_URL);

/** Cross-tab channel the callback page broadcasts success on. */
export const OAUTH_BROADCAST_CHANNEL = 'oauth';

/** Message the callback page sends to the opener + broadcast channel. */
export interface OAuthSuccessMessage {
  type: 'oauth-success';
  provider: string;
  accountLabel: string | null;
}

export const isOAuthSuccessMessage = (
  value: unknown,
): value is OAuthSuccessMessage =>
  typeof value === 'object' &&
  value !== null &&
  (value as { type?: unknown }).type === 'oauth-success' &&
  typeof (value as { provider?: unknown }).provider === 'string';
