import type { FieldProps, RJSFSchema } from '@rjsf/utils';
import { Loader2 } from 'lucide-react';
import { useCallback, useEffect, useRef, useState } from 'react';

import type {
  StartProviderEnum,
  StatusProviderEnum,
} from '@/autogenerated/api';
import { Button } from '@/components/ui/button';
import { useWebSocketEvent } from '@/hooks/useWebSocket';

import {
  isOAuthSuccessMessage,
  OAUTH_BROADCAST_CHANNEL,
  oauthApi,
} from './oauth-api';

interface OAuthFieldContext {
  graphId?: string;
  nodeId?: string;
}

const readProvider = (schema: RJSFSchema): string | null => {
  const marker = (schema as Record<string, unknown>)['x-ui:oauth-authenticate'];
  if (marker && typeof marker === 'object' && 'provider' in marker) {
    const provider = (marker as { provider?: unknown }).provider;
    return typeof provider === 'string' ? provider : null;
  }
  return null;
};

/**
 * Generic per-MCP-node "Authenticate" field. Reads `x-ui:oauth-authenticate`
 * for the provider, shows the node's auth-state from `GET /oauth/:provider/
 * status`, and on click opens the OAuth flow in a NEW tab (popup-safe) — the
 * callback page signals back (postMessage + BroadcastChannel) and the node
 * refreshes. The field value is the resolved secret name so the graph compiler
 * injects the token into the runtime (secret-select collection).
 */
export const RjsfOAuthAuthenticateField = (
  props: FieldProps<unknown, RJSFSchema, OAuthFieldContext>,
) => {
  const provider = readProvider(props.schema);
  // rjsf types `formContext` as `any` — narrow it via an explicit assertion.
  const ctx = (props.formContext ?? {}) as OAuthFieldContext;
  const { graphId, nodeId } = ctx;

  const [loading, setLoading] = useState(true);
  const [authenticated, setAuthenticated] = useState(false);
  const [accountLabel, setAccountLabel] = useState<string | null>(null);
  const [starting, setStarting] = useState(false);
  const [fallbackUrl, setFallbackUrl] = useState<string | null>(null);
  // Set when a paused background/trigger run reports this provider needs auth
  // (the `auth.required` project-room event). Overrides a stale "authenticated"
  // label until the user re-connects.
  const [needsReauth, setNeedsReauth] = useState(false);
  // The single-use capability token + paused-run threadId carried by that same
  // `auth.required` event. Held in refs (not state — they don't drive render)
  // so clicking Authenticate redeems them, resuming the paused run server-side.
  const capabilityTokenRef = useRef<string | null>(null);
  const pausedThreadIdRef = useRef<string | null>(null);

  // Wrap onChange in a ref so the status-refresh callback can wire the secret
  // name into the field value without re-subscribing the cross-tab listeners.
  // onChange, the field path, and the current formData are read through refs so
  // refreshStatus depends ONLY on `provider`. Otherwise an unrelated form edit
  // (formData changes, or rjsf hands a fresh `fieldPathId.path` array each
  // render) would recreate refreshStatus, re-firing the status fetch AND
  // re-subscribing the cross-tab listeners (a fresh BroadcastChannel) on every
  // keystroke.
  const onChangeRef = useRef(props.onChange);
  const fieldPathRef = useRef(props.fieldPathId.path);
  const formDataRef = useRef(props.formData);
  useEffect(() => {
    onChangeRef.current = props.onChange;
    fieldPathRef.current = props.fieldPathId.path;
    formDataRef.current = props.formData;
  });

  const refreshStatus = useCallback(async () => {
    if (!provider) {
      setLoading(false);
      return;
    }
    try {
      const { data } = await oauthApi.status(provider as StatusProviderEnum);
      setAuthenticated(data.authenticated);
      setAccountLabel(data.accountLabel ?? null);
      // A fresh valid credential clears any pending re-auth prompt.
      if (data.authenticated) {
        setNeedsReauth(false);
      }
      // Wire / canonicalise the resolved secret name into the field value so the
      // compiler injects it. Only writes when it differs — so a fresh auth or a
      // re-auth that supersedes a stale name updates it, but an already-correct
      // value doesn't needlessly dirty the form on mount.
      if (
        data.authenticated &&
        data.secretName &&
        formDataRef.current !== data.secretName
      ) {
        onChangeRef.current(data.secretName as unknown, fieldPathRef.current);
      }
    } catch (error) {
      console.warn('Failed to load OAuth status', error);
    } finally {
      setLoading(false);
    }
  }, [provider]);

  useEffect(() => {
    void refreshStatus();
  }, [refreshStatus]);

  // Cross-tab completion signal — the callback page posts to the opener and a
  // BroadcastChannel; either refreshes this node's auth-state.
  useEffect(() => {
    if (!provider) {
      return;
    }
    const handleSignal = (data: unknown): void => {
      if (isOAuthSuccessMessage(data) && data.provider === provider) {
        void refreshStatus();
      }
    };
    const onMessage = (event: MessageEvent): void => {
      if (event.origin !== window.location.origin) {
        return;
      }
      handleSignal(event.data);
    };
    window.addEventListener('message', onMessage);
    const channel =
      typeof BroadcastChannel !== 'undefined'
        ? new BroadcastChannel(OAUTH_BROADCAST_CHANNEL)
        : null;
    if (channel) {
      channel.onmessage = (event) => handleSignal(event.data);
    }
    return () => {
      window.removeEventListener('message', onMessage);
      channel?.close();
    };
  }, [provider, refreshStatus]);

  // Project-room signal: a paused run needs this provider authenticated. Match
  // on provider, and on nodeId too when both are known (the producer carries the
  // OAuth-MCP node id), so an unrelated node's prompt doesn't flip this field.
  // The event also carries a single-use `capabilityToken` (in `data`) + the
  // paused run's `threadId` (envelope); stash both so clicking Authenticate
  // redeems them and the exchange resumes the paused run server-side.
  useWebSocketEvent('auth.required', (data) => {
    const evt = data as {
      nodeId?: string;
      threadId?: string;
      data?: { provider?: string; capabilityToken?: string };
    };
    if (
      evt.data?.provider === provider &&
      (!nodeId || !evt.nodeId || evt.nodeId === nodeId)
    ) {
      capabilityTokenRef.current = evt.data?.capabilityToken ?? null;
      pausedThreadIdRef.current = evt.threadId ?? null;
      setNeedsReauth(true);
    }
  });

  const handleAuthenticate = useCallback(async () => {
    if (!provider) {
      return;
    }
    setFallbackUrl(null);
    // Open a BLANK tab SYNCHRONOUSLY in the click handler so the popup blocker
    // allows it. NOT `noopener` — the same-origin callback needs `window.opener`
    // to post the success signal back. Navigate it once /start resolves.
    const tab = window.open('', '_blank');
    setStarting(true);
    try {
      // When a paused run flagged this node (needsReauth), redeem its single-use
      // capability token + threadId so the exchange resumes that run. The server
      // recovers project + thread from the token's claims; both are `undefined`
      // for ordinary proactive auth, leaving the in-editor flow unchanged.
      const { data } = await oauthApi.start(
        provider as StartProviderEnum,
        graphId,
        nodeId,
        pausedThreadIdRef.current ?? undefined,
        capabilityTokenRef.current ?? undefined,
      );
      // The token is single-use (redeemed server-side on this call) — clear it
      // so a later re-auth doesn't resend a spent token.
      capabilityTokenRef.current = null;
      pausedThreadIdRef.current = null;
      if (tab) {
        tab.location.href = data.authorizeUrl;
      } else {
        // Popup blocked (window.open returned null) — fall back to a link.
        setFallbackUrl(data.authorizeUrl);
      }
    } catch (error) {
      console.warn('Failed to start OAuth flow', error);
      tab?.close();
      // Intentionally DON'T clear the cap refs on failure: a transient error
      // before the server redeems the token leaves it still valid, so keeping it
      // lets the user retry. The rare redeem-then-network-fail window (token
      // consumed server-side, response lost) self-heals — the paused run
      // re-emits `auth.required` with a fresh cap on its next pre-flight.
    } finally {
      setStarting(false);
    }
  }, [provider, graphId, nodeId]);

  if (!provider) {
    return null;
  }

  const disabled = starting || props.disabled || props.readonly;

  return (
    <div data-testid="oauth-authenticate-field">
      <span className="text-sm font-semibold">
        {props.schema.title ?? props.name}
      </span>
      {props.schema.description && (
        <span className="text-muted-foreground mb-2 block text-xs">
          {props.schema.description}
        </span>
      )}
      {loading ? (
        <div className="text-muted-foreground flex items-center gap-2 text-sm">
          <Loader2 className="size-4 animate-spin" /> Checking…
        </div>
      ) : needsReauth ? (
        <div
          className="flex items-center gap-2"
          data-testid="oauth-needs-reauth">
          <span className="text-destructive text-sm">
            Re-authentication required
          </span>
          <Button size="sm" disabled={disabled} onClick={handleAuthenticate}>
            {starting ? (
              <Loader2 className="size-4 animate-spin" />
            ) : (
              'Authenticate'
            )}
          </Button>
        </div>
      ) : authenticated ? (
        <div className="flex items-center gap-2">
          <span
            className="text-foreground text-sm"
            data-testid="oauth-authenticated-label">
            Authenticated{accountLabel ? ` as ${accountLabel}` : ''}
          </span>
          <Button
            size="sm"
            variant="outline"
            disabled={disabled}
            onClick={handleAuthenticate}>
            Re-authenticate
          </Button>
        </div>
      ) : (
        <Button size="sm" disabled={disabled} onClick={handleAuthenticate}>
          {starting ? (
            <Loader2 className="size-4 animate-spin" />
          ) : (
            'Authenticate'
          )}
        </Button>
      )}
      {fallbackUrl && (
        <a
          href={fallbackUrl}
          target="_blank"
          rel="noopener noreferrer"
          className="text-primary mt-2 block text-xs underline"
          data-testid="oauth-fallback-link">
          Popup blocked — click here to continue authentication
        </a>
      )}
    </div>
  );
};
