import { CheckCircle2, Loader2, XCircle } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { useParams, useSearchParams } from 'react-router';

import type { OAuthExchangeRequestDtoProviderEnum } from '@/autogenerated/api';

import { extractApiErrorMessage } from '../../../utils/errors';
import {
  OAUTH_BROADCAST_CHANNEL,
  oauthApi,
  type OAuthSuccessMessage,
} from '../oauth-api';

type CallbackState =
  | { status: 'exchanging' }
  | { status: 'success'; accountLabel: string | null }
  | { status: 'error'; message: string };

/**
 * Loads in the NEW tab opened by the per-node Authenticate widget. Exchanges
 * the authorization code, then signals the opener editor (postMessage +
 * BroadcastChannel) and self-closes. The authoritative completion signal is the
 * server-side `credential.acquired` event emitted during the exchange; these
 * browser signals are the convenience layer that refreshes the editor.
 */
export const OAuthCallbackPage = () => {
  const { provider } = useParams();
  const [searchParams] = useSearchParams();
  const code = searchParams.get('code');
  const state = searchParams.get('state');

  const [view, setView] = useState<CallbackState>({ status: 'exchanging' });
  const hasRun = useRef(false);

  useEffect(() => {
    if (hasRun.current) {
      return;
    }
    if (!provider || !code || !state) {
      setView({
        status: 'error',
        message: 'Missing provider, code, or state in the callback URL.',
      });
      return;
    }
    hasRun.current = true;
    let closeTimer: number | undefined;

    const run = async () => {
      try {
        const { data } = await oauthApi.exchange({
          provider: provider as OAuthExchangeRequestDtoProviderEnum,
          code,
          state,
        });
        const message: OAuthSuccessMessage = {
          type: 'oauth-success',
          provider: data.provider,
          accountLabel: data.accountLabel ?? null,
        };
        try {
          // `window.opener` is typed `any` in the DOM lib — narrow it.
          const opener = window.opener as Window | null;
          opener?.postMessage(message, window.location.origin);
        } catch {
          // Opener gone / cross-origin — the BroadcastChannel still signals.
        }
        try {
          const channel = new BroadcastChannel(OAUTH_BROADCAST_CHANNEL);
          channel.postMessage(message);
          channel.close();
        } catch {
          // BroadcastChannel unsupported — the postMessage above still signals.
        }
        setView({ status: 'success', accountLabel: data.accountLabel ?? null });
        // Best-effort self-close (only works for a script-opened tab).
        closeTimer = window.setTimeout(() => window.close(), 1200);
      } catch (error) {
        setView({
          status: 'error',
          message: extractApiErrorMessage(error, 'Authentication failed'),
        });
      }
    };
    void run();
    return () => {
      if (closeTimer !== undefined) {
        window.clearTimeout(closeTimer);
      }
    };
  }, [provider, code, state]);

  if (view.status === 'exchanging') {
    return (
      <div className="flex min-h-[50vh] flex-col items-center justify-center gap-4">
        <Loader2 className="text-primary size-9 animate-spin" />
        <p className="text-muted-foreground">Completing authentication…</p>
      </div>
    );
  }

  if (view.status === 'success') {
    return (
      <div className="mx-auto flex min-h-[50vh] max-w-lg flex-col items-center justify-center gap-4 text-center">
        <CheckCircle2 className="size-12 text-emerald-500" />
        <h2 className="text-foreground text-xl font-semibold">Connected</h2>
        <p className="text-muted-foreground">
          {view.accountLabel
            ? `Authenticated as ${view.accountLabel}. `
            : 'Authentication succeeded. '}
          You can close this tab and return to the editor.
        </p>
      </div>
    );
  }

  return (
    <div className="mx-auto flex min-h-[50vh] max-w-lg flex-col items-center justify-center gap-4 text-center">
      <XCircle className="text-destructive size-12" />
      <h2 className="text-foreground text-xl font-semibold">
        Authentication Failed
      </h2>
      <p className="text-muted-foreground">{view.message}</p>
    </div>
  );
};
