import {
  CheckCircle2,
  ChevronDown,
  ExternalLink,
  FolderGit2,
  KeyRound,
  Loader2,
  RefreshCw,
} from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router';
import { toast } from 'sonner';

import { Alert, AlertDescription } from '@/components/ui/alert';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from '@/components/ui/collapsible';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Skeleton } from '@/components/ui/skeleton';

import { gitAuthApi, gitRepositoriesApi } from '../../api';
import type { GitUserPatStatusResponseDto } from '../../autogenerated/api';
import { extractApiErrorMessage } from '../../utils/errors';

interface GitHubPatSectionProps {
  /** Whether per-user PAT storage is available (the secrets store is configured). */
  enabled: boolean;
  /** Whether the user also has a GitHub App installation — drives the precedence hint. */
  hasAppInstallations: boolean;
  /**
   * Link to the Repositories page where PAT-synced repos appear. Built by the
   * parent from the current project (PAT repos have `installationId: null`, so
   * they never render under a GitHub App installation on this page). When null
   * the "View repositories" link is hidden.
   */
  repositoriesHref?: string | null;
}

const CREATE_TOKEN_URL =
  'https://github.com/settings/tokens/new?scopes=repo&description=Geniro';

const EMPTY_STATUS: GitUserPatStatusResponseDto = {
  configured: false,
  login: null,
  tokenType: null,
  validatedAt: null,
};

/**
 * Settings card for the user's personal GitHub PAT. State A (no PAT) shows a
 * masked input + validate-on-save; state B (configured) shows the connected
 * account + Replace/Remove. The token value is never re-displayed. Degrades to
 * a disabled note when the secrets store is unavailable.
 */
export const GitHubPatSection = ({
  enabled,
  hasAppInstallations,
  repositoriesHref,
}: GitHubPatSectionProps) => {
  const [status, setStatus] =
    useState<GitUserPatStatusResponseDto>(EMPTY_STATUS);
  const [loading, setLoading] = useState(enabled);
  const [token, setToken] = useState('');
  const [replacing, setReplacing] = useState(false);
  const [saving, setSaving] = useState(false);
  const [removing, setRemoving] = useState(false);
  const [syncing, setSyncing] = useState(false);
  const [confirmingRemove, setConfirmingRemove] = useState(false);
  const [error, setError] = useState<string | null>(null);
  // Distinct from `error` (save/remove): a failed STATUS fetch must not silently
  // drop to the empty "add a token" form (state A) — that implies no token
  // exists and invites a confused re-entry. Surface an error + Retry instead.
  const [statusError, setStatusError] = useState<string | null>(null);

  const fetchStatus = useCallback(async () => {
    if (!enabled) {
      setLoading(false);
      return;
    }
    setLoading(true);
    try {
      const response = await gitAuthApi.getStatus();
      setStatus(response.data);
      setStatusError(null);
    } catch (e: unknown) {
      setStatusError(
        extractApiErrorMessage(e, 'Could not load your GitHub token status.'),
      );
    } finally {
      setLoading(false);
    }
  }, [enabled]);

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect -- one-shot status fetch on mount
    fetchStatus();
  }, [fetchStatus]);

  const handleSave = useCallback(async () => {
    if (!token.trim()) {
      return;
    }
    setSaving(true);
    setError(null);
    try {
      const response = await gitAuthApi.setPat({ token });
      setStatus(response.data);
      setToken('');
      setReplacing(false);
      toast.success('GitHub personal access token saved.');
    } catch (e: unknown) {
      setError(extractApiErrorMessage(e, 'Failed to save the token.'));
    } finally {
      setSaving(false);
    }
  }, [token]);

  const handleRemove = useCallback(async () => {
    setRemoving(true);
    setError(null);
    try {
      await gitAuthApi.deletePat();
      setStatus(EMPTY_STATUS);
      setToken('');
      setReplacing(false);
      toast.success('GitHub personal access token removed.');
    } catch (e: unknown) {
      setError(extractApiErrorMessage(e, 'Failed to remove the token.'));
    } finally {
      setRemoving(false);
      setConfirmingRemove(false);
    }
  }, []);

  const handleSync = useCallback(async () => {
    setSyncing(true);
    setError(null);
    try {
      // With a PAT configured this resolves to the per-user PAT sync
      // (GET /user/repos). The toast reports the count so a no-delta sync (the
      // PAT lists the same repos the App already synced) is not mistaken for a
      // no-op. Synced repos are listed on the Repositories page, not here.
      const { data } = await gitRepositoriesApi.syncRepositories();
      toast.success(
        `Sync complete: ${data.synced} added, ${data.removed} removed, ${data.total} total`,
      );
    } catch (e: unknown) {
      setError(extractApiErrorMessage(e, 'Failed to sync repositories.'));
    } finally {
      setSyncing(false);
    }
  }, []);

  const header = (
    <div className="flex items-center gap-2">
      <KeyRound className="h-4 w-4 text-muted-foreground" />
      <h3 className="text-sm font-medium">Personal Access Token</h3>
    </div>
  );

  if (!enabled) {
    return (
      <Card className="p-4 space-y-2 opacity-80">
        {header}
        <p className="text-sm text-muted-foreground">
          Personal access tokens require a configured secrets store. Contact
          your administrator to enable it.
        </p>
      </Card>
    );
  }

  if (loading) {
    return (
      <Card className="p-4 space-y-3">
        {header}
        <Skeleton className="h-9 w-full" />
      </Card>
    );
  }

  if (statusError) {
    return (
      <Card className="p-4 space-y-3">
        {header}
        <Alert variant="destructive">
          <AlertDescription>{statusError}</AlertDescription>
        </Alert>
        <Button variant="outline" onClick={fetchStatus}>
          Retry
        </Button>
      </Card>
    );
  }

  const tokenForm = (
    <div className="space-y-2">
      <Label htmlFor="github-pat-input">Token</Label>
      <Input
        id="github-pat-input"
        type="password"
        autoComplete="off"
        placeholder="ghp_… or github_pat_…"
        value={token}
        onChange={(e) => setToken(e.target.value)}
      />
      <div className="space-y-2 text-xs text-muted-foreground">
        <p>
          Needs the <code>repo</code> scope (classic token) — or a fine-grained
          token granting Contents, Pull requests, and Issues access.
        </p>
        <Collapsible>
          <CollapsibleTrigger className="inline-flex items-center gap-1 underline [&[data-state=open]>svg]:rotate-180">
            Which permissions does it need?
            <ChevronDown className="h-3 w-3 transition-transform" />
          </CollapsibleTrigger>
          <CollapsibleContent className="space-y-3 pt-2">
            <div className="space-y-1">
              <p className="font-medium text-foreground">
                Classic token (simplest)
              </p>
              <ul className="list-disc space-y-0.5 pl-4">
                <li>
                  <code>repo</code> — required. Covers cloning, pushing, and
                  managing pull requests, issues, and comments across your
                  repositories.
                </li>
                <li>
                  <code>workflow</code> — only if agents edit GitHub Actions
                  workflow files (<code>.github/workflows/</code>). GitHub
                  rejects pushes that touch those files without it.
                </li>
                <li>
                  <code>read:org</code> — only if agents request team reviewers
                  on pull requests.
                </li>
              </ul>
            </div>
            <div className="space-y-1">
              <p className="font-medium text-foreground">
                Fine-grained token (more restrictive)
              </p>
              <p>
                Select the repositories Geniro may access, then grant these
                repository permissions:
              </p>
              <ul className="list-disc space-y-0.5 pl-4">
                <li>
                  <span className="font-medium">Contents</span> — Read and write
                  (clone, fetch, push, commits)
                </li>
                <li>
                  <span className="font-medium">Pull requests</span> — Read and
                  write
                </li>
                <li>
                  <span className="font-medium">Issues</span> — Read and write
                </li>
                <li>
                  <span className="font-medium">Metadata</span> — Read (selected
                  automatically; required to list your repositories)
                </li>
                <li>
                  <span className="font-medium">Workflows</span> — Read and
                  write (optional; only to edit workflow files)
                </li>
                <li>
                  <span className="font-medium">
                    Organization &rsaquo; Members
                  </span>{' '}
                  — Read (optional; only for team reviewers)
                </li>
              </ul>
            </div>
          </CollapsibleContent>
        </Collapsible>
        <a
          href={CREATE_TOKEN_URL}
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-1 underline">
          Create a token on GitHub
          <ExternalLink className="h-3 w-3" />
        </a>
      </div>
      {error && <p className="text-destructive text-sm">{error}</p>}
      <div className="flex gap-2">
        <Button onClick={handleSave} disabled={!token.trim() || saving}>
          {saving && <Loader2 className="h-4 w-4 animate-spin" />}
          Save
        </Button>
        {replacing && (
          <Button
            variant="outline"
            onClick={() => {
              setReplacing(false);
              setToken('');
              setError(null);
            }}
            disabled={saving}>
            Cancel
          </Button>
        )}
      </div>
    </div>
  );

  if (status.configured && !replacing) {
    return (
      <Card className="p-4 space-y-3">
        {header}
        <div className="flex items-center gap-2 text-sm">
          <CheckCircle2 className="h-4 w-4 text-green-600" />
          <span>
            Connected as <span className="font-medium">{status.login}</span>
          </span>
          {status.tokenType && (
            <Badge variant="secondary">
              {status.tokenType === 'fine-grained' ? 'Fine-grained' : 'Classic'}
            </Badge>
          )}
        </div>
        {status.validatedAt && (
          <p className="text-xs text-muted-foreground">
            Validated {new Date(status.validatedAt).toLocaleString()}
          </p>
        )}
        {hasAppInstallations && (
          <Alert>
            <AlertDescription>
              Your personal access token takes precedence over the GitHub App
              for your GitHub operations. While it is set, App-synced
              repositories are not refreshed and may go stale. Remove it to fall
              back to the App.
            </AlertDescription>
          </Alert>
        )}
        <p className="text-xs text-muted-foreground">
          Repositories accessible to this token (including org repos the GitHub
          App can&apos;t reach) are synced under your account and listed on the{' '}
          {repositoriesHref ? (
            <Link
              to={repositoriesHref}
              className="inline-flex items-center gap-1 underline">
              Repositories page
              <FolderGit2 className="h-3 w-3" />
            </Link>
          ) : (
            'Repositories page'
          )}
          {hasAppInstallations
            ? ' — not in the GitHub App installations above.'
            : '.'}
        </p>
        {error && <p className="text-destructive text-sm">{error}</p>}
        <div className="flex flex-wrap gap-2">
          <Button variant="outline" onClick={handleSync} disabled={syncing}>
            {syncing ? (
              <Loader2 className="h-4 w-4 animate-spin" />
            ) : (
              <RefreshCw className="h-4 w-4" />
            )}
            Sync repositories
          </Button>
          <Button variant="outline" onClick={() => setReplacing(true)}>
            Replace
          </Button>
          <Button
            variant="destructive"
            onClick={() => setConfirmingRemove(true)}
            disabled={removing}>
            {removing && <Loader2 className="h-4 w-4 animate-spin" />}
            Remove
          </Button>
        </div>
        <AlertDialog
          open={confirmingRemove}
          onOpenChange={(open) => {
            if (!open) {
              setConfirmingRemove(false);
            }
          }}>
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle>Remove personal access token</AlertDialogTitle>
              <AlertDialogDescription>
                Your stored GitHub personal access token will be deleted.{' '}
                {hasAppInstallations
                  ? 'Your GitHub operations will fall back to the GitHub App.'
                  : 'You have no GitHub App installation, so GitHub operations will stop working until you add a token again or connect the App.'}
              </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogCancel disabled={removing}>Cancel</AlertDialogCancel>
              <AlertDialogAction
                onClick={(e) => {
                  e.preventDefault();
                  handleRemove();
                }}
                disabled={removing}
                className="bg-destructive text-destructive-foreground hover:bg-destructive/90">
                {removing && <Loader2 className="mr-1 size-4 animate-spin" />}
                Remove token
              </AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>
      </Card>
    );
  }

  return (
    <Card className="p-4 space-y-3">
      {header}
      <p className="text-sm text-muted-foreground">
        Use your own GitHub personal access token for all your GitHub
        operations. When set, it takes precedence over the GitHub App.
      </p>
      {tokenForm}
    </Card>
  );
};
