import { CheckCircle2, ExternalLink, KeyRound, Loader2 } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { toast } from 'sonner';

import { Alert, AlertDescription } from '@/components/ui/alert';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Skeleton } from '@/components/ui/skeleton';

import { gitAuthApi } from '../../api';
import type { GitUserPatStatusResponseDto } from '../../autogenerated/api';
import { extractApiErrorMessage } from '../../utils/errors';

interface GitHubPatSectionProps {
  /** Whether per-user PAT storage is available (the secrets store is configured). */
  enabled: boolean;
  /** Whether the user also has a GitHub App installation — drives the precedence hint. */
  hasAppInstallations: boolean;
}

const CREATE_TOKEN_URL =
  'https://github.com/settings/tokens/new?scopes=repo&description=Geniro';

const EMPTY_STATUS: GitUserPatStatusResponseDto = {
  configured: false,
  login: null,
  tokenType: null,
  validatedAt: null,
};

/**
 * Settings card for the user's personal GitHub PAT. State A (no PAT) shows a
 * masked input + validate-on-save; state B (configured) shows the connected
 * account + Replace/Remove. The token value is never re-displayed. Degrades to
 * a disabled note when the secrets store is unavailable.
 */
export const GitHubPatSection = ({
  enabled,
  hasAppInstallations,
}: GitHubPatSectionProps) => {
  const [status, setStatus] =
    useState<GitUserPatStatusResponseDto>(EMPTY_STATUS);
  const [loading, setLoading] = useState(enabled);
  const [token, setToken] = useState('');
  const [replacing, setReplacing] = useState(false);
  const [saving, setSaving] = useState(false);
  const [removing, setRemoving] = useState(false);
  const [confirmingRemove, setConfirmingRemove] = useState(false);
  const [error, setError] = useState<string | null>(null);
  // Distinct from `error` (save/remove): a failed STATUS fetch must not silently
  // drop to the empty "add a token" form (state A) — that implies no token
  // exists and invites a confused re-entry. Surface an error + Retry instead.
  const [statusError, setStatusError] = useState<string | null>(null);

  const fetchStatus = useCallback(async () => {
    if (!enabled) {
      setLoading(false);
      return;
    }
    setLoading(true);
    try {
      const response = await gitAuthApi.getStatus();
      setStatus(response.data);
      setStatusError(null);
    } catch (e: unknown) {
      setStatusError(
        extractApiErrorMessage(e, 'Could not load your GitHub token status.'),
      );
    } finally {
      setLoading(false);
    }
  }, [enabled]);

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect -- one-shot status fetch on mount
    fetchStatus();
  }, [fetchStatus]);

  const handleSave = useCallback(async () => {
    if (!token.trim()) {
      return;
    }
    setSaving(true);
    setError(null);
    try {
      const response = await gitAuthApi.setPat({ token });
      setStatus(response.data);
      setToken('');
      setReplacing(false);
      toast.success('GitHub personal access token saved.');
    } catch (e: unknown) {
      setError(extractApiErrorMessage(e, 'Failed to save the token.'));
    } finally {
      setSaving(false);
    }
  }, [token]);

  const handleRemove = useCallback(async () => {
    setRemoving(true);
    setError(null);
    try {
      await gitAuthApi.deletePat();
      setStatus(EMPTY_STATUS);
      setToken('');
      setReplacing(false);
      toast.success('GitHub personal access token removed.');
    } catch (e: unknown) {
      setError(extractApiErrorMessage(e, 'Failed to remove the token.'));
    } finally {
      setRemoving(false);
      setConfirmingRemove(false);
    }
  }, []);

  const header = (
    <div className="flex items-center gap-2">
      <KeyRound className="h-4 w-4 text-muted-foreground" />
      <h3 className="text-sm font-medium">Personal Access Token</h3>
    </div>
  );

  if (!enabled) {
    return (
      <Card className="p-4 space-y-2 opacity-80">
        {header}
        <p className="text-sm text-muted-foreground">
          Personal access tokens require a configured secrets store. Contact
          your administrator to enable it.
        </p>
      </Card>
    );
  }

  if (loading) {
    return (
      <Card className="p-4 space-y-3">
        {header}
        <Skeleton className="h-9 w-full" />
      </Card>
    );
  }

  if (statusError) {
    return (
      <Card className="p-4 space-y-3">
        {header}
        <Alert variant="destructive">
          <AlertDescription>{statusError}</AlertDescription>
        </Alert>
        <Button variant="outline" onClick={fetchStatus}>
          Retry
        </Button>
      </Card>
    );
  }

  const tokenForm = (
    <div className="space-y-2">
      <Label htmlFor="github-pat-input">Token</Label>
      <Input
        id="github-pat-input"
        type="password"
        autoComplete="off"
        placeholder="ghp_… or github_pat_…"
        value={token}
        onChange={(e) => setToken(e.target.value)}
      />
      <p className="text-xs text-muted-foreground">
        Needs the <code>repo</code> scope.{' '}
        <a
          href={CREATE_TOKEN_URL}
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-1 underline">
          Create a token on GitHub
          <ExternalLink className="h-3 w-3" />
        </a>
      </p>
      {error && <p className="text-destructive text-sm">{error}</p>}
      <div className="flex gap-2">
        <Button onClick={handleSave} disabled={!token.trim() || saving}>
          {saving && <Loader2 className="h-4 w-4 animate-spin" />}
          Save
        </Button>
        {replacing && (
          <Button
            variant="outline"
            onClick={() => {
              setReplacing(false);
              setToken('');
              setError(null);
            }}
            disabled={saving}>
            Cancel
          </Button>
        )}
      </div>
    </div>
  );

  if (status.configured && !replacing) {
    return (
      <Card className="p-4 space-y-3">
        {header}
        <div className="flex items-center gap-2 text-sm">
          <CheckCircle2 className="h-4 w-4 text-green-600" />
          <span>
            Connected as <span className="font-medium">{status.login}</span>
          </span>
          {status.tokenType && (
            <Badge variant="secondary">
              {status.tokenType === 'fine-grained' ? 'Fine-grained' : 'Classic'}
            </Badge>
          )}
        </div>
        {status.validatedAt && (
          <p className="text-xs text-muted-foreground">
            Validated {new Date(status.validatedAt).toLocaleString()}
          </p>
        )}
        {hasAppInstallations && (
          <Alert>
            <AlertDescription>
              Your personal access token takes precedence over the GitHub App
              for your GitHub operations. While it is set, App-synced
              repositories are not refreshed and may go stale. Remove it to fall
              back to the App.
            </AlertDescription>
          </Alert>
        )}
        {error && <p className="text-destructive text-sm">{error}</p>}
        <div className="flex gap-2">
          <Button variant="outline" onClick={() => setReplacing(true)}>
            Replace
          </Button>
          <Button
            variant="destructive"
            onClick={() => setConfirmingRemove(true)}
            disabled={removing}>
            {removing && <Loader2 className="h-4 w-4 animate-spin" />}
            Remove
          </Button>
        </div>
        <AlertDialog
          open={confirmingRemove}
          onOpenChange={(open) => {
            if (!open) {
              setConfirmingRemove(false);
            }
          }}>
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle>Remove personal access token</AlertDialogTitle>
              <AlertDialogDescription>
                Your stored GitHub personal access token will be deleted.{' '}
                {hasAppInstallations
                  ? 'Your GitHub operations will fall back to the GitHub App.'
                  : 'You have no GitHub App installation, so GitHub operations will stop working until you add a token again or connect the App.'}
              </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogCancel disabled={removing}>Cancel</AlertDialogCancel>
              <AlertDialogAction
                onClick={(e) => {
                  e.preventDefault();
                  handleRemove();
                }}
                disabled={removing}
                className="bg-destructive text-destructive-foreground hover:bg-destructive/90">
                {removing && <Loader2 className="mr-1 size-4 animate-spin" />}
                Remove token
              </AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>
      </Card>
    );
  }

  return (
    <Card className="p-4 space-y-3">
      {header}
      <p className="text-sm text-muted-foreground">
        Use your own GitHub personal access token for all your GitHub
        operations. When set, it takes precedence over the GitHub App.
      </p>
      {tokenForm}
    </Card>
  );
};
