import { Eye, EyeOff, Loader2, Pencil, Plus, Trash2 } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { toast } from 'sonner';

import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { Textarea } from '@/components/ui/textarea';

import { secretsApi } from '../../api';
import type { SecretResponseDto } from '../../autogenerated';
import { extractApiErrorMessage } from '../../utils/errors';

// --- CreateSecretDialog ---

interface CreateSecretDialogProps {
  open: boolean;
  onClose: () => void;
  onCreated: () => void;
}

const CreateSecretDialog = ({
  open,
  onClose,
  onCreated,
}: CreateSecretDialogProps) => {
  const [name, setName] = useState('');
  const [value, setValue] = useState('');
  const [description, setDescription] = useState('');
  const [showValue, setShowValue] = useState(false);
  const [saving, setSaving] = useState(false);
  const [nameError, setNameError] = useState<string | null>(null);

  const handleClose = () => {
    setName('');
    setValue('');
    setDescription('');
    setShowValue(false);
    setNameError(null);
    onClose();
  };

  const validateName = (val: string): boolean => {
    const pattern = /^[A-Z][A-Z0-9_]*$/;
    if (!val) {
      setNameError('Name is required');
      return false;
    }
    if (!pattern.test(val)) {
      setNameError('Must be uppercase snake_case (e.g. API_KEY)');
      return false;
    }
    setNameError(null);
    return true;
  };

  const handleSave = async () => {
    if (!validateName(name)) {
      return;
    }
    if (!value) {
      toast.error('Value is required');
      return;
    }
    setSaving(true);
    try {
      await secretsApi.create({
        name,
        value,
        description: description || null,
      });
      toast.success('Secret created');
      onCreated();
      handleClose();
    } catch (err: unknown) {
      toast.error(extractApiErrorMessage(err, 'Failed to create secret'));
    } finally {
      setSaving(false);
    }
  };

  return (
    <Dialog
      open={open}
      onOpenChange={(o) => {
        if (!o) {
          handleClose();
        }
      }}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Create Secret</DialogTitle>
          <DialogDescription className="sr-only">
            Add a new secret value that can be injected into agent
            configurations.
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-4 py-2">
          <div className="space-y-1.5">
            <Label htmlFor="secret-name">Name</Label>
            <Input
              id="secret-name"
              value={name}
              onChange={(e) => {
                setName(e.target.value);
                if (nameError) {
                  validateName(e.target.value);
                }
              }}
              onBlur={() => validateName(name)}
              placeholder="API_KEY"
            />
            {nameError ? (
              <p className="text-xs text-destructive">{nameError}</p>
            ) : (
              <p className="text-xs text-muted-foreground">
                Uppercase snake_case (e.g. API_KEY)
              </p>
            )}
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="secret-value">Value</Label>
            <div className="relative">
              <Input
                id="secret-value"
                type={showValue ? 'text' : 'password'}
                value={value}
                onChange={(e) => setValue(e.target.value)}
                placeholder="Enter secret value"
                className="pr-9"
              />
              <button
                type="button"
                className="absolute right-2 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
                onClick={() => setShowValue((prev) => !prev)}
                aria-label={showValue ? 'Hide value' : 'Show value'}>
                {showValue ? (
                  <EyeOff className="size-4" />
                ) : (
                  <Eye className="size-4" />
                )}
              </button>
            </div>
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="secret-description">
              Description{' '}
              <span className="text-muted-foreground font-normal">
                (optional)
              </span>
            </Label>
            <Textarea
              id="secret-description"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Short description of what this secret is used for"
              rows={3}
            />
          </div>
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={handleClose} disabled={saving}>
            Cancel
          </Button>
          <Button onClick={handleSave} disabled={saving}>
            {saving && <Loader2 className="mr-1 size-4 animate-spin" />}
            Save
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};

// --- EditSecretDialog ---

interface EditSecretDialogProps {
  secret: SecretResponseDto | null;
  onClose: () => void;
  onUpdated: () => void;
}

const EditSecretDialog = ({
  secret,
  onClose,
  onUpdated,
}: EditSecretDialogProps) => {
  const [value, setValue] = useState('');
  const [description, setDescription] = useState('');
  const [showValue, setShowValue] = useState(false);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    if (secret) {
      // eslint-disable-next-line react-hooks/set-state-in-effect -- hydrate edit form when secret prop changes
      setDescription(secret.description ?? '');
      setValue('');
      setShowValue(false);
    }
  }, [secret]);

  const handleClose = () => {
    setValue('');
    setDescription('');
    setShowValue(false);
    onClose();
  };

  const handleSave = async () => {
    if (!secret) {
      return;
    }
    setSaving(true);
    try {
      await secretsApi.update(secret.id, {
        value: value || undefined,
        description: description || null,
      });
      toast.success('Secret updated');
      onUpdated();
      handleClose();
    } catch (err: unknown) {
      toast.error(extractApiErrorMessage(err, 'Failed to update secret'));
    } finally {
      setSaving(false);
    }
  };

  return (
    <Dialog
      open={Boolean(secret)}
      onOpenChange={(o) => {
        if (!o) {
          handleClose();
        }
      }}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Edit Secret</DialogTitle>
          <DialogDescription className="sr-only">
            Update the value or description of an existing secret.
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-4 py-2">
          <div className="space-y-1.5">
            <Label htmlFor="edit-secret-name">Name</Label>
            <Input
              id="edit-secret-name"
              value={secret?.name ?? ''}
              disabled
              readOnly
            />
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="edit-secret-value">Value</Label>
            <div className="relative">
              <Input
                id="edit-secret-value"
                type={showValue ? 'text' : 'password'}
                value={value}
                onChange={(e) => setValue(e.target.value)}
                placeholder="Enter new value to update"
                className="pr-9"
              />
              <button
                type="button"
                className="absolute right-2 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
                onClick={() => setShowValue((prev) => !prev)}
                aria-label={showValue ? 'Hide value' : 'Show value'}>
                {showValue ? (
                  <EyeOff className="size-4" />
                ) : (
                  <Eye className="size-4" />
                )}
              </button>
            </div>
            <p className="text-xs text-muted-foreground">
              Leave blank to keep the current value
            </p>
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="edit-secret-description">
              Description{' '}
              <span className="text-muted-foreground font-normal">
                (optional)
              </span>
            </Label>
            <Textarea
              id="edit-secret-description"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Short description of what this secret is used for"
              rows={3}
            />
          </div>
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={handleClose} disabled={saving}>
            Cancel
          </Button>
          <Button onClick={handleSave} disabled={saving}>
            {saving && <Loader2 className="mr-1 size-4 animate-spin" />}
            Save
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};

// --- DeleteConfirmationDialog ---

interface DeleteConfirmationProps {
  secret: SecretResponseDto | null;
  onClose: () => void;
  onDeleted: () => void;
}

const DeleteConfirmationDialog = ({
  secret,
  onClose,
  onDeleted,
}: DeleteConfirmationProps) => {
  const [deleting, setDeleting] = useState(false);

  const handleDelete = async () => {
    if (!secret) {
      return;
    }
    setDeleting(true);
    try {
      await secretsApi._delete(secret.id);
      toast.success('Secret deleted');
      onDeleted();
      onClose();
    } catch (err: unknown) {
      toast.error(extractApiErrorMessage(err, 'Failed to delete secret'));
    } finally {
      setDeleting(false);
    }
  };

  return (
    <AlertDialog
      open={Boolean(secret)}
      onOpenChange={(o) => {
        if (!o) {
          onClose();
        }
      }}>
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogTitle>Delete Secret</AlertDialogTitle>
          <AlertDialogDescription>
            Are you sure you want to delete{' '}
            <span className="font-semibold">{secret?.name}</span>? This action
            cannot be undone. Any agents using this secret will stop working.
          </AlertDialogDescription>
        </AlertDialogHeader>
        <AlertDialogFooter>
          <AlertDialogCancel disabled={deleting}>Cancel</AlertDialogCancel>
          <AlertDialogAction
            onClick={(e) => {
              e.preventDefault();
              handleDelete();
            }}
            disabled={deleting}
            className="bg-destructive text-destructive-foreground hover:bg-destructive/90">
            {deleting && <Loader2 className="mr-1 size-4 animate-spin" />}
            Delete
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  );
};

// --- SecretsPage ---

export const SecretsPage = () => {
  const [secrets, setSecrets] = useState<SecretResponseDto[]>([]);
  const [loading, setLoading] = useState(true);
  const [createOpen, setCreateOpen] = useState(false);
  const [editSecret, setEditSecret] = useState<SecretResponseDto | null>(null);
  const [deleteSecret, setDeleteSecret] = useState<SecretResponseDto | null>(
    null,
  );

  const fetchSecrets = useCallback(async () => {
    try {
      const response = await secretsApi.list();
      setSecrets(response.data);
    } catch (err: unknown) {
      toast.error(extractApiErrorMessage(err, 'Failed to load secrets'));
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect -- one-shot secrets fetch on mount
    fetchSecrets();
  }, [fetchSecrets]);

  const formatDate = (dateStr: string): string => {
    return new Date(dateStr).toLocaleDateString(undefined, {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  };

  return (
    <div className="space-y-6">
      <div className="flex items-start justify-between">
        <div>
          <h2 className="text-base font-semibold">Secrets</h2>
          <p className="text-sm text-muted-foreground mt-1">
            Manage secret values that can be injected into agent configurations.
          </p>
        </div>
        <Button size="sm" onClick={() => setCreateOpen(true)}>
          <Plus className="mr-1.5 size-4" />
          New Secret
        </Button>
      </div>

      {loading ? (
        <div className="flex items-center justify-center py-12">
          <Loader2 className="size-6 animate-spin text-muted-foreground" />
        </div>
      ) : secrets.length === 0 ? (
        <div className="rounded-md border border-dashed py-12 text-center text-sm text-muted-foreground">
          No secrets configured. Create one to get started.
        </div>
      ) : (
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Name</TableHead>
              <TableHead>Description</TableHead>
              <TableHead>Created</TableHead>
              <TableHead className="w-20" />
            </TableRow>
          </TableHeader>
          <TableBody>
            {secrets.map((secret) => (
              <TableRow key={secret.id}>
                <TableCell className="font-mono font-medium">
                  {secret.name}
                </TableCell>
                <TableCell className="text-muted-foreground">
                  {secret.description ?? (
                    <span className="italic">No description</span>
                  )}
                </TableCell>
                <TableCell className="text-muted-foreground">
                  {formatDate(secret.createdAt)}
                </TableCell>
                <TableCell>
                  <div className="flex items-center gap-1">
                    <Button
                      variant="ghost"
                      size="icon"
                      className="size-7"
                      aria-label="Edit secret"
                      onClick={() => setEditSecret(secret)}>
                      <Pencil className="size-3.5" />
                    </Button>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="size-7 text-destructive hover:text-destructive"
                      aria-label="Delete secret"
                      onClick={() => setDeleteSecret(secret)}>
                      <Trash2 className="size-3.5" />
                    </Button>
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      )}

      <CreateSecretDialog
        open={createOpen}
        onClose={() => setCreateOpen(false)}
        onCreated={fetchSecrets}
      />
      <EditSecretDialog
        secret={editSecret}
        onClose={() => setEditSecret(null)}
        onUpdated={fetchSecrets}
      />
      <DeleteConfirmationDialog
        secret={deleteSecret}
        onClose={() => setDeleteSecret(null)}
        onDeleted={fetchSecrets}
      />
    </div>
  );
};
