// @vitest-environment jsdom
import { act, renderHook, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

// ── Module mocks ──────────────────────────────────────────────────────────────

// Mock the API module — controls the apiTotal side of the hook.
vi.mock('../../../api', () => ({
  threadsApi: {
    getThreadUsageStatistics: vi.fn(),
  },
}));

// ── Imports after mocks ───────────────────────────────────────────────────────

import { threadsApi } from '../../../api';
import type { ThreadDto } from '../../../autogenerated';
import type { ThreadTokenUsageSnapshot } from '../types';
import { useChatsUsageStats } from './useChatsUsageStats';

// ── Helpers ───────────────────────────────────────────────────────────────────

const toastMessage = {
  success: vi.fn(),
  error: vi.fn(),
  warning: vi.fn(),
  info: vi.fn(),
  loading: vi.fn(),
  open: vi.fn(),
  destroy: vi.fn(),
};

const makeThread = (overrides: Partial<ThreadDto> = {}): ThreadDto =>
  ({
    id: 'thread-1',
    graphId: 'graph-1',
    status: 'running',
    effectiveCostLimitUsd: null,
    name: 'Test thread',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    ...overrides,
  }) as unknown as ThreadDto;

const makeUsageStats = (total: Partial<ThreadTokenUsageSnapshot>) => ({
  data: {
    total: {
      inputTokens: 0,
      cachedInputTokens: 0,
      outputTokens: 0,
      reasoningTokens: 0,
      totalTokens: 0,
      totalPrice: 0,
      currentContext: 0,
      ...total,
    },
    byNode: {
      'node-1': {
        inputTokens: total.inputTokens ?? 0,
        cachedInputTokens: total.cachedInputTokens ?? 0,
        outputTokens: total.outputTokens ?? 0,
        reasoningTokens: total.reasoningTokens ?? 0,
        totalTokens: total.totalTokens ?? 0,
        totalPrice: total.totalPrice,
        currentContext: total.currentContext ?? 0,
      },
    },
  },
});

const makeAggregateByNode = (
  snap: Partial<ThreadTokenUsageSnapshot>,
): Record<string, Record<string, ThreadTokenUsageSnapshot>> => ({
  'thread-1': {
    'node-1': {
      inputTokens: snap.inputTokens ?? 0,
      cachedInputTokens: snap.cachedInputTokens ?? 0,
      outputTokens: snap.outputTokens ?? 0,
      reasoningTokens: snap.reasoningTokens ?? 0,
      totalTokens: snap.totalTokens ?? 0,
      totalPrice: snap.totalPrice,
      currentContext: snap.currentContext ?? 0,
    },
  },
});

// ── Shared teardown ───────────────────────────────────────────────────────────

afterEach(() => {
  vi.clearAllMocks();
});

// ── Tests ─────────────────────────────────────────────────────────────────────

describe('useChatsUsageStats — selectedThreadThreadUsage', () => {
  beforeEach(() => {
    // Default: API returns zero stats so tests that set aggregate can compare clearly.
    (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mockResolvedValue(makeUsageStats({ totalPrice: 0, totalTokens: 0 }));
  });

  it('returns aggregate fields when Running regardless of apiTotal magnitude (single-source policy)', async () => {
    // apiTotal has higher totalPrice than aggregate — but single-source policy means aggregate wins
    (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mockResolvedValue(
      makeUsageStats({
        inputTokens: 200,
        outputTokens: 100,
        totalTokens: 300,
        totalPrice: 0.3,
        currentContext: 5000,
      }),
    );

    const selectedThread = makeThread({ status: 'running' });

    const { result } = renderHook(() =>
      useChatsUsageStats({
        toastMessage,
        selectedThread,
        selectedThreadId: 'thread-1',
        selectedThreadIsDraft: false,
        selectedAgentNodeId: null,
        graphCache: {},
        getFullGraph: () => undefined,
      }),
    );

    // Set aggregate with lower values than apiTotal
    act(() => {
      result.current.setThreadTokenUsageByNode(
        makeAggregateByNode({
          inputTokens: 100,
          outputTokens: 50,
          totalTokens: 150,
          totalPrice: 0.1,
          currentContext: 3000,
        }),
      );
    });

    // Wait for API fetch to complete (hook auto-loads on mount), then verify aggregate wins
    await waitFor(() => {
      const usage = result.current.selectedThreadThreadUsage;
      expect(usage?.totalPrice).toBe(0.1);
    });

    const usage = result.current.selectedThreadThreadUsage;
    expect(usage?.inputTokens).toBe(100);
    expect(usage?.outputTokens).toBe(50);
    expect(usage?.totalTokens).toBe(150);
    expect(usage?.totalPrice).toBe(0.1);
    // Single-source policy: while running, aggregate wins for all fields including currentContext
    expect(usage?.currentContext).toBe(3000);
  });

  it('returns aggregate fields when Running (single-source policy)', async () => {
    // apiTotal has lower totalPrice than aggregate
    (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mockResolvedValue(
      makeUsageStats({
        inputTokens: 50,
        outputTokens: 25,
        totalTokens: 75,
        totalPrice: 0.05,
        currentContext: 1000,
      }),
    );

    const selectedThread = makeThread({ status: 'running' });

    const { result } = renderHook(() =>
      useChatsUsageStats({
        toastMessage,
        selectedThread,
        selectedThreadId: 'thread-1',
        selectedThreadIsDraft: false,
        selectedAgentNodeId: null,
        graphCache: {},
        getFullGraph: () => undefined,
      }),
    );

    // Set aggregate with higher values than apiTotal
    act(() => {
      result.current.setThreadTokenUsageByNode(
        makeAggregateByNode({
          inputTokens: 300,
          outputTokens: 200,
          totalTokens: 500,
          totalPrice: 0.5,
          currentContext: 8000,
        }),
      );
    });

    await waitFor(() => {
      const usage = result.current.selectedThreadThreadUsage;
      expect(usage?.totalPrice).toBe(0.5);
    });

    const usage = result.current.selectedThreadThreadUsage;
    expect(usage?.inputTokens).toBe(300);
    expect(usage?.outputTokens).toBe(200);
    expect(usage?.totalTokens).toBe(500);
    expect(usage?.totalPrice).toBe(0.5);
    // Single-source policy: while running, aggregate wins for all fields including currentContext
    expect(usage?.currentContext).toBe(8000);
  });

  it('returns apiTotal when thread is Stopped', async () => {
    (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mockResolvedValue(
      makeUsageStats({
        inputTokens: 400,
        outputTokens: 250,
        totalTokens: 650,
        totalPrice: 0.42,
        currentContext: 6000,
      }),
    );

    const selectedThread = makeThread({ status: 'stopped' });

    const { result } = renderHook(() =>
      useChatsUsageStats({
        toastMessage,
        selectedThread,
        selectedThreadId: 'thread-1',
        selectedThreadIsDraft: false,
        selectedAgentNodeId: null,
        graphCache: {},
        getFullGraph: () => undefined,
      }),
    );

    // Aggregate also has data — stopped thread must prefer apiTotal
    act(() => {
      result.current.setThreadTokenUsageByNode(
        makeAggregateByNode({
          inputTokens: 100,
          totalPrice: 0.1,
        }),
      );
    });

    await waitFor(() => {
      const usage = result.current.selectedThreadThreadUsage;
      expect(usage?.totalPrice).toBe(0.42);
    });

    const usage = result.current.selectedThreadThreadUsage;
    expect(usage?.inputTokens).toBe(400);
    expect(usage?.outputTokens).toBe(250);
    expect(usage?.totalTokens).toBe(650);
    expect(usage?.totalPrice).toBe(0.42);
  });

  it('includes effectiveCostLimitUsd from selectedThread', async () => {
    (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mockResolvedValue(makeUsageStats({ totalPrice: 0.1 }));

    const selectedThread = makeThread({
      status: 'running',
      effectiveCostLimitUsd: 5,
    });

    const { result } = renderHook(() =>
      useChatsUsageStats({
        toastMessage,
        selectedThread,
        selectedThreadId: 'thread-1',
        selectedThreadIsDraft: false,
        selectedAgentNodeId: null,
        graphCache: {},
        getFullGraph: () => undefined,
      }),
    );

    act(() => {
      result.current.setThreadTokenUsageByNode(
        makeAggregateByNode({ totalPrice: 0.1 }),
      );
    });

    await waitFor(() => {
      const usage = result.current.selectedThreadThreadUsage;
      expect(usage).toBeDefined();
    });

    const usage = result.current.selectedThreadThreadUsage;
    expect(usage?.effectiveCostLimitUsd).toBe(5);
  });

  // Scenario 3.3: Running + aggregate.totalPrice > apiTotal.totalPrice → hook returns withLimit(aggregate).
  // Covered by 'returns aggregate fields when Running (single-source policy)' above — that test
  // explicitly sets aggregate higher than apiTotal and asserts field-for-field equality with aggregate.

  // Scenario 3.4: running→done transition triggers exactly one fetch; extra re-render without
  // status change must NOT fire another fetch (StrictMode / redundant render safety).
  // Scenario 3.4: running→done transition triggers exactly one fetch; extra re-render without
  // status change must NOT fire another fetch (StrictMode / redundant render safety).
  it('fetches once on running→done transition and not again on a redundant re-render (3.4)', async () => {
    (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mockResolvedValue(makeUsageStats({ totalPrice: 0.2 }));

    const runningThread = makeThread({ status: 'running' });
    const doneThread = makeThread({ status: 'done' });

    const { rerender } = renderHook(
      (props: { thread: typeof runningThread }) =>
        useChatsUsageStats({
          toastMessage,
          selectedThread: props.thread,
          selectedThreadId: 'thread-1',
          selectedThreadIsDraft: false,
          selectedAgentNodeId: null,
          graphCache: {},
          getFullGraph: () => undefined,
        }),
      { initialProps: { thread: runningThread } },
    );

    // Let the mount-fetch settle so its call is counted.
    await waitFor(() => {
      expect(
        threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>,
      ).toHaveBeenCalled();
    });

    // Reset mock call count so we isolate transition-triggered fetches.
    (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mockClear();

    // Transition: running → done — must trigger exactly one fetch.
    rerender({ thread: doneThread });

    await waitFor(() => {
      expect(
        threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>,
      ).toHaveBeenCalledTimes(1);
    });

    expect(
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>,
    ).toHaveBeenCalledWith('thread-1');

    // Reset again to verify redundant re-render (same status) does NOT fire another fetch.
    (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mockClear();

    // Re-render with same done status — must NOT fire fetch.
    // Use fake timers so the assertion is deterministic regardless of CI load (H4 fix).
    vi.useFakeTimers();
    rerender({ thread: makeThread({ status: 'done' }) });
    vi.runAllTimers();
    await Promise.resolve(); // flush microtasks
    vi.useRealTimers();

    expect(
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>,
    ).not.toHaveBeenCalled();
  });

  it('Change 2: running thread — inFlightSubagentPrice folds into aggregate totalPrice and is exposed as selectedThreadHeaderInFlightSum', async () => {
    // API returns a baseline so the running→done logic has something to fetch.
    (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mockResolvedValue(makeUsageStats({ totalPrice: 0.05, totalTokens: 10 }));

    const selectedThread = makeThread({ status: 'running' });

    const { result } = renderHook(() =>
      useChatsUsageStats({
        toastMessage,
        selectedThread,
        selectedThreadId: 'thread-1',
        selectedThreadIsDraft: false,
        selectedAgentNodeId: null,
        graphCache: {},
        getFullGraph: () => undefined,
      }),
    );

    // Seed a node snapshot that carries both a scalar totalPrice and an
    // inFlightSubagentPrice map with a live subagent accumulating cost.
    act(() => {
      result.current.setThreadTokenUsageByNode({
        'thread-1': {
          'node-1': {
            inputTokens: 100,
            outputTokens: 50,
            totalTokens: 150,
            totalPrice: 0.05,
            currentContext: 1000,
            inFlightSubagentPrice: { 'tc-A': 0.15 },
          },
        },
      });
    });

    // While running, the hook folds inFlightSubagentPrice into totalPrice.
    await waitFor(() => {
      expect(result.current.selectedThreadHeaderUsage?.totalPrice).toBeCloseTo(
        0.2,
        10,
      );
    });

    // selectedThreadHeaderInFlightSum exposes the raw in-flight portion so the
    // UI can render "$0.05 + $0.15 in-flight".
    expect(result.current.selectedThreadHeaderInFlightSum).toBeCloseTo(
      0.15,
      10,
    );

    // Aggregate total = scalar (0.05) + in-flight (0.15) = 0.20.
    expect(result.current.selectedThreadHeaderUsage?.totalPrice).toBeCloseTo(
      0.2,
      10,
    );
  });

  it('Change 2: not-running thread — inFlightSubagentPrice is ignored; suffix sum is 0', async () => {
    // REST is authoritative once done/stopped; API returns the final settled total.
    (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mockResolvedValue(makeUsageStats({ totalPrice: 0.05, totalTokens: 10 }));

    const selectedThread = makeThread({ status: 'done' });

    const { result } = renderHook(() =>
      useChatsUsageStats({
        toastMessage,
        selectedThread,
        selectedThreadId: 'thread-1',
        selectedThreadIsDraft: false,
        selectedAgentNodeId: null,
        graphCache: {},
        getFullGraph: () => undefined,
      }),
    );

    // Same node snapshot as the running test — totalPrice: 0.05 scalar plus
    // an inFlightSubagentPrice entry that must be ignored when done.
    act(() => {
      result.current.setThreadTokenUsageByNode({
        'thread-1': {
          'node-1': {
            inputTokens: 100,
            outputTokens: 50,
            totalTokens: 150,
            totalPrice: 0.05,
            currentContext: 1000,
            inFlightSubagentPrice: { 'tc-A': 0.15 },
          },
        },
      });
    });

    // Wait for the API fetch that a done-status mount triggers.
    await waitFor(() => {
      expect(
        threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>,
      ).toHaveBeenCalledWith('thread-1');
    });

    // selectedThreadHeaderInFlightSum must be 0 — suffix must not render.
    await waitFor(() => {
      expect(result.current.selectedThreadHeaderInFlightSum).toBe(0);
    });

    // totalPrice must reflect the authoritative REST snapshot (0.05), not the
    // sum with in-flight (which would be 0.20). The in-flight portion is ignored.
    await waitFor(() => {
      expect(result.current.selectedThreadHeaderUsage?.totalPrice).toBeCloseTo(
        0.05,
        10,
      );
    });
  });

  it('Change 2: not-running + apiTotal absent (race window) — totalPrice equals scalar-only aggregate, not inflated 0.20', async () => {
    // Simulate the running→done race window: the API fetch has not completed yet
    // (apiTotal is undefined). The aggregate must NOT fold inFlightSubagentPrice
    // into totalPrice so the fallback path (apiTotal ?? aggregate) returns the
    // scalar-only value (0.05) rather than the inflated value (0.20).
    (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mockImplementation(
      () => new Promise(() => {}), // never resolves — keeps apiTotal undefined
    );

    const selectedThread = makeThread({ status: 'done' });

    const { result } = renderHook(() =>
      useChatsUsageStats({
        toastMessage,
        selectedThread,
        selectedThreadId: 'thread-1',
        selectedThreadIsDraft: false,
        selectedAgentNodeId: null,
        graphCache: {},
        getFullGraph: () => undefined,
      }),
    );

    // Seed the same node snapshot used in the running test — scalar 0.05 plus
    // an inFlightSubagentPrice entry worth 0.15 that must be excluded when done.
    act(() => {
      result.current.setThreadTokenUsageByNode({
        'thread-1': {
          'node-1': {
            inputTokens: 100,
            outputTokens: 50,
            totalTokens: 150,
            totalPrice: 0.05,
            currentContext: 1000,
            inFlightSubagentPrice: { 'tc-A': 0.15 },
          },
        },
      });
    });

    // apiTotal stays undefined (API call is pending). The !isRunning fallback
    // must use the aggregate WITHOUT the inflight fold, so totalPrice === 0.05.
    await waitFor(() => {
      expect(result.current.selectedThreadHeaderUsage?.totalPrice).toBeCloseTo(
        0.05,
        10,
      );
    });

    // The inflated value (scalar + inflight = 0.20) must NOT appear.
    expect(
      result.current.selectedThreadHeaderUsage?.totalPrice,
    ).not.toBeCloseTo(0.2, 5);

    // selectedThreadHeaderInFlightSum must still be 0 when done.
    expect(result.current.selectedThreadHeaderInFlightSum).toBe(0);
  });

  it('does not fetch when switching from a running thread to a different thread that is already done', async () => {
    // Pre-populate stats for thread B so the mount-effect short-circuits and
    // does not call getThreadUsageStatistics at all, leaving only the transition
    // effect to potentially trigger a fetch.
    (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mockResolvedValue(makeUsageStats({ totalPrice: 0.1 }));

    const threadA = makeThread({ id: 'a', status: 'running' });
    const threadB = makeThread({ id: 'b', status: 'done' });

    const { rerender, result } = renderHook(
      (props: { thread: typeof threadA; threadId: string }) =>
        useChatsUsageStats({
          toastMessage,
          selectedThread: props.thread,
          selectedThreadId: props.threadId,
          selectedThreadIsDraft: false,
          selectedAgentNodeId: null,
          graphCache: {},
          getFullGraph: () => undefined,
        }),
      { initialProps: { thread: threadA, threadId: 'a' } },
    );

    // Let mount-effect for thread A settle.
    await waitFor(() => {
      expect(
        threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>,
      ).toHaveBeenCalledWith('a');
    });

    // Reset so we can assert cleanly on thread B calls only.
    (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mockClear();

    // Switch to thread B (different id, already done — never ran→done on its own).
    // The transition effect must NOT fire a fetch for B because B's identity changed,
    // not because B transitioned from running.
    vi.useFakeTimers();
    rerender({ thread: threadB, threadId: 'b' });
    vi.runAllTimers();
    await Promise.resolve(); // flush microtasks
    vi.useRealTimers();

    // The transition effect must not have fired for thread B.
    // (The mount effect may call once for B if stats are missing — that is acceptable,
    // but we assert the count is at most 1, not 2, ruling out a double fetch.)
    const callsForB = (
      threadsApi.getThreadUsageStatistics as ReturnType<typeof vi.fn>
    ).mock.calls.filter((args: unknown[]) => args[0] === 'b');
    expect(callsForB.length).toBeLessThanOrEqual(1);

    // Row 7 (thread-switch during running): after switching to thread B the hook
    // must not display thread A's stale stats for thread B.
    // The mock resolves with totalPrice: 0.1 for any threadId. If a fetch occurred for
    // thread B, selectedThreadThreadUsage.totalPrice must be 0.1 (not stale thread A data).
    // Allow time for any pending fetch and state update to settle.
    await waitFor(() => {
      expect(result.current.selectedThreadThreadUsage).toBeDefined();
      expect(result.current.selectedThreadThreadUsage?.totalPrice).toBeCloseTo(
        0.1,
        5,
      );
    });
  });
});
