import { useEffect, useState } from 'react';

import { ThreadDtoStatusEnum } from '../../../autogenerated/api';

export function useLiveThreadDuration(args: {
  runningStartedAt: string | null | undefined;
  totalRunningMs: number | undefined;
  status: ThreadDtoStatusEnum | string | undefined;
}): number {
  const { runningStartedAt, totalRunningMs, status } = args;

  const [nowMs, setNowMs] = useState<number>(() => Date.now());

  const isRunning = status === ThreadDtoStatusEnum.Running;

  const startedAtMs =
    isRunning && runningStartedAt != null
      ? new Date(runningStartedAt).getTime()
      : NaN;

  const validStartedAt = !Number.isNaN(startedAtMs);

  useEffect(() => {
    if (!isRunning || !validStartedAt) {
      return;
    }

    setNowMs(Date.now()); // immediate refresh on transition into Running
    const id = setInterval(() => {
      setNowMs(Date.now());
    }, 1000);

    return () => {
      clearInterval(id);
    };
    // startedAtMs is intentionally excluded: it is a render-scope derived value
    // (not an effect dependency). Including it would cause interval teardown on
    // every render where runningStartedAt reference changes (common via WebSocket
    // re-renders), creating 1-second tick gaps and spurious immediate refreshes.
  }, [isRunning, validStartedAt]);

  if (isRunning && validStartedAt) {
    return (totalRunningMs ?? 0) + Math.max(0, nowMs - startedAtMs);
  }

  return totalRunningMs ?? 0;
}
