import {
  type AgentMemoryEntryDto,
  AgentMemoryEntryDtoModeEnum,
} from '../../autogenerated';
import { MemoryEntriesTable } from '../memory/MemoryEntriesTable';

const SAMPLE_ENTRIES: AgentMemoryEntryDto[] = [
  {
    id: '1',
    projectId: 'p1',
    namespace: 'conventions',
    key: 'package-manager',
    title: 'Package manager',
    value: 'Uses a single package manager across the repo.',
    mode: AgentMemoryEntryDtoModeEnum.Kv,
    authorAgentId: 'Engineer',
    tags: ['build'],
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: '2',
    projectId: 'p1',
    namespace: 'learnings',
    key: '2026-01-02T00:00:00.000Z-9f1c',
    title: 'A learning worth keeping',
    value: 'An accumulating note future sessions can read back in order.',
    mode: AgentMemoryEntryDtoModeEnum.Append,
    authorAgentId: 'Reviewer',
    tags: ['db', 'migrations'],
    createdAt: '2026-01-02T00:00:00.000Z',
    updatedAt: '2026-01-02T00:00:00.000Z',
  },
];

const noop = () => {};

/**
 * Storybook section for the Project Memory page's entries table, in its three
 * states. The table is presentational (page owns data + dialogs), so fixture
 * props drive it without any API. KV rows show edit + delete; append rows are
 * immutable and show no actions.
 */
export function MemorySection() {
  return (
    <section id="project-memory" className="scroll-mt-6">
      <div className="mb-4">
        <h2 className="text-base font-semibold">Project Memory</h2>
        <p className="text-muted-foreground mt-0.5 text-sm">
          Durable per-project memory entries table — loading, empty, and
          populated states.
        </p>
      </div>
      <div className="border-border divide-border divide-y overflow-hidden rounded-lg border">
        <div className="space-y-2 px-5 py-4">
          <p className="text-foreground text-xs font-medium">Loading</p>
          <MemoryEntriesTable
            entries={[]}
            loading
            onEdit={noop}
            onDelete={noop}
          />
        </div>
        <div className="space-y-2 px-5 py-4">
          <p className="text-foreground text-xs font-medium">Empty</p>
          <MemoryEntriesTable
            entries={[]}
            loading={false}
            onEdit={noop}
            onDelete={noop}
          />
        </div>
        <div className="space-y-2 px-5 py-4">
          <p className="text-foreground text-xs font-medium">Populated</p>
          <MemoryEntriesTable
            entries={SAMPLE_ENTRIES}
            loading={false}
            onEdit={noop}
            onDelete={noop}
          />
        </div>
      </div>
    </section>
  );
}
